### ISSUE TITLE
 Azure DevOps Demo Generator

### ISSUE THREAD

**Issue by cheikhkub** [microsoft/AzureDevOpsDemoGenerator#1000]
i go this message below when i created a new project PartsUnlimited
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

**Comment by aksh-h** [comment]
@cheikhkub please try again by creating a new project. If you experience the same issue, click on the ```view diagnostic logs``` button to see more detailed logs and share it with us.
