### ISSUE TITLE
Issue deploying SmartHotel360 Template

### ISSUE THREAD

**Issue by Randolph1911** [microsoft/AzureDevOpsDemoGenerator#1002]
"Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1"

After attempting to deploy the SmartHotel360 template, and following all of the prompts along the side to console for classic release pipelines, and headind the message about ARM outputs...

**Comment by aksh-h** [comment]
@Randolph1911 If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.
