### ISSUE TITLE
creating project fails

### ISSUE THREAD

**Issue by sahil730** [microsoft/AzureDevOpsDemoGenerator#1003]
creating projecting with default templates failing

**Comment by sashabatin** [comment]
faced the similar problem.

**Comment by aksh-h** [comment]
@sahil730 & @sashabatin Can you please provide additional details about the issue you experienced?

**Comment by aksh-h** [comment]
Go to organizational setting -> policies -> enable allow third-party access

![image](https://github.com/user-attachments/assets/3a20c6f0-b643-4be3-a687-316f0f77d4c6)
