### ISSUE TITLE
Azure DevOps Demo Generator - Terraform Error

### ISSUE THREAD

**Issue by rijwanansari** [microsoft/AzureDevOpsDemoGenerator#1005]
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
Please install the [Terraform](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks) extension from the marketplace and try to provision the project again.
