### ISSUE TITLE
redirected to verify 

### ISSUE THREAD

**Issue by cdunnink** [microsoft/AzureDevOpsDemoGenerator#1008]
When I click the link "build your template", I get redirected to "https://azuredevopsdemogenerator.azurewebsites.net/Account/Verify". I am a member of the "Project Collection Administrators" of my organization.  has anybody an idea?

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/83016387/e4b4d567-c5a1-402f-b88e-f5159be88c38)

**Comment by aksh-h** [comment]
@cdunninkIt seems that the authentication process has failed. Please log in again and try once more.
