### ISSUE TITLE
VS402362: No process template with type <GUID> was found

### ISSUE THREAD

**Issue by Castle1979** [microsoft/AzureDevOpsDemoGenerator#1017]
I have created a private template based on a current project in a different organisation but on trying to create a project using the template I get this error … any suggestions.

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/80288141/de9d5382-3a2a-45a3-af35-44b004dfdf3d)

**Comment by aksh-h** [comment]
@Castle1979 It is possible to encounter an issue where the process template Ids differ in the source and target organizations. This may occur if you exported a project that belongs to a custom or inherited process in the source organization. To ensure proper mapping in the target organization, Azure DevOps Demo Generator requires the same process template to be used.
