### ISSUE TITLE
Error during cretaing a new project based on Terraform template

### ISSUE THREAD

**Issue by bshelat** [microsoft/AzureDevOpsDemoGenerator#1018]
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Install the [Replace Tokens](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens) and [Terraform](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks) extensions from marketplace.

Run the demo generator again and try to install the extension needed by the template.
