### ISSUE TITLE
Error while creating a Project using Ansible Template

### ISSUE THREAD

**Issue by Vijay-333** [microsoft/AzureDevOpsDemoGenerator#1021]
Error Description:
Error while creating release definition: Tasks with versions 'Replace variables in Ansible script to deploy Azure resources:4.*, Run playbook to deploy Azure resources:0.*' are not valid for deploy job 'Agent job' in stage Azure Dev.

PS: I'm using free tier organization.

**Comment by aksh-h** [comment]
@Vijay-333 install the extension Ansible from [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-ansible), then try provisioning the project.
