### ISSUE TITLE
Got an error while creating the Custom Template using my Template project.

### ISSUE THREAD

**Issue by VikramSanap1** [microsoft/AzureDevOpsDemoGenerator#1024]
While creating the template using 'Build Your Template' option on Demo Generator I got following error message: 
"Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist."

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/117803096/2b933594-10f8-4c1e-8454-42aaa1003d1d)

**Comment by aksh-h** [comment]
@VikramSanap1 Thank you for reaching us. Template builder has the limited support on exporting the projects as the template.

Could you please provide more information on the project and the process template used by the project.
If it is custom or inherited, what are the backlog levels you have.
