### ISSUE TITLE
 Error while creating build definition: The classic pipelines are disabled for this project / organization

### ISSUE THREAD

**Issue by Donsufia** [microsoft/AzureDevOpsDemoGenerator#1029]
I encountered this error message,

 Error while creating build definition: The classic pipelines are disabled for this project / organization

kindly help me to fix it

**Comment by aksh-h** [comment]
By default, classic pipeline creation has been disabled for new organizations. To enable it, go to organization settings and provision the project. 

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/38463158/b5f894e8-074d-4c12-9cff-c9955a3d8caf)
