### ISSUE TITLE
Unable to create the project on ADO

### ISSUE THREAD

**Issue by nareshmanam** [microsoft/AzureDevOpsDemoGenerator#1034]
Unable to create the project on ADO

Sorry….We ran into an issue!
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

**Comment by aksh-h** [comment]
Go to organizational setting -> policies -> enable allow third-party access

![image](https://github.com/user-attachments/assets/3a20c6f0-b643-4be3-a687-316f0f77d4c6)

Try provision the project again.
