### ISSUE TITLE
cannot create project

### ISSUE THREAD

**Issue by mtlong142** [microsoft/AzureDevOpsDemoGenerator#1035]
Error while creating release definition: The classic pipelines are disabled for this project / organization.

**Comment by aksh-h** [comment]
Go to organizational setting -> policies -> enable allow third-party access. Once you do the below settings you can try provisioning the project again.

![image](https://github.com/user-attachments/assets/3a20c6f0-b643-4be3-a687-316f0f77d4c6)

![Image](https://github.com/user-attachments/assets/8378cb67-e5cf-458e-81e2-6abd1fac87a6)
