### ISSUE TITLE
provisioning failed

### ISSUE THREAD

**Issue by mbommena** [microsoft/AzureDevOpsDemoGenerator#1036]
Error while creating build definition: The classic pipelines are disabled for this project / organization.

**Comment by david-cesal-adeon** [comment]
![image](https://github.com/user-attachments/assets/4cac4037-b76e-4ada-9fbe-21694d0f327d)
I confirm that generator is not working at all. Nothing is deployed.

**Comment by Dacesilian** [comment]
I confirm that generator is not working, nothing is deployed.
![image](https://github.com/user-attachments/assets/af5ccd95-5464-4046-9339-b9c89f6d9d36)
