### ISSUE TITLE
error while created demo Azure devops project

### ISSUE THREAD

**Issue by rovark** [microsoft/AzureDevOpsDemoGenerator#1038]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)

**Comment by aksh-h** [comment]
Install the [Bower](https://marketplace.visualstudio.com/items?itemName=touchify.vsts-bower) extension from Marketplace and try again to provision the project,
