### ISSUE TITLE
enable the classic build and release pipeline!!

### ISSUE THREAD

**Issue by saiarshad** [microsoft/AzureDevOpsDemoGenerator#1039]
Even after disabling the "Disable creation of classic build pipelines" & "Disable creation of classic release pipelines". 
I am unable to create the project using selected templet.

<img width="749" alt="Screenshot 2024-06-26 123319" src="https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/171698268/9c85bae0-105c-4eab-be75-9b2be287a8a1">
<img width="601" alt="Screenshot 2024-06-26 123419" src="https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/171698268/82d4b1b0-190d-4585-84fa-6cce64ced6ba">

**Comment by aksh-h** [comment]
Please try to provision the project again
