### ISSUE TITLE
Projects are not created

### ISSUE THREAD

**Issue by nzenginel** [microsoft/AzureDevOpsDemoGenerator#1040]
Hi,
We're trying to create projects using demo generator. After clicking Create Project button, it immediately says the provision is successful but nothing is created. We've tried with different organizations and different templates; the result is the same:

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/167362958/2e8ebb77-6120-4d27-bc3c-a6f2fcb88ba6)

**Comment by nzenginel** [comment]
Yes, thank you @jan-marten , that was the solution to my problem.

**Comment by SilvaEric** [comment]
Estava esbarrando no mesmo problema, em outros templates era possivel habilitar o Oauth diretamente quando o mesmo era selecionado.
Habilitar o Oauth na organização resolveu !!

**Comment by Ihtisham-Khattak** [comment]
> I stumbled on this too. Solution seems to be to enable OAuth;
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/2071232/343213540-2cb3d1bb-48e1-4c9b-a2af-d7c85056750d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjgzNjcsIm5iZiI6MTcyNDIyODA2NywicGF0aCI6Ii8yMDcxMjMyLzM0MzIxMzU0MC0yY2IzZDFiYi00OGUxLTRjOWItYTJhZi1kN2M4NTA1Njc1MGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMDgxNDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTllNDI5ODNlYjMxMmQ3NGRhYTNlYTUxOWUxMGNkMDI4ZjM2YTI5MDBjMWNkMTkyOWE0NjYxZjI3YTUzY2U3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._8m-V74qEWoHm2JhHxdYlNUKRSOSSJtdLyQeDrNYA8w)

Thank You @jan-marten
