### ISSUE TITLE
azure devops demo generator failed to navigate to project

### ISSUE THREAD

**Issue by itsmeajam** [microsoft/AzureDevOpsDemoGenerator#1042]
I got this error after creating then navigating to project:

404 - Page not found
Looks like this page doesn’t exist or can’t be found. Make sure the project name and URL are correct.
27/6/2024 8:20:37 AM (UTC)
63725626-dd41-4372-8fae-dfaa6b4704a6

**Comment by aksh-h** [comment]
Please enable the third party authentication vai oAuth option in your organization settings and try to provision the project,
Refer to #1040
