### ISSUE TITLE
Unable to create demo project

### ISSUE THREAD

**Issue by iamamulya** [microsoft/AzureDevOpsDemoGenerator#1044]
HI team,

after i  selected the project template, name, and organization and clicked on create, it showing creating project, but within 5 sec it showed creation is complete. it not show any detail of the repo, files under the project. When i  clicked on navigate to  project it showing "404 - Page not found" error. i have even disabled the organizational settings also (If you're using brand new organization, please enable the creation of classic build and relase pipeline by disabling the following flag under Organization Settings >> Pipelines >> Settings[ here.](https://azuredevopsdemogenerator.azurewebsites.net/Images/enable_classic.png)).. Please help me with this

**Comment by JCFM-GH** [comment]
I had the same issue. This solved the problem:
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1040#issuecomment-2191912961

**Comment by iamamulya** [comment]
thanks @JCFM-GH , it worked

**Comment by iamamulya** [comment]
.
