### ISSUE TITLE
Azure DevOps Demo Generator (Manage Agile software delivery plans across teams) Template not working

### ISSUE THREAD

**Issue by mhmPM** [microsoft/AzureDevOpsDemoGenerator#1047]
Even after disabling the flags as mentioned in the page, I am still not able to create the project in my account. Do help me out as this is blocking my completion of this course. 
![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/175008977/fc81d039-8481-4b07-ab03-0d713e7ad971)

I am still getting this error.
![AzureDevopsImage](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/175008977/cd723f00-0e0f-4823-b851-1a3218c6969d)

**Comment by Claudine-Simonsen** [comment]
@mhmPM I had a similar issues. This solved the problem:
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1040#issuecomment-2191912961
