### ISSUE TITLE
Azure devops demo generator

### ISSUE THREAD

**Issue by Sharmi7898** [microsoft/AzureDevOpsDemoGenerator#1048]
Copy Diagnostic Log
×
Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: The classic pipelines are disabled for this project / organization.

**Comment by aksh-h** [comment]
If you're using a brand new organization, please enable the creation of a classic build and release pipeline by disabling the following flag under Organization Settings >> Pipelines >> Settings
![image](https://github.com/user-attachments/assets/150ff486-acbd-4b25-bf3c-c08855db8de8)
