### ISSUE TITLE
Error while creating project in azure-devops-generator

### ISSUE THREAD

**Issue by sribettagere** [microsoft/AzureDevOpsDemoGenerator#1051]
While creating project I got this error.
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

I enabled the creation of classic build pipelines and  creation of classic release pipelines in my organisation setting and still cannot create project

**Comment by aksh-h** [comment]
@sribettagere is this issue specific to the creation of classic pipelines? please share more details. 
The classic pipeline should be created if you've enabled the flags in the organization settings.
