### ISSUE TITLE
404 when navigating to the project after creation

### ISSUE THREAD

**Issue by cfloydtandem** [microsoft/AzureDevOpsDemoGenerator#1053]
When creating the project, it is returning a 404 error after clinking the link.

https://dev.azure.com/TandemDemo/Floyd

![image](https://github.com/user-attachments/assets/eaa43fb3-ece4-43f7-a743-2ce626cd5289)

**Comment by cfloydtandem** [comment]
![image](https://github.com/user-attachments/assets/c3b6fd06-4c5d-43a8-9cc6-6cc4076bc6fa)

**Comment by Wass09** [comment]
I have the same problem and already started from scratch many times, did you find any solution?

**Comment by MMS-RBKN** [comment]
For me https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1040#issuecomment-2191912961 was the solution. Maybe it will help you as well.

**Comment by aksh-h** [comment]
Go to organizational setting -> policies -> enable allow third-party access

![image](https://github.com/user-attachments/assets/3a20c6f0-b643-4be3-a687-316f0f77d4c6)
