### ISSUE TITLE
IT is not wortking 

### ISSUE THREAD

**Issue by Wass09** [microsoft/AzureDevOpsDemoGenerator#1054]
I am just starting the course for devops and using the tool to create a project does not work i created the ADO_ORG and PAT, it says project created but i cannot find it anywhere

**Comment by MMS-RBKN** [comment]
For me https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1040#issuecomment-2191912961 was the solution. Maybe it will help you as well.

**Comment by aksh-h** [comment]
Go to organizational setting -> policies -> enable allow third-party access

![image](https://github.com/user-attachments/assets/3a20c6f0-b643-4be3-a687-316f0f77d4c6)
