### ISSUE TITLE
404 page not found when i create eShopOnWeb

### ISSUE THREAD

**Issue by Abdellahmaher** [microsoft/AzureDevOpsDemoGenerator#1055]
Hi,
I'm beginner in Azure Devops, i folow instructions to create eShopOnWeb Project, i create my projet in my organization from https://azuredevopsdemogenerator.azurewebsites.net/ link, i see this message "Congratulations! Your project is successfully provisioned" but when i clic Navigate to projet i have 404 Not Found Error!!
For information:
I have Azure Free Trial Subscription and i configured my paiement carte in Azure.
I enabled the creation of classic build and release Pipeline as indicated in the instruction Guide.

can you help me to undestand where is the problem?

Thanks,

**Comment by aksh-h** [comment]
#1059 
there is actually one simple solution Go to organizational setting -> policies -> enable allow third party access
![Screenshot 2024-08-19 at 1 04 30 PM](https://github.com/user-attachments/assets/b2f5215e-b527-49b7-a8bc-113c85d7dae2)
