### ISSUE TITLE
not able to navipagte to the project after creating

### ISSUE THREAD

**Issue by tarun121819** [microsoft/AzureDevOpsDemoGenerator#1059]
It shows project is successfully created in demo generator and when i try to navigate it shows 404:page not found and it is not even reflecting in my organization

**Comment by kosevolkan** [comment]
same problem for me

**Comment by tarun121819** [comment]
there is actually one simple solution  Go to organizational setting -> policies -> enable allow third party access
![Screenshot 2024-08-19 at 1 04 30 PM](https://github.com/user-attachments/assets/b2f5215e-b527-49b7-a8bc-113c85d7dae2)

**Comment by aksh-h** [comment]
I hope the suggestion worked.
