### ISSUE TITLE
Unable to Sign In

### ISSUE THREAD

**Issue by wscherphof** [microsoft/AzureDevOpsDemoGenerator#1060]
Tried many different accounts/networks/browsers/incognito windows; all with the same result:

1. Go to https://azuredevopsdemogenerator.azurewebsites.net/?enableextractor=true.
2. Click the Sign In button.
3. Sign in.
4. Land on https://azuredevopsdemogenerator.azurewebsites.net/Account/Verify.
5. Click the Sign In button.
6. Land on https://azuredevopsdemogenerator.azurewebsites.net/Account/Verify again, and so on.

When first signed into Azure DevOps, then to the Demo Generator, I get the same (step 4, 5, 6):
![afbeelding](https://github.com/user-attachments/assets/31f34714-54c8-4a47-898a-7116488f21e4)

The response headers of the "createproject" request there, are:
```
HTTP/1.1 302 Found
Content-Length: 132
Content-Type: text/html; charset=utf-8
Date: Wed, 28 Aug 2024 12:32:01 GMT
Server: Microsoft-IIS/10.0
Cache-Control: private
Location: /Account/Verify
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
```

**Comment by gowthamsaig** [comment]
Same for me ,
always landing to https://azuredevopsdemogenerator.azurewebsites.net/Account/Verify

**Comment by wscherphof** [comment]
At work I did manage to sign in, but it connected as a different account. I signed into devops as user1, then tried the demo generator, which failed, then signed into devops as user2, then tried the demo generator again, which succeeded, but with the user1 account...

**Comment by aksh-h** [comment]
@wscherphof there was some glitch on that day and it is mitigated. You can authenticate Demo Generator using your ADO credentials.
