### ISSUE TITLE
Project not created using template...

### ISSUE THREAD

**Issue by bvangeel** [microsoft/AzureDevOpsDemoGenerator#1063]
Dear,
Although running the template "Create a build pipeline with Azure Pipelines" ends with the notion that the project is created, it does not appear in the actual organisation.
<img width="425" alt="image" src="https://github.com/user-attachments/assets/f8eb969d-9e8c-4138-9c33-858ad56f025a">

When I navigate to the project I see the following:
<img width="658" alt="image" src="https://github.com/user-attachments/assets/47e6cc57-6c82-4435-8d65-93901853da8e">

This is blocking the exercise. What should I do?
Kind regards,
Bart

**Comment by desene95** [comment]
Solution can be found here https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1040#issuecomment-2191912961
