### ISSUE TITLE
404 code generated 

### ISSUE THREAD

**Issue by Scfraser26** [microsoft/AzureDevOpsDemoGenerator#1064]
Hi there.  I'm trying to complete a lab which depends on the use of a demo template - it's managing Teams and using the Delivery Report functionality.  I am getting a 404 when I try and navigate to the new project.  I get the project creation success message, but when I try and access it, it fails.  The new project is not there either when I go back into Azure Dev Ops.  Is there a missing step in the instructions, please?

**Comment by desene95** [comment]
Solution can be found here https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1040#issuecomment-2191912961
