### ISSUE TITLE
Issue while creating Project

### ISSUE THREAD

**Issue by Omkarrandive09** [microsoft/AzureDevOpsDemoGenerator#1066]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '333b11bd-d341-40d9-afcf-b32d5ce6f23b'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'NuGetInstaller_1'.) A task is missing. The pipeline references a task called '71a9a2d3-a98a-4caa-96ab-affca411ecda'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 1.*, job 'Phase_1', step 'VSBuild_2'.)

**Comment by aksh-h** [comment]
@Omkarrandive09 could you please point us to the template you tried to get this issue?
