### ISSUE TITLE
404 popped out while navigating to newly created project

### ISSUE THREAD

**Issue by Chilliyang23** [microsoft/AzureDevOpsDemoGenerator#1071]
Hi there, 

I have created a project on a newly created organization, and it showed that the project has been successfully provisioned. However, when I clicked the 'Navigate to project' button, it popped out 404. I have doubled checked url and it's correct.

Please kindly give any advices on what might went wrong, thanks.

**Comment by akshay-online** [comment]
Enable the following at your organization settings


![Third party authentication via oAuth](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/2071232/2cb3d1bb-48e1-4c9b-a2af-d7c85056750d)
