### ISSUE TITLE
Failure to Generate Project with Data

### ISSUE THREAD

**Issue by keshwanramlu** [microsoft/AzureDevOpsDemoGenerator#1074]
I have tried several times but not able to generate the Parts Unlimited Project with data. 
<img width="503" alt="image" src="https://github.com/user-attachments/assets/4a2883bb-db1c-46c6-9977-527964c0baca">
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/b121841b-9c5a-4130-b99b-fa7d3486a06a">

**Comment by aksh-h** [comment]
Go to organizational setting -> policies -> enable allow third-party access

![image](https://github.com/user-attachments/assets/3a20c6f0-b643-4be3-a687-316f0f77d4c6)

**Comment by derdelean** [comment]
This still does not work for me after allowing third-party access.
