### ISSUE TITLE
404 Error when selecting "Navigate to the Project"

### ISSUE THREAD

**Issue by heyrexayyy** [microsoft/AzureDevOpsDemoGenerator#1075]
After successfully creating the project using DevOps Demo Generator (eShop on Web), when I click on navigate to the project, a new tab opens that always runs in error.
![Image](https://github.com/user-attachments/assets/e63bea96-ed8d-4033-b521-838446589122)

**Comment by aksh-h** [comment]
@heyrexayyy please enable the third-party authentication via oauth option in your organization setting, then provision the project again. 

organizational setting -> policies -> enable allow third-party access

![image](https://github.com/user-attachments/assets/3a20c6f0-b643-4be3-a687-316f0f77d4c6)
