### ISSUE TITLE
Create a custom template from a single repo in a DevOps project ?

### ISSUE THREAD

**Issue by soonerfan** [microsoft/AzureDevOpsDemoGenerator#1076]
It would be nice to be able to generate a template from a single repo in a DevOps project.

Rather than creating another project (which we as developers don't have permission to do at our Organization) and duplicating an existing repo that already exists, it would be nice to be able to generate custom templates from a repo in a project that may contain numerous different repos

**Comment by aksh-h** [comment]
@soonerfan Thank you for your suggestion! Currently, Azure DevOps Demo Generator uses predefined templates to set up demo projects within your organization. If you don't have access to create a project, you can create your own organization and use the Demo Generator to provision a project. Additionally, we have a template builder feature that can export your project setup in JSON format for provisioning new projects. However, it doesn't support generating custom templates from existing repositories at this time.
