### ISSUE TITLE
404 - Page not found Looks like this page doesn’t exist or can’t be found. Make sure the project name and URL are correct.

### ISSUE THREAD

**Issue by Johnvo96** [microsoft/AzureDevOpsDemoGenerator#1085]
Congratulations! Your project is successfully provisioned. 

But Get error https://dev.azure.com/myorganise/eShopOnWeb.

404 - Page not found
Looks like this page doesn’t exist or can’t be found. Make sure the project name and URL are correct.
11/23/2024 5:16:18 PM (UTC)
29601c23-553b-4bc5-94af-e13bd0820678

**Comment by timrob0** [comment]
Hey, I had the same issue but this solved it.

[Issue #1075](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1075.)

[Solution](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/1075#issuecomment-2437073919
)

**Comment by akshay-online** [comment]
#1075
