### ISSUE TITLE
.NET Core 3.0?

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/AzureDevOpsDemoGenerator#164]
Would you be willing to take a PR to upgrade this repo to .NET Core 3?

**Comment by dmckinstry** [comment]
@isaac2004 - That's a great idea.  Let me discuss that with the team.  I believe the answer is a strong *yes* but want to make sure we're prepared for long term support.

**Comment by dmckinstry** [comment]
@isaac2004  - We'd be thrilled to accept a PR for a .NET Core upgrade. If you choose to help on it, we'll work with you when you get close. We'll need to make some deployment changes which will be hands-on from our side so we will be able to accept your fork into a separate branch until we can complete the config changes.
