### ISSUE TITLE
Scope not mentioned for the website

### ISSUE THREAD

**Issue by rathishrms** [microsoft/AzureDevOpsDemoGenerator#166]
In step 7 there is no scope mentioned for the website registration. Could you please help.

![image](https://user-images.githubusercontent.com/17181502/65759351-5c08a780-e138-11e9-8916-47667dd7dd4c.png)

**Comment by dmckinstry** [comment]
Yes - we'll put that on the backlog to fix the docs.  @aksh-h - Can you help?

**Comment by aksh-h** [comment]
Corrected required image paths. You can see which all the scopes are required to run the application locally.
