### ISSUE TITLE
API to create project is not working

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/AzureDevOpsDemoGenerator#170]
I tried to use the API to create a new project but got the following error:
the resource cannot be found

$resp = Invoke-WebRequest -Uri "https://demogenapi.azurewebsites.net/api/environment/create" -Method "POST" -ContentType application/json -Body $body
Provisioning project ...
Invoke-WebRequest : 

        The resource cannot be found.

**Comment by dmckinstry** [comment]
Thanks @stefanstranger - Akshay has the update staged and the PR should be merged soon!

**Comment by aksh-h** [comment]
Thanks @stefanstranger we have merged the changes
