### ISSUE TITLE
Support Task Groups

### ISSUE THREAD

**Issue by harrchen88** [microsoft/AzureDevOpsDemoGenerator#176]
Task groups are commonly used in pipelines for common and repeated groups of tasks.  Current DemoGenerator doesn't support Task Groups.  It will be great to add the support.

**Comment by dmckinstry** [comment]
@aksh-h - The API appears to support this. Let's discuss in our next 1:1.  The same is true for the Variable-group request.

**Comment by dmckinstry** [comment]
Hi @harrchen88 - I'm going to close this since we haven't had anyone else pile on.
