### ISSUE TITLE
Support for Azure DevOps Server?

### ISSUE THREAD

**Issue by Cj-Scott** [microsoft/AzureDevOpsDemoGenerator#177]
Are there any plans to add support for On-Premises environments of Azure DevOps Server?

**Comment by aksh-h** [comment]
@Cj-Scott Yes, you can find it on [TFSDemoGenerator Repo](https://github.com/microsoft/tfsdemogenerator). You need to host it in your IIS.

**Comment by persalmi** [comment]
Is this really correct that the same features are in the TFS DemoGenerator project? Can you extract templates with it?

**Comment by aksh-h** [comment]
No, we have not extended all the features. It has some limited support with azure devops server.

**Comment by persalmi** [comment]
Would it be a good thing to make this tool work for AzDO Server? Or do you think it is way too much work compared to continue work to implement the missing features in the TFSDemoGenerator?

**Comment by aksh-h** [comment]
Shared the repository for TFS demo generator which has limited support and features. We no longer supporting the TFS demo generator. The same source code (with minor changes) might work for later versions of Azure DevOps Server (2020 and 2022).
