### ISSUE TITLE
Github import and forking not working

### ISSUE THREAD

**Issue by rorpage** [microsoft/AzureDevOpsDemoGenerator#184]
It's 100% possible I'm doing something wrong, but I created a template project and set Github as the source code which the Generator recognized as Github. I selected to fork it but when I navigate to Azure DevOps I don't see any source code pulled into the repo, and it looks like nothing is pointing at it.

You can see my sample template [here](https://github.com/egineering-llc/Concierge_AzureDevOpsImport) and the import file [here](https://github.com/egineering-llc/Concierge_AzureDevOpsImport/blob/master/ImportSourceCode/Concierge_AzureFunctionCSharp.json).

Thanks!
Robbie

**Comment by dmckinstry** [comment]
Thanks @rorpage - @aksh-h and I will look into it tomorrow.  Thank you for reporting!

**Comment by aksh-h** [comment]
@rorpage whenever user uploads a template, irrespective of where is the repository, GitHub fork option will be enabled. If the source code is present in GitHub and pipelines are pointing to it, then user can opt for this option. The new pipelines would be pointed to the forked repository. As an example you can try [SmartHotel360](https://azuredevopsdemogenerator.azurewebsites.net/?name=SmartHotel360) template.

**Comment by rorpage** [comment]
I realized after opening this issue that I had removed the source code I had linked above. My apologies.

I am going to close this issue as I switched back to hosting the code in a public Azure DevOps repo.

Many thanks anyways!
