### ISSUE TITLE
New Project Creation Fails 

### ISSUE THREAD

**Issue by jyothivel** [microsoft/AzureDevOpsDemoGenerator#191]
The template has a secure file that gets loaded along with the project. I have added the User role permission in the security tab from the Pipeline library. I still fails with the error given below. 'Limit Job authorization scope to current job' is disabled already but not sure where to set the build job authorization to 'Project Collection'
Here is the Diagnostic Log information:
_Error while creating build definition: To get sources from a different team project, on the Options tab you must set the build job authorization scope to ‘Project collection’ and ensure that the 'Limit job authorization scope to current project' pipeline setting is disabled. Error while creating release definition: User does not have permission to link the secure file 'f1ded125-faff-4760-93fe-e0abe21ab257' to the release pipeline. Make sure the user has 'User Role' on the secure file and retry the operation._

**Comment by jyothivel** [comment]
![AzureDevopsDemoGeneratorError](https://user-images.githubusercontent.com/30132769/68401899-83479100-0148-11ea-93ce-d567b5821ec6.png)

**Comment by aksh-h** [comment]
@jyothivel We haven’t heard of any similar issues recently. We suspect this is because of the cross project repository reference. If this is the case, please keep the repo in the same project from which you have been trying to generate the Template. Let us know your updates.

**Comment by aksh-h** [comment]
Handling this thread offline

**Comment by aksh-h** [comment]
Looks organization related issue. Hence closing
