### ISSUE TITLE
Document how to review and revoke access granted to DemoGenerator

### ISSUE THREAD

**Issue by dpurge** [microsoft/AzureDevOpsDemoGenerator#197]
This is a cool application :-)

This app is used to set up lab environments during MS trainings.  If there is a problem with using a promo code somone may be pressed to solve it by granting access to some other subscription that belongs to that person just to be able to do the lab exercise and may wish to revoke the granted access after the training is over.

You are missing documentation explaining where to review the permissions granted to the app and how to revoke them.

**Comment by aksh-h** [comment]
@dpurge you can find all applications that you have authorized here. https://dev.azure.com/{ORGANIZATION}/_usersSettings/authorizations 

You can revoke by clicking on delete icon there.

**Comment by aksh-h** [comment]
@dpurge  if you need any more info you can reopen this issue.
