### ISSUE TITLE
Unknown user accounts included in ProjectSetttings.json when exporting

### ISSUE THREAD

**Issue by jkewley** [microsoft/AzureDevOpsDemoGenerator#200]
Wondering why exporting through the web site generates a ProjectSettings.json file that includes several external users:

```
{
  "type": "<process name>",
  "id": "b2421a69-5335-4628-abee-a06642c0339a",
  "users": [ "ckelly109@outlook.com", "craig109@outlook.com", "nmunger109@outlook.com", "lsteel109@outlook.com" ],
  "userAssignment": "Any"
}
```

**Comment by aksh-h** [comment]
Application uses this file to assign users to work item. If keep the work item unassigned, you can remove the key userAssignment.

**Comment by jkewley** [comment]
What I mean is that you guys have those four users hard coded into the generated template. If someone is exporting from a private AZDO instance they'll see these four accounts which have nothing to do with their organization. If they're meant to be placeholder accounts you might use email addresses like someone@somedomain.com.

**Comment by aksh-h** [comment]
Thank you for your inputs, we will update the setting
