### ISSUE TITLE
Deployment error pertaining to deprecated Kubernetes API version in mhc.yaml 

### ISSUE THREAD

**Issue by noemi616** [microsoft/AzureDevOpsDemoGenerator#201]
I am running the [Azure DevOps labs on deploying MHC in AKS ](https://azuredevopslabs.com/labs/vstsextend/kubernetes/)and ran into build issue when running the release pipeline.  The error shows up in the "Create Deployments & Services in AKS" task as 

> "unable to recognize "/home/vsts/work/r1/a/MyHealth.AKS.build/deploy/mhc-aks.yaml": no matches for kind "Deployment" in version "apps/v1beta1""

![image](https://user-images.githubusercontent.com/16081468/73229228-1f73b800-41cd-11ea-95af-e08885c50aea.png)

, which I believe pertains to [Kubernetes API "apps/v1beta1" being deprecated since 1.16](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).  I have updated mhc.yaml to use the latest version (apps/v1) and have tried running this against Kubernetes cluster deployments running in 1.15.7 (default) as well as 1.17.0 (preview).

**Comment by aksh-h** [comment]
@noemi616 thank you, we will look into this.

**Comment by sriramdasbalaji** [comment]
Hi @noemi616 ,

We have fixed the api version issue in our template. You can recreate the project from demo generator to get the latest source code or replace the content of mhc-aks.yaml file from https://raw.githubusercontent.com/microsoft/azuredevopslabs/master/labs/vstsextend/kubernetes/mhc-aks.yaml

Thanks

**Comment by aksh-h** [comment]
Fixed, hence closing the issue

**Comment by squanchd** [comment]
I'm still experiencing this issue.
