### ISSUE TITLE
Will there be a support to work with GitHub and GitHub enterprise instead of Azure DevOps?

### ISSUE THREAD

**Issue by harrchen88** [microsoft/AzureDevOpsDemoGenerator#207]
If I want to duplicate repo, actions, workflow, projects etc. in GitHub or GitHub enterprise, will I be able to use this tool to do that?

**Comment by dmckinstry** [comment]
Hi @harrchen  - Let's start an email discussion on this.  It already supports the repos which means much of the configurations and Actions are  already supported.  Projects and Issues and a few other things would still need work.  Ping me via email with your requirements.  Thanks!
