### ISSUE TITLE
Deploy Template from Azure DevOps

### ISSUE THREAD

**Issue by jeffpatton1971** [microsoft/AzureDevOpsDemoGenerator#208]
So after a quick run through of the extract doc it appears that I need to deploy my template by hitting your Azure Webapp. Is it possible to not do this? I ask because at some point this project may die and the app may get removed, and I don't want to be in the position of leveraging a tool that we use to generate projects for customers when it goes away.

Can we get some more detailed documentation about how a deployment actually progresses?

**Comment by aksh-h** [comment]
there is no other tool which does the same operations. You can build your own template as a blueprint to provision new project and use it with this system only. 

There is another option for you, as the project is open-source, you can deploy a copy of this app in your IIS and use.
