### ISSUE TITLE
Selenium Template throws error on Release Pipeline import

### ISSUE THREAD

**Issue by omarv74** [microsoft/AzureDevOpsDemoGenerator#212]
CredScan.
Error while creating release definition: A credential or other secret was detected in one or more plaintext variables. 
Remove all secrets or convert all variable types to secure. 
...
Variables (and their corresponding stage) that need to be secured: DefaultConnectionString (Release)

**Comment by omarv74** [comment]
Note: The edits on this PR have been tested according to the steps in the corresponding AzureDevOpsLabs.com lab.

**Comment by aksh-h** [comment]
fixed and released
