### ISSUE TITLE
PartsUnlimited demo Test Suite is empty

### ISSUE THREAD

**Issue by berberich** [microsoft/AzureDevOpsDemoGenerator#214]
Previously when using the PartsUnlimited demo generator it created a Test Suite with numerous test cases, as seen in [this project](https://dev.azure.com/berbs/PartsUnlimited%20(Previous)/_testPlans/execute?planId=3268&suiteId=3270).

When running the demo generator today in two different Azure DevOps accounts, it creates an empty Test Suite, as seen in [this project](https://dev.azure.com/berbs/PartsUnlimited%20(Scrum)/_testPlans/define?planId=3445&suiteId=3446).

The generator did not show any warnings or errors.

@dmckinstry

**Comment by dmckinstry** [comment]
@aksh-h - Can you confirm the symptoms and help triage this?

**Comment by aksh-h** [comment]
Yes @dmckinstry, looks like there is some issue with creating work items in the recent changes implemented. We are working on it.

**Comment by aksh-h** [comment]
fixed and released
