### ISSUE TITLE
Can not build a custom template

### ISSUE THREAD

**Issue by Grahamworth** [microsoft/AzureDevOpsDemoGenerator#229]
On the build template page there seems to be no option to do / download from an existing project anymore, only an analyse that returns no results.  spotted this keep appearing in the the console: ajax.ts:157 POST https://dc.services.visualstudio.com/v2/track 400 (Invalid instrumentation key)

**Comment by aksh-h** [comment]
@Grahamworth we have fixed issue. Try again to generate template in preview [environment](http://demogen-code.azurewebsites.net/). Let us know your feedback.
