### ISSUE TITLE
Cannot create Parts Unlimited from a lab

### ISSUE THREAD

**Issue by oscholz** [microsoft/AzureDevOpsDemoGenerator#232]
https://azuredevopslabs.com/labs/azuredevops/pullrequests/

I try to run [this lab](https://azuredevopslabs.com/labs/azuredevops/prereq/)
And I get an error...

**Comment by aksh-h** [comment]
@oscholz this looks like an intermittent issue. Could you please retry and let us know?

**Comment by aksh-h** [comment]
@oscholz we are closing the issue. If this still persists you can reopen the same
