### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by prasyada** [microsoft/AzureDevOpsDemoGenerator#236]
Unable to create project. It stops in between and nothing happens after wards. It just sits there.

**Comment by aksh-h** [comment]
@prasyada this looks like an intermittent issue, could you please let us know which template you tried?

**Comment by prasyada** [comment]
I tired terraform template

**Comment by aksh-h** [comment]
@prasyada could you please retry and check [here](https://demogen-code.azurewebsites.net/)

**Comment by prasyada** [comment]
It worked this time. thanks.

**Comment by aksh-h** [comment]
@prasyada thank you.
