### ISSUE TITLE
Issue creating project with template "Scan code for vulnerabilities in Azure Pipelines"

### ISSUE THREAD

**Issue by kaushikmaji** [microsoft/AzureDevOpsDemoGenerator#238]
Hi,

While creating a project using template "Scan code for vulnerabilities in Azure Pipelines", I am not able to do so and I get errors in screenshots below:

![image](https://user-images.githubusercontent.com/9915281/79745965-8060e700-8309-11ea-95ab-2887b447c123.png)

![image](https://user-images.githubusercontent.com/9915281/79747322-bc954700-830b-11ea-87a4-f59134590c05.png)

Please assist.

Thanks and Regards, 
Kaushik

**Comment by aksh-h** [comment]
Hello @kaushikmaji 

As error clearly says the project is already exist in you azure devops organization, try selecting a different org and try again.

**Comment by kaushikmaji** [comment]
Really Sorry Akshay!! I have now uploaded the correct error in the original issue report above. Kindly check.

**Comment by aksh-h** [comment]
does it happening every time or to every organization you tried?

**Comment by kaushikmaji** [comment]
No this is the only organization, where I create my projects. I am doing the self learning course module for Az-400 certification i.e. "Build applications with Azure DevOps". It worked for templates in AzureDevOps learning modules earlier, but I am not able to create project with mentioned template in this Issue instance and also with template "Run quality tests in your build pipeline using Azure Pipelines".

**Comment by aksh-h** [comment]
We will inspect this issue. In the meantime could you please check the necessary permissions to create the endpoints ?
Here you have been authorizing the GitHub to create end point under your projects, so that pipeline can talk to remote repository.

**Comment by kaushikmaji** [comment]
Hi Akshay, Thanks!!
I have provided necessary permissions as demanded, when I clicked, the Authorize button on createproject page. Otherwise, did not explicitly authorized github to create endpoint. 

regards,
Kaushik

**Comment by aksh-h** [comment]
> Hi Akshay, Thanks!!
> I have provided necessary permissions as demanded, when I clicked, the Authorize button on createproject page. Otherwise, did not explicitly authorized github to create endpoint.
> 
> regards,
> Kaushik

After authorizing are you still facing the issue?

**Comment by aksh-h** [comment]
> We will inspect this issue. In the meantime could you please check the necessary permissions to create the endpoints ?
> Here you have been authorizing the GitHub to create end point under your projects, so that pipeline can talk to remote repository.

Please check the necessary permission in your azure devops org

**Comment by kaushikmaji** [comment]
![image](https://user-images.githubusercontent.com/9915281/80126161-fb88fe00-8592-11ea-9be8-5f192856bbe3.png)

On Github Side, Azure App already has the requested permission and I am not able to see from where I would be able to give it permissions for managing webhooks in my GitHub repo. Please suggest.

**Comment by kaushikmaji** [comment]
![image](https://user-images.githubusercontent.com/9915281/80126609-9eda1300-8593-11ea-9323-737cdf1d91e4.png)

Demo app has full access

**Comment by kaushikmaji** [comment]
Now I tried to revoke access and then tried creating the project. Even then, its giving the same error. Quoting again below:

_"Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository. "_

**Comment by aksh-h** [comment]
you might need access to create service connections your Azure DevOps Organizations.
Meantime, you can try other tempaltes and see if you area still facing the same issue
