### ISSUE TITLE
Add and option to Azure DevOps Generator to build a new devops project template without any assigned users

### ISSUE THREAD

**Issue by vandyrodrigues** [microsoft/AzureDevOpsDemoGenerator#239]
Currently when creating a new azure devops template the ProjectSettings.json file is prepopulated with a few dummy users, ex: kelly109@outlook.com", "craig109@outlook.com", "nmunger109@outlook.com"

To prevent this behavior I have to unzip the file, remove the users, zip again, then upload to GitHub. 
Ask: Add and option to Azure DevOps Generator to build a new devops project template without any assigned users

ProjectSettings.json
----------------------------
{
  "type": "Agile",
  "id": "adcc42ab-9882-485e-a3ed-7678f01f66bc",
  "users": [ "ckelly109@outlook.com", "craig109@outlook.com", "nmunger109@outlook.com", "lsteel109@outlook.com" ],
  "userAssignment": "Any"
}
-----------------------------

**Comment by aksh-h** [comment]
@vandyrodrigues thank for brining it to our notice, we will do needful.

**Comment by aksh-h** [comment]
Since this was requested by most of the users, we have decided to not to bring any users to user generated template.
