### ISSUE TITLE
Add a new tab "Microsoft Community"

### ISSUE THREAD

**Issue by vandyrodrigues** [microsoft/AzureDevOpsDemoGenerator#241]
Ask: Add a Microsoft Community tab or a similar tab when a user "choose a template" option
https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/About-Azure-DevOps-Demo-Generator/images/templateselection.png

We are currently working on an initiative to leverage on the DevOps generator to accelerate customer guidance to adopt and deploy azure services. Add the tab point to current repo https://github.com/microsoft/azuredevopsgenerator will help to scale the solution.

**Comment by aksh-h** [comment]
Adding a tab means  would you like to keep the tempalte in **azure devops demo generator** repository and link back to the docs you have in your repo.

**Comment by aksh-h** [comment]
Could you please confirm the extensions that are required for the project/template? You can find the extension in **Extensions.json** file

**Comment by aksh-h** [comment]
Here you can find the quick link to the template, and it is still under our test site
[Azure Sentinel](https://azuredevopsdemogenerator-mslearn.azurewebsites.net/?name=AzureSentinel) and [Azure NIST 800-171 Rev2](https://azuredevopsdemogenerator-mslearn.azurewebsites.net/?name=AzureNIST)

**Comment by aksh-h** [comment]
We need additional information for your templates

- Icons for the template - .png or .jpg
- Template Details - Please provide below info

        `{
          "Name": "TEMPLATE NAME", // Will be displayed
          "ShortName": "SHORT NAME", // Short name for the template - for quick links
          "Description": "DESCRIPTION OF TEMPLATE- NOT MORE THAN 50 WORDS",
        }`

**Comment by aksh-h** [comment]
Please provide the above details

**Comment by vandyrodrigues** [comment]
> Could you please confirm the extensions that are required for the project/template? You can find the extension in **Extensions.json** file

**Comment by vandyrodrigues** [comment]
> We need additional information for your templates
> 
> * Icons for the template - .png or .jpg
> * Template Details - Please provide below info
>   ```
>     `{
>       "Name": "TEMPLATE NAME", // Will be displayed
>       "ShortName": "SHORT NAME", // Short name for the template - for quick links
>       "Description": "DESCRIPTION OF TEMPLATE- NOT MORE THAN 50 WORDS",
>     }`
>   ```

  `{
    "Name": "Azure Sentinel DevOps", // Will be displayed
    "ShortName": "azuresentinel", // Short name for the template - for quick links
    "Description": "The objective is helping customers to quickly deploy Azure Sentinel following the best practices using Azure DevOps board with agile practices.",
  }`

![azuresentinel](https://user-images.githubusercontent.com/18331100/80758256-0562b200-8afb-11ea-9303-bab599fc8fab.jpg)

  `{
    "Name": "NIST 800-171", // Will be displayed
    "ShortName": "nist800171rev2", // Short name for the template - for quick links
    "Description": "By importing the NIST 800-171 DevOps template, you will be able to complete actionable Work Items that correspond to customer responsibilities in order to implement compliance..",
  }`
![nist](https://user-images.githubusercontent.com/18331100/80757649-152dc680-8afa-11ea-974c-68ba07931213.png)

**Comment by aksh-h** [comment]
Thank you. Regarding extensions, these were present in the organization from where you generated the template. If all these extensions are really required for the template, we can keep, else i'll discard those
