### ISSUE TITLE
Preview version appears to be using the wrong templates

### ISSUE THREAD

**Issue by tristanwilkinson** [microsoft/AzureDevOpsDemoGenerator#249]
I'm trying to use the demo generator for the learning module "Implement a code workflow in your build pipeline by using Git and GitHub" ( https://docs.microsoft.com/en-gb/learn/modules/implement-code-workflow/3-set-up-environment ), following the instructions in unit.

The first time, rather than generating the matching demo, it generated a demo which dragged SmartHotel360 and PublicWeb into Azure Repos. (The learning module in question shouldn't be putting anything into Azure Repos, it uses GitHub.) In addition to that, the work items & boards expected to be added for the unit weren't added.

I deleted the generated demo project, and tried again with a slightly different project name, this time ensuring that I specifically selected the relevant template (also named "Implement a code workflow in your build pipeline using Git and GitHub") rather than relying on it being automatically selected. The demo generation ran with the wrong template again though, this time importing AKS into Azure Repos. It also failed with an error:

> Error while Setting Epic Settings: VS402488: One or more of the backlog levels specified in the backlog visibilities is not valid. Error while updating board column TF401501: The board does not exist.

As the site says it'll revert away from the preview version in a few hours I'll just wait until tomorrow before trying again.

**Comment by aksh-h** [comment]
Please clear the browser catch before you use it next time or use incognito window

**Comment by aksh-h** [comment]
we couldn't reproduce the issue. We recommend you to try again with any templates. Please clear your browser cache and refresh the browser tab with Ctrl+F5.

**Comment by tristanwilkinson** [comment]
To update on my experience since, initially I was using the generator in an incognito window as requested and didn't have any trouble that way. Following the most recent comment I swapped back to a regular window and haven't had any trouble that way either.

However, I've never been given the preview version of the site since in either scenario, so the problems not happening may have been expected.
