### ISSUE TITLE
generating wiki template

### ISSUE THREAD

**Issue by Kumar3010** [microsoft/AzureDevOpsDemoGenerator#254]
Hi,

I want to generate a custom project template with 1. wiki pages 2. build and release defs.
the generator generates teh build and release but not wiki. how do i do that.

thanks,
Kumar

**Comment by aksh-h** [comment]
Hi there,

Generating wiki is not supported in Azure DevOps Demo Generator. That needs to be handled manually.
As a suggestion, keep the wiki content in repository, so that you can link it directly or do any modification in Azure Repos.
