### ISSUE TITLE
Project Template Not Found

### ISSUE THREAD

**Issue by cramos0619** [microsoft/AzureDevOpsDemoGenerator#255]
The AzureDevOpsDemoGenerator failed with to create the project, Project Template not found was all that was in the log file.  I was using the SFPowerScripts sample pipeline zipe:  https://github.com/azlamsalam/sfpowerscripts/blob/release/SamplePipelines/sfpowerscripts-sample-pipelines.zip 

and when trying to use the ZIP recommended in the online documentation (https://github.com/Accenture/sfpowerscripts/releases/download/13.8000.7/sfpowerscripts_sample_pipelines.zip) I received an error "Unable to download file, please check the provided URL"  Do you know anyway to work around this issue?

**Comment by aksh-h** [comment]
Thank you for reaching us. We are looking into the issue

**Comment by aksh-h** [comment]
Hi @cramos0619, tool can only read/download the files from repository not form release section. I believe this worked for your first link what you shared.

**Comment by aksh-h** [comment]
@cramos0619 we recommend you to use the template which the generated from the Template Builder, if you are keeping the template in GitHub public repo, make sure that you are not keeping it under releases.

Closing this thread.
