### ISSUE TITLE
Limitation section and export import bugs

### ISSUE THREAD

**Issue by gsuttie** [microsoft/AzureDevOpsDemoGenerator#257]
The create custom templates doc points to a limitations section but the URL points to https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs

What are the limitations as I want to create custom templates where I set up a base project with things like artifacts and test plans taken out but when I explore and remimport into a new project this doesnt work.

**Comment by dmckinstry** [comment]
Thanks Gregor.  @aksh-h - can you help with the limitations docs?  I thought we had this already but perhaps it's just a broken link?

**Comment by aksh-h** [comment]
added limitation doc [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)

hence closing the issue.
