### ISSUE TITLE
Cannot get past Sign In screen - I get circular Sign in - Pick an account - Sign in - Pick an account...

### ISSUE THREAD

**Issue by kayceejay** [microsoft/AzureDevOpsDemoGenerator#261]
I am trying to use a template and I get dumped into a circular sign in whirlpool.
Page says "Sign in" -> So I sign in
Page says "Sign in" -> So I sign in 
Page says "Sign in" -> So I sign in
Page says "Sign in" -> So I sign in
Page says "Sign in" -> So I sign in

Again and again and again and again and again...

1) Start on page "Exercise - Set up your environment"
https://docs.microsoft.com/en-us/learn/modules/manage-delivery-plans/4-set-up-environment

2) Click on "Run a template that sets up your Azure DevOps organization."
https://azuredevopsdemogenerator.azurewebsites.net/?name=deliveryplans

3) I get a screen "Azure DevOps Demo Generator" "Sign in" in or "Get started for free"
https://azuredevopsdemogenerator.azurewebsites.net/?name=deliveryplans

4) I click on "Sign in" 

5)
I briefly see "loading identity providers"
I see "Pick an account" 
I click on my account

I briefly see "loading identity providers"
I see "Pick an account" 
I click on my account

I briefly see "loading identity providers"
I see "Pick an account" 
I click on my account

AND ON AND ON AND ON AND ON...

I have tried FOUR different browsers

I have tried TWO different computers.

I have tried TWO accounts

I tried signing out FOUR times like this: "close your browser windows and then open a new browser and navigate to https://aka.ms/vssignout. Close this browser, open a new browser and navigate to https://aex.dev.azure.com/me"

**Comment by aksh-h** [comment]
@kayceejay Thank you for reaching us. We find no similar issue, and we do not reproduce it, if you are still facing the same please let us know.

**Comment by aksh-h** [comment]
Please try to sign in to your organization before you login to Azure DevOps Demo Generator. If you face the same, please reach out to us.
Thanks,

**Comment by aksh-h** [comment]
We are closing issue, if you encounter the same, you can always reopen the issue. Thanks.
