### ISSUE TITLE
PartsUnlimited Empty repos

### ISSUE THREAD

**Issue by devops-app** [microsoft/AzureDevOpsDemoGenerator#263]
Starting today onward, the PartsUnlimited DevOps generator provide an empty repos. This has happen to me and my participants. I am sure it can be reproduce.
![Capture](https://user-images.githubusercontent.com/65710369/82612978-d1107c00-9bf6-11ea-8c40-6946ec18fd35.PNG)

**Comment by omarv74** [comment]
Confirming this issue. I just reproduced it a few times. I tried templates from the General Section and from the DevOpsLabs section and only the ones from General seem to have this problem. I use different templates fairly often. I will try to look into this over the weekend and contribute a fix.

**Comment by aksh-h** [comment]
Hi,
Could you please retry?

**Comment by devops-app** [comment]
Dear All,

I have tested and the generator is working fine now. Thank you for the
prompt response.
Have a nice day.

**Comment by aksh-h** [comment]
@devops-app thank you for your confirmation. We are closing the issue.
Thanks.
