### ISSUE TITLE
Error while importing Octopus DevOps Project

### ISSUE THREAD

**Issue by injeetender** [microsoft/AzureDevOpsDemoGenerator#264]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '179fac12-2402-486e-80cf-5a6a8571f7c0'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Phase_1', step 'OctopusPack1'.)

**Comment by aksh-h** [comment]
Hello @injeetender, I believe this is from octopus template, which requires octopus extension to be installed prior to the project creation. If this is  installed at the time of project creation it may take little time to install, enable and available for the use of build definition.
We would recommend you to retry and let us know if the issue persists.

**Comment by aksh-h** [comment]
Are you still facing the same issue? Let us know your updates,

**Comment by aksh-h** [comment]
You can always reopen the issue if you face the same.

**Comment by injeetender** [comment]
Hello @aksh-h, Yes this issue is faced while importing Octopus template. the octopus extension is already installed and even after that tried 4 to 5 times, but the same issue is faced while importing the template.

Also, I am not able to re-open this issue.

**Comment by aksh-h** [comment]
@injeetender  

This [link](https://docs.microsoft.com/en-us/azure/devops/demo-gen/use-demo-generator-v2?view=azure-devops#common-issues-and-workarounds) might help you.

**Comment by injeetender** [comment]
@aksh-h 

The link shared speaks about permission level in DevOps Organisation. I have complete Project admin access rights for the organisation, in which I am trying to import the template.
