### ISSUE TITLE
Error msg when creating a project...

### ISSUE THREAD

**Issue by pfrimpong** [microsoft/AzureDevOpsDemoGenerator#266]
I get this error msg:
-------------
'We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs here and we will try to help you.

Click on View Diagnostics button to share logs with us
--------------------------------------
When creating a project under the Space Game - web - Agent.

**Comment by aksh-h** [comment]
Hi @pfrimpong,

Thank you for reaching us. Next time if you encounter the same issue, please click on View Diagnostic logs button to see the logs. You can share the same logs with us for more information.
Thanks
