### ISSUE TITLE
Community T1 Plan 404

### ISSUE THREAD

**Issue by shooker** [microsoft/AzureDevOpsDemoGenerator#268]
When I visit [this page](https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject) coming from the first link on [this page](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/template), the template "Community T1" is selected. The template is not found in GitHub. To successfully deploy the demo, I had to use [this link](https://docs.microsoft.com/en-us/azure/devops/demo-gen/?view=azure-devops).

**Comment by aksh-h** [comment]
Hi @shooker 
Thank you for pointing this. Could you please retry from the same [link](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/template)?

Let us know your updates.
Thanks.

**Comment by aksh-h** [comment]
Answered. Hence closing the issue.
