### ISSUE TITLE
Error while importing Octopus DevOps Project : Earlier Issue - #264

### ISSUE THREAD

**Issue by injeetender** [microsoft/AzureDevOpsDemoGenerator#269]
Hello the below mentioned issue is still faced while importing Octopus template. the octopus extension is already installed and even after that tried 4 to 5 times, but the same issue is faced while importing the template. 

Also, I am not able to re-open this issue, hence created this new issue. Old Issue reference: #264 

Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '179fac12-2402-486e-80cf-5a6a8571f7c0'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Phase_1', step 'OctopusPack1'.)

**Comment by aksh-h** [comment]
Hi @injeetender Thank you for reaching us, you may find the similar issue and response [here](https://docs.microsoft.com/en-us/azure/devops/demo-gen/use-demo-generator-v2?toc=%2Fazure%2Fdevops%2Fdemo-gen%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fdemo-gen%2Fbreadcrumb%2Ftoc.json&view=azure-devops#common-issues-and-workarounds)

This is related to extension availability or the version mismatch with the build task. You can try re-running the generator.
Thanks
