### ISSUE TITLE
We ran into some issues and we are sorry about that!

### ISSUE THREAD

**Issue by stephaneclavel** [microsoft/AzureDevOpsDemoGenerator#271]
Faced the below error message when creating project based on TemplateAsCode template

Error while creating release definition: Tasks with versions 'Install Terraform 0.12.18:0.*, Terraform : init:0.*, Terraform : plan:0.*, Terraform : apply -auto-approve:0.*' are not valid for deploy job 'Deploy Terraform Config' in stage Build.

**Comment by stephaneclavel** [comment]
Actually the project is successfully provisioned

**Comment by aksh-h** [comment]
Hi @stephaneclavel 
Terraform template required the [extension](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks) which should be installed prior to the creating project. If you install this at the time of project provision or if the extension version doesn't match the required version, you may encounter this issue. We recommend you to try again with installing/enabling the Terraform extension.

Thanks

**Comment by stephaneclavel** [comment]
Thanks. As I didn't got this warning https://csprodstorage001.blob.core.windows.net/blog/CreateProject.png I incorrectly assumed everything was ok. 

I re-imported the template today, still no warning, and release pipeline is correctly imported.

**Comment by aksh-h** [comment]
Waring will be shown when you select your organization. Hope you are able to work with the project. Thank you. We are closing the issue.
