### ISSUE TITLE
Exporting areas

### ISSUE THREAD

**Issue by tasb** [microsoft/AzureDevOpsDemoGenerator#273]
I have this config of areas on my project:

![image](https://user-images.githubusercontent.com/415105/83364678-d5792980-a39a-11ea-85b6-1694e9bc2872.png)

I make the export and when created the new project the areas definition are like this:

![image](https://user-images.githubusercontent.com/415105/83364682-e7f36300-a39a-11ea-9c6f-4fcfa6ce22b8.png)

**Comment by aksh-h** [comment]
Hi @tasb Thank you for reaching us, please refer Azure DevOps Demo Generator limitation docs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)
