### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by jamesjej** [microsoft/AzureDevOpsDemoGenerator#276]
I am getting the following:

Could not load your organizations. Please check if the logged in Id contains the Azure DevOps Organizations or change the directory in profile page and try again. 

How do i correct this?

**Comment by aksh-h** [comment]
Hi @jamesjej,

The directory in which you might have logged in is't listing the Azure DevOps organizations. You can visit profile section of azure devops account to change the directory and login again.
