### ISSUE TITLE
azure sentinel template

### ISSUE THREAD

**Issue by vandyrodrigues** [microsoft/AzureDevOpsDemoGenerator#277]
[Azure sentinel template](https://github.com/microsoft/AzureDevOpsDemoGenerator/tree/master/src/VstsDemoBuilder/Templates/AzureSentinel/WorkItems) has multiple stories and features, however when generating a new project it creates only three work items.

![azuresentinel jpg](https://user-images.githubusercontent.com/18331100/84077349-d0206e00-a99c-11ea-8aaa-caae12f5a4b8.png)

**Comment by aksh-h** [comment]
Thanks @vandyrodrigues, we are investigating the issue.
