### ISSUE TITLE
False report of success

### ISSUE THREAD

**Issue by AlanMcBee** [microsoft/AzureDevOpsDemoGenerator#278]
I tried using the generator to make number of projects, and I've done it many times over the past 2 years. Today, no matter which general template I pick, it spins for only a couple of seconds (WAY faster than it normally is), then reports that the project is created.

The project is not created. Clicking the link takes me to a 404, and checking projects and audit history from the organization reveals no attempt by the generator to create the project.

![image](https://user-images.githubusercontent.com/37203424/84079859-16230500-a990-11ea-8a32-b2f284c1e462.png)

**Comment by aksh-h** [comment]
Hi @AlanMcBee, Thank you for reaching us. This could be an intermittent issue. Could you please re-sign in and retry ?

Let us know if the issue persists.
