### ISSUE TITLE
Tested Azure Sentinel template staging site

### ISSUE THREAD

**Issue by vandyrodrigues** [microsoft/AzureDevOpsDemoGenerator#282]
I have tested the Azure Sentinel Template in the staging site, it's ready to production.

**Comment by CrisRomeo** [comment]
+1 - its ready for prod

**Comment by aksh-h** [comment]
Thanks, we have moved it to production. Could you please try it once in [prod](http://azuredevopsdemogenerator.azurewebsites.net/?name=azuresentinel) ?

**Comment by vandyrodrigues** [comment]
It's working but the order seems incorrect., That should be the right order. 
![azsentinel](https://user-images.githubusercontent.com/18331100/84681117-4cfd9b80-aef9-11ea-9a44-5a65c398b490.jpg)

**Comment by aksh-h** [comment]
I'm not sure with the ordering, i'll look into this.
