### ISSUE TITLE
Pipeline Releases not working after importing the project

### ISSUE THREAD

**Issue by amitsethitx** [microsoft/AzureDevOpsDemoGenerator#284]
Hello - I have imported the project and created another project using DevOpsGenerator.  Now after the import pipeline releases are not working . 
The releases are erring out with following error messages.

C:\Modules\az_3.8.0\Az.Accounts\1.8.1\Az.Accounts.psd1 -Global
2020-06-15T19:01:24.4352802Z ##[command]Clear-AzContext -Scope Process
2020-06-15T19:01:25.8039846Z ##[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
2020-06-15T19:01:26.2707060Z ##[command]Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
**2020-06-15T19:01:26.8165247Z ##[error]AADSTS7000215: Invalid client secret is provided.
Trace ID: XXXXXXXXXXXX**
Correlation ID: XXXXXXXXXXXXXXX
Timestamp: 2020-06-15 19:01:26Z
2020-06-15T19:01:26.9573204Z ##[error]There was an error with the service principal used for the deployment.
2020-06-15T19:01:27.2158091Z ##[error]PowerShell exited with code '1'. 

Thanks'
Regards
Amit Sethi

**Comment by aksh-h** [comment]
Hello @amitsethitx, Thank you for reaching us. 
Could you please share more info - which template you used from Demo Generator ? or are you trying to use any of your private template.

By seeing the error log,
the pipeline definitions would not be created/linked with service principal details, the user has to create service connections and use it for deployments. It is recommended to verify the service connections before you run the pipeline. Please find limitation [docs ](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md) if this is helpful.

Feel free to add your comments below.

**Comment by amitsethitx** [comment]
Hello Akshay - I am using a custom template ( Project created in DevOps )
and then importing  via Devopsgenertor .

I verified the service connection (subscription ) before running the
releases but still giving these errors .

**Comment by amitsethitx** [comment]
Hello Akshay - I am using a custom template ( Project created in DevOps ) and then importing  via Devopsgenertor .  

I verified the service connection (subscription ) before running the releases but still giving these errors .

**Comment by aksh-h** [comment]
Amit, Is it possible to share the template with details like which service end point and what you are trying to achieve with this?

**Comment by amitsethitx** [comment]
Please find the attached template .

**Comment by amitsethitx** [comment]
Please contact  @wayneme  for details.

**Comment by aksh-h** [comment]
We haven't received any files. please share it through [email](mailto:akshay.hosur@ecanarys.com)

**Comment by aksh-h** [comment]
Hi Amit, 
Could not get the source code form your repo. 

Meanwhile can you compare your pipeline definitions with your primary project and the newly created project using Demo Generator? So that you can figure out if anything missing in the template. Let us know your updates.

**Comment by amitsethitx** [comment]
Hello Akshay - I think I resolved the issue .

Looks like when DemoGenerator imports the projects -> Doesn't clear the
service connection under project settings .

Now when you clear them and reset the connection everything starts working
fine.
Please reset the connections to subscriptions in the release pipeline when
you import the projects .

**Comment by aksh-h** [comment]
Amit, Thank you. Could you please clear me what do you mean by "clear and reset" here.
When the new project created, pipeline would not have configured with any connections and the service connection which were created needs to be authorized then use it for the pipeline.

I'm not clear with clear and reset point. 😐 

:smiley:
--




:smiley:
--

**Comment by amitsethitx** [comment]
Hello Akshay - I deleted the following service connection  and re
authorized at agent subscription .


[image: image.png]\\\

**Comment by aksh-h** [comment]
Thank you Amit. Since reported issue has been resolved, I'm closing the issue.

**Comment by amitsethitx** [comment]
Thanks
