### ISSUE TITLE
Not to able to create project devops using template 

### ISSUE THREAD

**Issue by tmastana** [microsoft/AzureDevOpsDemoGenerator#286]
template1 'Manage release cadence in Azure Pipelines with deployment patterns'
template2 'Automate Azure Function deployments with Azure Pipelines'

It is taking ending time to complete the project creation. 
![image](https://user-images.githubusercontent.com/18572354/85411716-51bff080-b586-11ea-8c01-71a1e71325b5.png)

 
![image](https://user-images.githubusercontent.com/18572354/85411754-5f757600-b586-11ea-9ccc-7263add65ea3.png)

**Comment by aksh-h** [comment]
Hi @tmastana, Are you able to reproduce this? We recommend you to retry in an incognito window. Let us know if the issue persists.

Thanks!
