### ISSUE TITLE
Error while creating build definition: TF401019: The Git repository with name or identifier 779D8E0C-355F-46A8-B232-ABB2CC07ACB0 does not exist or you do not have permissions for the operation you are attempting.

### ISSUE THREAD

**Issue by pascalbillot** [microsoft/AzureDevOpsDemoGenerator#287]
Created custom template to create DevOps project.
The project gets created fine but I get this error and a service connection to an unknown GitHub repo is added to the project.

> Error while creating build definition: TF401019: The Git repository with name or identifier 779D8E0C-355F-46A8-B232-ABB2CC07ACB0 does not exist or you do not have permissions for the operation you are attempting.

**Comment by aksh-h** [comment]
Hello @pascalbillot, thank you for reaching us. 

This might occur when the repository that you want to use is private.

Can you unzip the template file and check /serviceendpoints/*.json files. If you see any repository that is private and trying to authenticate, make it public and try once.

Let us know your updates.

**Comment by aksh-h** [comment]
@pascalbillot we are closing the issue, you can reopen the same if the issue persists
