### ISSUE TITLE
Organization doesn't appear in the List

### ISSUE THREAD

**Issue by aldodfm** [microsoft/AzureDevOpsDemoGenerator#291]
Hello,

I'm trying to create some projects using DemoGenerator, but the organization where i'm administrator doesn't appear in the list:
![image](https://user-images.githubusercontent.com/907559/86441464-895c3480-bd0c-11ea-8f3b-9bc3b27d3bd9.png)

My organization is: https://dev.azure.com/AASolutions

**Comment by aksh-h** [comment]
Hi @aldodfm, Thank you for reaching us.
This might happen when you logged in with active directory other than which has the required organization. You can change the directory  from Azure DevOps profile [page ](https://aex.dev.azure.com/me?mkt=en-US&campaign=o~msft~old~vsts~profile)and login again.

Reference document [here](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)
