### ISSUE TITLE
Migrate Queries and Dashboards currently

### ISSUE THREAD

**Issue by Frenemee2020** [microsoft/AzureDevOpsDemoGenerator#299]
Please let me know if we have capabilities to migrate queries and dashboards currently in Azure DevOps Demo Generator.

**Comment by aksh-h** [comment]
Hi @Frenemee2020, Thank you for reaching us.
Currently this is supported only for some standard templates in Azure DevOps Demo Generator. You can use an external tool for this purpose [here](https://vstscopydashboard.ecanarys.com/)
