### ISSUE TITLE
Pipeline/Release variables all converted to secrets?

### ISSUE THREAD

**Issue by Styxxy** [microsoft/AzureDevOpsDemoGenerator#303]
In PR #218 (completed) all/many of the pipeline/release variables are converted to secrets.
What is the reasoning behind it?

Some of the labs are not matching anymore, and also values are now hidden, while some of them seems not have any reason to be hidden (eg url to ACR, DB name, ...).

/cc @aksh-h

**Comment by aksh-h** [comment]
Hi @Styxxy, Thank you for reaching us.
we were receiving some errors messages when the variable kept as plane text. So we converted those into secrets. Based on user feedback we are gradually adding those into documentations.
We have noted your point and will ask the team to verify the content once.

Thanks!!
