### ISSUE TITLE
Issue with Azure DevOps Demo

### ISSUE THREAD

**Issue by patternproject** [microsoft/AzureDevOpsDemoGenerator#304]
Hi, 

I am getting an error that I do not have the rights to create a project, though am sure I have these rights.  What is the best way to troubleshoot/fix this

Thanks

**Comment by dmckinstry** [comment]
Hi @patternproject - I know @aksh-h or @Damovisa will add more, but one thought.  Can you [create a new test org](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azure-devops#create-an-organization) to ensure that you have full admin rights and then try again with that org?

**Comment by patternproject** [comment]
Resolved. 

Well, the trick was to change the "Org Permissions" on the AzureDevOps. I asked site admin to add me both to the "Project Collection Administrators" and "Project Administrators group". 

Thanks for following up. 

    On Friday, July 24, 2020, 7:51:04 PM GMT+5, Dave McKinstry <notifications@github.com> wrote:  
 
 


Hi @patternproject - I know @aksh-h or @Damovisa will add more, but one thought. Can you create a new test org to ensure that you have full admin rights and then try again with that org?
