### ISSUE TITLE
Requesting access to AzureDevOpsDemoGenerator

### ISSUE THREAD

**Issue by Shgunter** [microsoft/AzureDevOpsDemoGenerator#308]
Hi, I'm looking to get access to this demo generator to generate a baseline adoption plan for multiple Azure Engineering investment program customers.  Thank you!

**Comment by dmckinstry** [comment]
Hi @Shgunter - I'm curious what you need? The code is available open source in this repo.  It is [hosted for your use](https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject) today including the ability to generate and use custom templates.  And we're looking into making a Docker container for self-hosting.  Can you provide more context on the request?

**Comment by Shgunter** [comment]
I am lacking permissions to Create New Projects in Azure DevOps Demo Generator when trying to create a new project (Cloud Adoption Plan) .  I’ve outlined below, the path to repro the error and a SS of the error details itself.   Thanks for the prompt reply @microsoft/AzureDevOpsDemoGenerator<mailto:reply@reply.github.com>!


  *   Aks.ms/caf <https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/#:~:text=The%20Cloud%20Adoption%20Framework%20is%20a%20full%20lifecycle,how%20enterprises%20procure%2C%20use%2C%20and%20secure%20technology%20resources.>  -->  Tools & Templates<https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/tools-templates> --> Cloud Adoption Plan Generator<https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/template> --> Sign-in / Create Project<https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject>
     *   Add Project Name
     *   Select organization (AzureFastTrack selected)
     *   Select Template (Cloud Adoption Plan selected)
     *   Click “Create project”
     *   ERROR!  (SS below)

[cid:image002.png@01D665B6.8819E520]

  *


Thank you,
Shawn Gunter
M: 289-971-1881
Sr. Program Manager, FastTrack for Azure
Azure Engineering | Customer Experience (CXP)

[Image result for microsoft logo]

**Comment by dmckinstry** [comment]
Hi @Shgunter - That error is generally because of your permissions in the target Azure DevOps org.  That is, you likely don't have permissions to create a project, so the generator will fail when trying to make one on your behalf.  @aksh-h has a FAQ and may have more guidance to help.

**Comment by aksh-h** [comment]
Hi @@Shgunter, you can find FAQ [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/FAQ.md)

**Comment by aksh-h** [comment]
We assume you are able to provision the project. Hence closing the issue.
