### ISSUE TITLE
Feature implementation

### ISSUE THREAD

**Issue by apetkov81** [microsoft/AzureDevOpsDemoGenerator#310]
Hello guys and thanks for keeping alive and pushing further with adding new features on the demogenerator. I want to ask is there any chance extracting template from custom defined (inherited agile or scrum process) to be implemented in the solution. I think a lot of people need this feature.

**Comment by aksh-h** [comment]
Hello @apetkov81, Thank you for reaching us. The feature is already available, you can export project template from custom or inherited process templates.
Please refer [limitation](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md) doc for more info.
