### ISSUE TITLE
Error while creating build definition: The pipeline is not valid.

### ISSUE THREAD

**Issue by narpur2127** [microsoft/AzureDevOpsDemoGenerator#312]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 5.*, job 'Phase_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 5.*, job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
Hello @narpur2127,
Could you please let me know which template you have used to provision the project?

Looking at the error, this might require some extension which has to be present before/while provisioning the project. 
Please refer [FAQ](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/FAQ.md)

**Comment by rgaur726** [comment]
The error is occurring when provisioning the TailwindTraders template. ARM Outputs version is 6.0 while the template requires task version 5 and hence the issue. Please check this

**Comment by kingma-sbw** [comment]
THis still is an issue.
