### ISSUE TITLE
ARM Outputs:5

### ISSUE THREAD

**Issue by shake** [microsoft/AzureDevOpsDemoGenerator#313]
Error while creating release definition: Tasks with versions 'ARM Outputs:5.*' are not valid for deploy job 'Agent job' in stage Stage 1.

when I create project ,meet the error.

**Comment by aksh-h** [comment]
Hi @christophe-havard-sonarsource, sorry to hear this. 
Please refer [FAQ](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/FAQ.md)

**Workaround**
- Install the extension from marketplace
- Create a pipeline manually - try to add the task which is failing while provisioning project
- Once you are able to add, try creating the project using Demo Generator

Let us know if this helps for you.

**Comment by shake** [comment]
I think it is bug ,not extensions problem. I have run it two , same problem.

**Comment by aksh-h** [comment]
did you try the workaround?

**Comment by christophe-havard-sonarsource** [comment]
It seems like the ARM Outputs task has not version 5 anymore
![image](https://user-images.githubusercontent.com/65390576/89267863-0f370c80-d638-11ea-8c8c-427ec28d377e.png)
