### ISSUE TITLE
Error while creating release definition: Tasks with versions 'ARM Outputs:5.*' are not valid for deploy job 'Agent job' in stage Stage 1.

### ISSUE THREAD

**Issue by Deepti480** [microsoft/AzureDevOpsDemoGenerator#314]

**Comment by aksh-h** [comment]
Hello @Deepti480, you may encounter this error if you are trying to install the extension and provision the project for the first time. Extension might take sometime to install and be available for the pipeline. You can retry after some time.

Meanwhile, you can the following workaround

- Install the extension from marketplace
- Create a pipeline manually - try to add the task which is failing while provisioning project
- Once you are able to add, try creating the project using Demo Generator

Let us know if this helps for you. 

#313
