### ISSUE TITLE
"Build your own template" breaking on work items

### ISSUE THREAD

**Issue by gmoed** [microsoft/AzureDevOpsDemoGenerator#320]
I'm trying to use the build your own template to import a project and  getting errors while querying for work items (even when there are no work items in the project) and the import process does not move on that step. I tried different projects (some with work items, some without) and all of them terminate with the exact same error

```
Error while querying work items: VS403474: You requested 381 work items which exceeds the limit of 200

Error while querying work items: VS403474: You requested 209 work items which exceeds the limit of 200

Error while querying work items: VS403474: You requested 209 work items which exceeds the limit of 200
```

**Comment by aksh-h** [comment]
#186
