### ISSUE TITLE
Issue provisioning new private template

### ISSUE THREAD

**Issue by MichaelGuiney-BE** [microsoft/AzureDevOpsDemoGenerator#325]
Hi, I got an error when creating a private template from one of our projects. It looks to be an issue with a release definitions, just guessing from looking at call stack shown in diagnostic output log, which is as follows:

`Object reference not set to an instance of an object. at AzureDevOpsDemoBuilder.Services.ExtractorService.NormalPipeline(ProjectConfigurations appConfig, Int32 count, String templatePath, JObject def, String fileName, JToken repoName, JToken type) in D:\a\1\s\src\AzureDevOpsDemoBuilder\Services\ExtractorService.cs:line 923Object reference not set to an instance of an object. at AzureDevOpsDemoBuilder.Services.ExtractorService.GeneralizingGetReleaseDefinitions(ProjectConfigurations appConfig) in D:\a\1\s\src\AzureDevOpsDemoBuilder\Services\ExtractorService.cs:line 1318`

Regards,
Mike

**Comment by aksh-h** [comment]
Hello Mike,
Thank you for reaching us and sharing the logs, we will look into this.

Meantime, could you please try again to generate your template ? let us know if the issue persists.

Thanks

**Comment by MichaelGuiney-BE** [comment]
Re-ran again and this did not happen. Tried this a few times and it fails periodically. I'm happy enough that I am not blocked by this so closing :)
