### ISSUE TITLE
Project creation error

### ISSUE THREAD

**Issue by kenhoose** [microsoft/AzureDevOpsDemoGenerator#327]
I'm trying to create a project in Azure DevOps Demo Generator using a template but I keep receiving this error:

"Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository."

I'm trying to fork the repository and clicking "Authorize" doesn't produce a credential prompt or error.  

Thanks in advance.

Ken

**Comment by aksh-h** [comment]
Hi @kenhoose 
Thank you for reaching us. We would like to know 
- In which site you have been encountering this issue? Since we have an Asp.Net Core version of the application is in preview and we are working on it to make the user experience better
- Have you tried system templates or any private template/zip file to provision your project? If yes, we would like to have a look at into the template
- We recommend you to retry - If the issue persists, please comment below.

Thanks

**Comment by kenhoose** [comment]
Hi Akshay,

To answer your questions, I first login to Azure DevOps Demo Generator.  On
the "Create New Project" window, I enter a Project name, select an
Organization, and choose a template.  In my case, I'm using the "Run
quality tests in your build pipeline from Azure Pipelines." I check off the
box next to "Yes, I want to fork this repository" and click the "Authorize"
button.  I then click the "Create Project" button, which generates the
error message.

I am following along in a MS Learn learning path called "AZ-400: Define and
implement continuous integration."  I'm in the second module "Run quality
tests in your build pipeline from Azure Pipelines" in the third unit
"Exercise - Setup your Azure DevOps environment."  I just retried with the
same error.

You mentioned the ASP.NET Core version in preview and I do see a link to
"We are migrating to Asp.Net core, visit our preview site here" within
Azure DevOps Demo Generator.  I will try building the template there and
let you know how it goes.

Thanks,

Ken

Thanks,

Ken

**Comment by kenhoose** [comment]
Hi Akshay,

The link to the preview site seems to have worked.  What was different here
was that after selecting an Organization, I received this:

[image: image.png]

After checking off the box above and clicking the "Authorize" button, I was
prompted to allow access to the repository.  After granting access, I could
successfully create the project.

I think that I am able to carry on now with the training.  Thanks for your
help!

Ken

**Comment by aksh-h** [comment]
Thank you for your feedback. Please try-out in production [site](https://azuredevopsdemogenerator.azurewebsites.net/) to see the constant result. Let me know if you need any help.

Thanks!
