### ISSUE TITLE
Not able to create a new project

### ISSUE THREAD

**Issue by SyedZeeshanAbbasNaqvi** [microsoft/AzureDevOpsDemoGenerator#330]
Getting below error:

TF50309: The following account does not have sufficient permissions to complete the operation: S.AbbasNaqvi. The following permissions are needed to perform this operation: Create new projects.

**Comment by aksh-h** [comment]
Hello @SyedZeeshanAbbasNaqvi

Please check the following issue #319 . let me know if this helps.

**Comment by SyedZeeshanAbbasNaqvi** [comment]
Thanks aksh-h. I need to check with my organization's admin.
