### ISSUE TITLE
CKWDemo-3

### ISSUE THREAD

**Issue by ckellywilson** [microsoft/AzureDevOpsDemoGenerator#331]
[MIC.zip](https://github.com/microsoft/AzureDevOpsDemoGenerator/files/5283944/MIC.zip)
When using Azure DevOps Demo Generator, I am getting the following error while generating the clone

_Error while creating build definition: To get sources from a different team project, on the Options tab you must set the build job authorization scope to ‘Project collection’ and ensure that the 'Limit job authorization scope to current project' pipeline setting is disabled._

I don't see how to set the build job authorization scope and cannot find the setting, 'Limit job authorization scope to current project' setting.

How do I fix the build failures?

[AB#3499](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3499)

**Comment by aksh-h** [comment]
Hi @ckellywilson,

Looks like the pipeline you are referring the other project in the organization, but the build setting has been configured the current project scope.
Please refer the following [document](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#build-job-authorization-scope) regarding build job authorization scope.

Under pipeline >>option tab you can find the following setting

![image](https://user-images.githubusercontent.com/38463158/94285124-ed3f7380-ff70-11ea-866e-297b97121532.png)

**Comment by ckellywilson** [comment]
Hello @aksh-h,

I don't see the above menu items in your screenshot when I click on _Pipelines_. When I click on my _Pipelines_ left-menu. I see the following:

![image](https://user-images.githubusercontent.com/8071092/94292586-c65a5080-ff22-11ea-9214-f8a9fea04886.png)

When I click on the pipeline, I see the following:

![image](https://user-images.githubusercontent.com/8071092/94292740-f144a480-ff22-11ea-8dd7-3c3d317e11d8.png)

Do you know why I can't see the menu you have?

**Comment by aksh-h** [comment]
Please edit the pipeline, you can find the option tab.

**Comment by ckellywilson** [comment]
When I edit the pipeline, this is what I see. I don't see the menu items you have.

![image](https://user-images.githubusercontent.com/8071092/94293792-767c8900-ff24-11ea-917d-c1c1c3997f96.png)

**Comment by aksh-h** [comment]
@ckellywilson is that the same project you encountered error?

**Comment by ckellywilson** [comment]
@aksh-h ,

This is the source project I used to create the artifacts for the Azure DevOps Demo Generator. I then targeted this Org and used the Azure DevOps Demo Generator to create the clone project.

I'm not sure if I answered your question.

**Comment by aksh-h** [comment]
This is somethhing related to pipeline configuration setting, not with the demo generator. Need to figure out.

I'll Look into the template zip file and get back to you with my findings.

**Comment by aksh-h** [comment]
@ckellywilson this works for me as expected. I can able to create project without fail.

As I gone through the pipeline definition in the zip template, I could see ```"jobAuthorizationScope": "projectCollection"```.
I suspect the organization you are trying might have enabled _Limit job authorization scope to current project for non-release pipelines_ . This restrict access to only those repositories that are in the same project as the pipeline.

If you are admin of the organization or project, please disable this configuration.

Please refer the following [reference document](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml#job-authorization-scope)

Let me know if this helps.

**Comment by ckellywilson** [comment]
Hello @aksh-h ,

Here is my Org settings for _Limit job authorization scope to current project for non-release pipelines_

![image](https://user-images.githubusercontent.com/8071092/94351872-f9d0d400-0023-11eb-9e6f-8dd15f66a1d1.png)

Here is the same setting for the project I am using as the base project for a clone:

![image](https://user-images.githubusercontent.com/8071092/94351954-bfb40200-0024-11eb-80f5-66d0a4feb113.png)

After generating the artifacts and then trying to clone the project from the generator, I get the following on the main page

![image](https://user-images.githubusercontent.com/8071092/94352022-70220600-0025-11eb-9181-d74c0ce6e3c7.png)

Also, the popup.

![image](https://user-images.githubusercontent.com/8071092/94352032-9182f200-0025-11eb-87cb-136e7f72ed78.png)


I think the secret is that I don't have the pipeline configuration screen you referenced above in order to set the build configuration scope to _Project Collections_

![image](https://user-images.githubusercontent.com/8071092/94352038-b7a89200-0025-11eb-8f5a-8e406a370623.png)

Do you know to whom I can reach out to see why I don't have this screen?

**Comment by aksh-h** [comment]
It worked in my trial. Could you please try this in different organization?

![](https://user-images.githubusercontent.com/8071092/94352038-b7a89200-0025-11eb-8f5a-8e406a370623.png)

The above screen you can see only in classic pipeline not in yml. For yml pipeline this configuration is done at org/project level.

Also there is an Id ```5fe69a29-a3a0-4ac3-a952-e7868912e174``` left in the ```/BuildDefinitons/MIC.json``` file. Please keep this empty as ``` "id": "",```. Make sure that you are not missing the ending comma.

**Comment by ckellywilson** [comment]
Thank you, @aksh-h for the clarification that the Classic Pipeline editor needs to be used. My pipeline was created using yaml. I did open the BuildDefinitions/MIC.json file, set the "Id" value to "", reran the generator tool and the project was created successfully.

Can we please get that documentation to the Azure DevOps Demo Generator tool, if it doesn't already exist?

**Comment by aksh-h** [comment]
All the docs you can find on here on GitHub [repo](https://github.com/microsoft/AzureDevOpsDemoGenerator).

Hope the issue has been resolved. Hence closing the issue.
Feel free to create or update the issue if required.
