### ISSUE TITLE
Documentation to modify the custom JSON file 

### ISSUE THREAD

**Issue by anshul348** [microsoft/AzureDevOpsDemoGenerator#333]
Hi Team,

Could you please do let me know which all the fields are mandatory and other things, I am not getting what else i can modify when i export the project and try to import if i would like to modify and create a reference project for my org

[AB#3505](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3505)

**Comment by aksh-h** [comment]
Hi @anshul348 
Thank you for reaching us. Could you please elaborate more on your question?
