### ISSUE TITLE
Using Custom Template

### ISSUE THREAD

**Issue by asifmasooddevops** [microsoft/AzureDevOpsDemoGenerator#337]
Hi Team,

This is the first time I used AzureDevOpsDemoGenerator for creating and utilizing Custom Template. When the new Project is created, I see that not all work items are copied, the area path configuration not copied and as well as the iteration path not copied, board swimlanes styles are not copied. Is it a limitation of the tool or am I doing something wrong. Is there any way I can edit the JSON file to match the master project? Attached screenshot.
[Issue Screenshot.docx](https://github.com/microsoft/AzureDevOpsDemoGenerator/files/5378375/Issue.Screenshot.docx)

Any help is highly appreciated

[AB#3515](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3515)

**Comment by asifmasooddevops** [comment]
Hi, thanks for the reply. Is it not possible that I manually edit the .JSON file and import it afterwards? If yes, can you share some technical details on it?

**Comment by aksh-h** [comment]
Area paths and sprints will not created as is in the source project. Demo Generator will create default sprints and assign the dates.
Work items should be imported if the select organization has the same process template.

**Comment by asifmasooddevops** [comment]
Hi, The Organization has the same process template (custom) but work items are still not copied over except one work item. Is there any way that the downloaded .json files can be edited to make the fine tuning i.e area path, iteration path etc? If not is there an plan in the future release to include this feature? It is very important because if we do SAFe on Azure DevOps, the iterations and area path configured to support PI, Porfolio, Program structure.

**Comment by asifmasooddevops** [comment]
Also, one more question. Is it possible to keep the template zip file in Azure Repo and get it from there during the project creation using the demo generator. I see 3 options, Local. GitHub and URL. DOes the URL supports Azure Repo URL?

**Comment by aksh-h** [comment]
> Hi, The Organization has the same process template (custom) but work items are still not copied over except one work item. Is there any way that the downloaded .json files can be edited to make the fine tuning i.e area path, iteration path etc? If not is there an plan in the future release to include this feature? It is very important because if we do SAFe on Azure DevOps, the iterations and area path configured to support PI, Porfolio, Program structure.

We have very limited support for Custom Process Templates here, if the work items are not creating, try to modify the area path/iteration path to default area/sprint, and wrap it up as zip file, try to provision new project using Demo Generator.

**Comment by aksh-h** [comment]
> Also, one more question. Is it possible to keep the template zip file in Azure Repo and get it from there during the project creation using the demo generator. I see 3 options, Local. GitHub and URL. DOes the URL supports Azure Repo URL?

You can keep the templates in GitHub repo and provide the zip file URL/raw URL in the required field.
If the repo is private, it requires credentials too.

Let me know if you need any other help.

**Comment by asifmasooddevops** [comment]
Thanks for the reply. This topics can be closed now.
