### ISSUE TITLE
Getting "Error while creating release definition: Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by SrivathsanJ** [microsoft/AzureDevOpsDemoGenerator#340]
Trying to run the Deployment group generator with basic values. get the belowerror

Error while creating release definition: Index was outside the bounds of the array.

Just the build definition is getting crearted

[AB#3518](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3518)

**Comment by aksh-h** [comment]
Hello @SrivathsanJ Thank you for reaching us.

Could you please retry the same template? Please feel free to comment back If the issue still persists.

Thanks.
