### ISSUE TITLE
Smarthotel360 Provision error

### ISSUE THREAD

**Issue by nabilnaim** [microsoft/AzureDevOpsDemoGenerator#345]
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can create an issue with logs here and we will try to help you.

Click on View Diagnostics button to share logs with us.

Diagnostics Log:
Error while creating release definition: Tasks with versions 'ARM Outputs:5.*' are not valid for deploy job 'Agent job' in stage Stage 1.

[AB#3532](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3532)

**Comment by aksh-h** [comment]
Hello @nabilnaim Thank you for reaching us.
We will look into this.

**Comment by aksh-h** [comment]
Seems like you are using older version of extension. This required Arm Outputs task with version 6.*
Please update from [marketplace](https://marketplace.visualstudio.com/items?itemName=keesschollaart.arm-outputs) and try to provision project again.

Thanks.
