### ISSUE TITLE
There Was a Problem  When Creating the WorkItem

### ISSUE THREAD

**Issue by WJinhai** [microsoft/AzureDevOpsDemoGenerator#347]
Hi , I  Use  This  Api  "https://dev.azure.com/jhaiwang/test/_workitems/Issue?api-version=5.0" to create a WorkItem, The StatusCode  is 200, but the result body  "JavaScript is Disabled  Please enable javascript and refresh the page" .  Looking forward to your answers

[AB#3535](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3535)

**Comment by aksh-h** [comment]
Hello @WJinhai
Hope this is not a right place to discuss this. You can raise a discussion thread at [visual studio developer community](https://developercommunity.visualstudio.com/spaces/21/index.html)

Thanks.
