### ISSUE TITLE
Space Game - Web - Workflow

### ISSUE THREAD

**Issue by ixdd** [microsoft/AzureDevOpsDemoGenerator#348]
[AB#3536](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3536)

**Comment by aksh-h** [comment]
Could you please explain more on the problem you faced?

**Comment by aksh-h** [comment]
we are closing this issue. if the issue still persist, you can reopen the thread.

**Comment by ixdd** [comment]
Thank You!
