### ISSUE TITLE
Failed to create containersolutionstoKubernetes

### ISSUE THREAD

**Issue by casperlw** [microsoft/AzureDevOpsDemoGenerator#349]
https://azuredevopsdemogenerator.azurewebsites.net/?name=Deploymulti-containersolutionstoKubernetes

Always failed, and report error like below, I have forked project manually it can be success. 

Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.

[AB#3537](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3537)

**Comment by aksh-h** [comment]
Hi @casperlw thank you for reaching us.

We couldn't reproduce your scenario. Could you please give it another and see?
Let us know your updates.

Thanks.

**Comment by casperlw** [comment]
@aksh-h I have deleted the project and try again, the result is same :(, By the way, the other project all success like Space Game - web, Space Game - web - Deploy. 
Only this one failed https://docs.microsoft.com/en-us/learn/modules/deploy-kubernetes/
![image](https://user-images.githubusercontent.com/38447937/100401209-c4804b00-3093-11eb-99bf-345d3990545a.png)

**Comment by aksh-h** [comment]
@casperlw sorry to hear this, we couldn't reproduce this.
As a workaround, create a project and fork the repository from GitHub and configure the pipeline.
