### ISSUE TITLE
ERROR: SmartHotel360 Template will not fully generate

### ISSUE THREAD

**Issue by MarcGervais** [microsoft/AzureDevOpsDemoGenerator#352]
![image](https://user-images.githubusercontent.com/1890204/101989011-76f70700-3c6b-11eb-87e4-82508a776a30.png)

I keep receiving the above error while attempting to generate a project using the SmartHotel360 template.

[AB#3550](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3550)

**Comment by aksh-h** [comment]
Hi @MarcGervais thank you for reaching us. Please refer to #345
Let us know your updates.
Thanks

**Comment by aksh-h** [comment]
Let us know if you need any more info. Thanks.
