### ISSUE TITLE
DevOps Generator "Could not load your organizations"

### ISSUE THREAD

**Issue by TrevorBarry** [microsoft/AzureDevOpsDemoGenerator#353]
I have successfully used the generator in the past to create projects in my organization. When I tried to use it today using the same credentials that I use for my DevOps organization the generator web site gives me the message - 

"Could not load your organizations. Please check if the logged in Id contains the Azure DevOps Organizations or change the directory in profile page and try again."

![image](https://user-images.githubusercontent.com/14116063/102032735-9c793300-3d87-11eb-9265-15cb70229ea6.png)

There is no 'profile page' in the devops site. My devops stuff is working fine, just can't the generator to behave.

Any ideas?

[AB#3551](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3551)

**Comment by aksh-h** [comment]
Hi @TrevorBarry thank you for reaching us.
One of the reason for this behavior, you might have logged in to different directoctory where the API is unable to find any organizations.

You can sign out and sign in again or use  incognito window of the browser and login and retry.

Let us know your updates.
Thanks.

**Comment by TrevorBarry** [comment]
> Hi @TrevorBarry thank you for reaching us.
> One of the reason for this behavior, you might have logged in to different directoctory where the API is unable to find any organizations.
> 
> You can sign out and sign in again or use incognito window of the browser and login and retry.
> 
> Let us know your updates.
> Thanks.

Yep, I've done all that. Tried different browsers, different machines, incognito mode. 

Doesn't make any difference the generator can't see my organizations.

**Comment by aksh-h** [comment]
Could you please confirm the logged in active directory and the directory which has the organizations are same ?

**Comment by TrevorBarry** [comment]
> Could you please confirm the logged in active directory and the directory which has the organizations are same ?

How? I'm using the same credentials to log in to Azure, Azure devops and the demo generator. The generator does not provide a way for me to see what I'm logged in to.

**Comment by aksh-h** [comment]
Demo Generator look for organizations present in the logged in directory to display it for end user.
You can change the logged in directory [here](https://aex.dev.azure.com/me?mkt=en-US&campaign=o~msft~old~vsts~profile)

Also you can refer to this [doc](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops) for more info.

Let us know your updates.

Thanks

**Comment by aksh-h** [comment]
#291

**Comment by TrevorBarry** [comment]
> 
> 
> Demo Generator look for organizations present in the logged in directory to display it for end user.
> You can change the logged in directory [here](https://aex.dev.azure.com/me?mkt=en-US&campaign=o~msft~old~vsts~profile)
> 
> Also you can refer to this [doc](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops) for more info.
> 
> Let us know your updates.
> 
> Thanks

Ah, thank you! I didn't know that page (https://aex.dev.azure.com/me?mkt=en-US&campaign=o~msft~old~vsts~profile which redirects you to https://aex.dev.azure.com/me?mkt=en-US#) existed. 

That fixed my problem, thank you again!

**Comment by aksh-h** [comment]
Thanks for your updates 👍

**Comment by MaxiPalle** [comment]
See also #436.
