### ISSUE TITLE
Error while importing source code: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by kwiecien** [microsoft/AzureDevOpsDemoGenerator#360]
[AB#3564](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3564)

**Comment by aksh-h** [comment]
Hi @kwiecien Thank you for reaching us.
 Could you please let me know which template you tried? Meanwhile, did you try again to provision the same project?
