### ISSUE TITLE
Error while importing source code: Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by kwiecien** [microsoft/AzureDevOpsDemoGenerator#361]
Create a release pipeline with Azure Pipelines
Set up a continuous delivery (CD) pipeline that automates the process of deploying your application.

Lab URL: Create a release pipeline

> Error while importing source code: Value cannot be null. Parameter name: key

[AB#3565](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3565)

**Comment by aksh-h** [comment]
Hi @kwiecien Thank you for reaching us.
We unable to reproduce this error? If the issue still persists, please add your comment below.
