### ISSUE TITLE
Cloud Adoption Framework Template for SQL and Server Mismatch

### ISSUE THREAD

**Issue by PranjalPatel24** [microsoft/AzureDevOpsDemoGenerator#364]
The following Templates

ServerMigration_CAF_DevOps_ProjectTaskList
SQL_CAF_DevOps_ProjectTaskList

both highlights the tasks of SQL. Previously Server and SQL both were different. But now I cant find the task lists for Server Migration

[AB#3568](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3568)

**Comment by aksh-h** [comment]
Hi @PranjalPatel24 Thank you for reaching us.
It was some mismatch in the template directories and files, could you please retry and let us know your updates?

Thanks

**Comment by PranjalPatel24** [comment]
Hello @aksh-h Thanks for the help.
I can confirm that the issue is resolved.

Thanks

**Comment by aksh-h** [comment]
Thank you for your updates. Hence closing the issue.
