### ISSUE TITLE
Template Generator fails to fork GitHub repo

### ISSUE THREAD

**Issue by dwillis50** [microsoft/AzureDevOpsDemoGenerator#366]
I am getting the following error when running the Template for the Learning module "Implement a code workflow in your build pipeline by using Git and GitHub", step 3 "Set up your Azure DevOps Environment":

Copy Diagnostic Log
"Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository."

The generator successfully creates the project in Azure DevOps Services, but doesn't fork the GitHub repo. I have tried several other templates, and they all fail with the same error. It is worth noting that I was able to run many of these same templates 2 months ago, and the only thing that changed since then is that I created a new organization tied to my personal account.

I have done the following troubleshooting, all with the same result/error:

- Attempted running the templates multiple times, including some with InPrivate browser
- Deleted the Azure DevOps project between attempts
- Manually forked the repo in GitHub without any issues
- Attempted running the template with the GitHub repo already forked
- Deleted the existing repositories that I had used before
- Deleted the organization that I had created, and retried running the templates

Screenshot 1 (Running template)
![image](https://user-images.githubusercontent.com/8116913/103419351-a9a46900-4b60-11eb-8943-ca16259af3d8.png)

Screenshot 2 (Error)
![image](https://user-images.githubusercontent.com/8116913/103418277-005b7400-4b5c-11eb-99e3-1e4391ac5bde.png)

[AB#3570](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3570)

**Comment by aksh-h** [comment]
Hi @dwillis50 Thank you for reaching us.

Our team is looking into this issue. Meanwhile, please see if [this](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/362) can help.

Currently we can suggest a workaround, create a new GitHub account (not Org) and try to provision the project.
We will comeback with our findings.

Thanks.

**Comment by dwillis50** [comment]
@aksh-h - provisioning the project works on a new GitHub account, but is still failing on my main account. While that is fine for these learning exercises, I'd like to get to the bottom of this so I don't have to maintain two accounts. Does it appear that adding the org caused this problem in the first place? If so, what can we do to clean that up? I already belonged to one org prior to that and these templates worked fine. And I have since deleted the org that I added.  Also, since it is the generator itself that is creating the GitHub repo (with no spaces I might add), I don't see how [this](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/362) applies, since I don't control the name of the source or destination repo. FWIW - I did remove the spaces from the Azure DevOps project name field but that made no difference at all. Please let me know what I can do to help troubleshoot.

**Comment by aksh-h** [comment]
Thank you for share information.
There are two kinds of repos: 
 - User Repo and  - ex: GitHubUserId/Repo
 - Organization Repos - ex: Org/Repo
When the tool tries, it forks the repo to User repo. Creating an organization doesn't affect the forking functionality as it doesn't look into the organization to fork. Our team also verified this behavior by creating new Org, unfortunately we couldn't reproduce.

**Comment by aksh-h** [comment]
We are hoping you are happy with the work around. If you need any help, please reopen the issue. Thanks.
