### ISSUE TITLE
Project from a local git source from a shell script

### ISSUE THREAD

**Issue by jeevaeastpoint** [microsoft/AzureDevOpsDemoGenerator#367]
The SourceCode repo artefact contains "gitsource" as the source for the project to be created. I am looking for a way to run a shell script which will generate a project I need with the respective state. Is it possible to run a script and select the local directory as git source. 

[AB#3572](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3572)

**Comment by aksh-h** [comment]
Hi @jeevaeastpoint Thank you for reaching us.
You can upload your private template to provision a new project. Source code can be present in Public Git Repo or Azure Repos. We don't support local directory as git source.

Thanks!
