### ISSUE TITLE
Deployment Groups template - release definition not generated

### ISSUE THREAD

**Issue by jaydarius** [microsoft/AzureDevOpsDemoGenerator#369]
Hey team,

The project doesn't include a release definition.  What was built for me included all 4 other components (e.g. build definition)

[AB#3573](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3573)

**Comment by aksh-h** [comment]
Hi @jaydarius Thank you for reaching us.

Could you please try it again to provision Deployment Group project? If you encounter same issue, please feel free to comment below. Meanwhile our team will look into this.

Thanks!

**Comment by aksh-h** [comment]
Hi @jaydarius,
Our team has confirmed that the templates are working normal. Deployment group pipelines are provisioned as expected.

If possible please give it a retry.
Thanks.
