### ISSUE TITLE
Template generator finds Github references when there are none

### ISSUE THREAD

**Issue by Jiihaa** [microsoft/AzureDevOpsDemoGenerator#370]
When making a template from existing project, it generates 13 github service connections, although whole source code is in the Azure Repo. When importing the template, it says that "The selected template includes a GitHub repository. " even when it doesn't. Then when run, it fails with errors "Error while creating build definition: TF401019: The Git repository with name or identifier B539701E-6E8E-4AF1-92E7-9F0FA6FFBB10 does not exist or you do not have permissions for the operation you are attempting."

[AB#3574](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3574)

**Comment by aksh-h** [comment]
Hi @Jiihaa Thank you for reaching us.
This looks very strange. Sorry for inconvenience caused. 
Could you please try to generate the template for same project ? If the issue persists, please comment below.

Thanks!

**Comment by aksh-h** [comment]
We couldn't reproduce this behavior.
Please let us know if you are still facing the same issue. If it is related to any particular project from your organization, we can discus this over the call.
