### ISSUE TITLE
error received while creating octopus Project

### ISSUE THREAD

**Issue by muralikrishna188** [microsoft/AzureDevOpsDemoGenerator#371]
Error while creating service endpoint: The URL specified for parameter XXXXXX.octopus.app is not valid. Parameter name: endpoint.Url Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '179fac12-2402-486e-80cf-5a6a8571f7c0'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Phase_1', step 'OctopusPack1'.)

[AB#3575](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3575)

**Comment by aksh-h** [comment]
Hi @muralikrishna188,
Thank you for reaching us. 
The template requires Octopus extension, which should be installed and enabled in your organization before provisioning the project. If the extension is installed and it is still throwing the issue, please go back to the pipeline and try to add the octopus task manually. In some cases, these extensions are taking longer than expected time to install and enable.

The URL and the key which you enter at the time of provisioning the template will be validated at the time of create a service end point of type Octopus. This could be one of the issue. Please make sure that you are entering the right URL.

Let us know if you need any help.

Thanks.
