### ISSUE TITLE
Problems trying to to create Version Controlling with Git in Azure Repos

### ISSUE THREAD

**Issue by zuyiro** [microsoft/AzureDevOpsDemoGenerator#372]
The message that shows is "your project is being created" and the process never ends and the project is not created.
![image](https://user-images.githubusercontent.com/56260469/105082735-001b0e00-5a62-11eb-8a0a-a18ac96d2742.png)

[AB#3579](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3579)

**Comment by zuyiro** [comment]
The message that shows is "your project is being created" and the process never ends and the project is not created.

**Comment by aksh-h** [comment]
Hi @zuyiro

Looks like two issues are added under the same title

1. Project provision - this might be hung due to session expiry. You could try it again and see if this still exist.
2. Version control - Is the issue is related to importing source code into azure repos in the newly created project?
