### ISSUE TITLE
Generator does not work. 

### ISSUE THREAD

**Issue by zuyiro** [microsoft/AzureDevOpsDemoGenerator#373]
These are the evidences...
![image](https://user-images.githubusercontent.com/56260469/105092918-e680c300-5a6f-11eb-8a1f-686473e737f8.png)
![image](https://user-images.githubusercontent.com/56260469/105092966-ff897400-5a6f-11eb-88d2-b71c7a21d4ed.png)

[AB#3580](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3580)

**Comment by aksh-h** [comment]
Hi @zuyiro Thank you for reaching us.
I have few questions
1. Have you tried to provision project with different name? 
2. Is this happening all the time you tried to create project?
3. Is this happening only in specific organization or in all other organizations as well?

Please let us know if the issue still persists.

**Comment by zuyiro** [comment]
Hi,

1. Yes, I have.
2. It started to fail the second day of the course.
3. It happened in different organizations

Finally, I can do it after restarting my computer.

I am going to check it again today. If problem persists, I will notify you.

Thanks and regards,

Zully
