### ISSUE TITLE
Azure Git repository not imported

### ISSUE THREAD

**Issue by tijmenamsing** [microsoft/AzureDevOpsDemoGenerator#381]
Hi,

I'm trying to generate a project based on a template I created from one of my other projects: https://dev.azure.com/cap-academy/PSD 

When I generate it in the same organization it succeeds (although I do have to manually remove the "id" from my yaml build definition as described in this issue: https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/331).
When I import it in another organization the repository remains empty. The originating project/repository is public.

[AB#3593](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3593)

**Comment by aksh-h** [comment]
Hi @tijmenamsing Thank you for reaching us.
It looks strange. Could you please confirm, do you have sufficient access in both organizations?
