### ISSUE TITLE
VS402362: No process template with type e90e4968-11a8-4716-8b5b-e4c45524d95c was found.

### ISSUE THREAD

**Issue by stinethebean** [microsoft/AzureDevOpsDemoGenerator#383]
Hey team, I was trying to replicate the structure of this project - but I keep getting an error. Can you help me?

[AI For Good Research Lab.zip](https://github.com/microsoft/AzureDevOpsDemoGenerator/files/5991990/AI.For.Good.Research.Lab.zip)

[AB#3595](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3595)

**Comment by aksh-h** [comment]
Hi @stinethebean, thank you for reaching us.
Looks like you have templatized your own project which is using custom or inherited process model.
To replicate the project you can use the same organization. Please refer limitation document [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)
