### ISSUE TITLE
Unable to import Service Connections (Service Endpoints) scoped to an Azure Management Group

### ISSUE THREAD

**Issue by ReneRebsdorf** [microsoft/AzureDevOpsDemoGenerator#390]
When attempting to provision service connections of type azrerm, scoped to a management group the following error occurs:

``` error
Error while creating service endpoint: Value cannot be null. Parameter name: managementGroupId
```

Sample json from export:
``` jsonc
{
  "data": {
    "environment": "AzureCloud",
    "subscriptionId": "",
    "subscriptionName": "",
    "scopeLevel": "ManagementGroup"
  },
  "name": "svc-conn-name", // data scrubbing was performed here when posting this issue
  "type": "azurerm",
  "url": "https://management.azure.com/",
  "authorization": {
    "parameters": {
      "tenantId": "guid", // data scrubbing was performed here when posting this issue
      "servicePrincipalId": "guid", // data scrubbing was performed here when posting this issue
      "authenticationType": "spnKey",
      "servicePrincipalKey": "spnKey"
    },
    "scheme": "ServicePrincipal"
  },
  "isShared": false,
  "isReady": true,
  "owner": "Library"
}
```

I guess a fix involves supporting "managementGroupId" in the "data" object.

[AB#3612](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3612)

**Comment by aksh-h** [comment]
Hi @ReneRebsdorf
Thank you for reaching us. We will consider your inputs.
Could you please provide more info on which template you tried?

**Comment by aksh-h** [comment]
Currently service connection with Managed Group is not supported in the Demo Generator. We will consider this as enhancement.

Thanks you.

**Comment by aksh-h** [comment]
#397
