### ISSUE TITLE
Unable to Create project with this repository

### ISSUE THREAD

**Issue by NarenKR** [microsoft/AzureDevOpsDemoGenerator#394]
[AB#3613](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3613)

**Comment by aksh-h** [comment]
Hi @NarenKR Could you please provide more info if you are facing any issue?

**Comment by NarenKR** [comment]
Actually I modified my git token and trying again, in case I face any
issue, I will revert.
