### ISSUE TITLE
Template fail to create management group create service connection  

### ISSUE THREAD

**Issue by sumitjos13** [microsoft/AzureDevOpsDemoGenerator#397]
Hi Team,

I am unable to reuse the template to create the new project using the AzureDevopsDemoGenerator getting below error.

![image](https://user-images.githubusercontent.com/80391668/110613375-1a7f8700-8189-11eb-819b-3eae900599c5.png)

Can you please look into on urgent basis.

[AB#3615](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3615)

**Comment by sumitjos13** [comment]
After adding manually the below parameter in serviceendpoint/test.json it giving below error for spn key, do we need to add it manually

    "managementGroupId"
    "managementGroupName" 

![image](https://user-images.githubusercontent.com/80391668/110616782-da220800-818c-11eb-87ac-0f8549bf0702.png)

**Comment by aksh-h** [comment]
Hi @sumitjos13 Thank you for reaching us.
Hope this user [suggestion](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/390) might help you. 

We are working on it.
