### ISSUE TITLE
failure while creating the release definition

### ISSUE THREAD

**Issue by muthu1425** [microsoft/AzureDevOpsDemoGenerator#401]
I have received below error while creating project, please check and advise. below is the error.

Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1

[AB#3627](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3627)

**Comment by aksh-h** [comment]
Hi @muthu1425 Thank you for reaching us.

This could an issue with version of ARM Output extension. Please install/enable the extension manually and try again.

Thanks!!
