### ISSUE TITLE
.net core version - Create New Template fails to download artifacts

### ISSUE THREAD

**Issue by okko-zure** [microsoft/AzureDevOpsDemoGenerator#405]
1. Build your own template -> https://azuredevopsdemogenerator-core.azurewebsites.net/Extractor/Index
2. Select org, project and analyze - succeeds (reports correct counts of work items etc.)
3. Generate artifacts - succeeds
4. Click **here** to download your file -> redirected to "Create New Template" page and nothing gets downloaded

Tested with Chromium based Edge (latest stable version) and Internet Explorer.

[AB#3629](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3629)

**Comment by aksh-h** [comment]
Hi @okko-zure Thank you for reaching us. 
We are migrating app to ASP.NET core, we appreciate your feedback. We will look into this.

**Comment by aksh-h** [comment]
Fixed and release to .Net Core version. Closing this issue.
