### ISSUE TITLE
Organisation not loaded

### ISSUE THREAD

**Issue by sen0204** [microsoft/AzureDevOpsDemoGenerator#406]
![image](https://user-images.githubusercontent.com/58696525/112153716-92c65d80-8c09-11eb-9fab-24b9f20da50c.png)

HI, my organisation is not loaded, so i'm not able to create a new project

[AB#3630](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3630)

**Comment by aksh-h** [comment]
Hi @sen0204  thank you for reaching us.
You might be logged in with different directory than the organization directory. This [doc](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops) might help you
