### ISSUE TITLE
DevSecOps project into ADO generator

### ISSUE THREAD

**Issue by azwildfire** [microsoft/AzureDevOpsDemoGenerator#409]
I would like to add our new Azure DevSecOps project as an ADO generator template. 
https://dev.azure.com/msftnso/DSO%20VTeam
Please advise :)
Rich
richti

[AB#3632](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3632)

**Comment by aksh-h** [comment]
Hi @azwildfire Thank you for reaching us.
We don't see anything from the shared link. You can export your project as tempate and share it with us.
