### ISSUE TITLE
Tailwind Traders - error creating wiki

### ISSUE THREAD

**Issue by jhart-tygart** [microsoft/AzureDevOpsDemoGenerator#411]
I was trying to use the Tailwind Traders and Parts Unlimited templates to generate projects in my DevOps account. The Parts Unlimited one was successful, but twice trying Tailwind Traders, I get the following error message:

Error while creating wiki: TF401019: The Git repository with name or identifier C739B785-DC84-4661-826D-AB3CC53F9393 does not exist or you do not have permissions for the operation you are attempting.

[AB#3633](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3633)

**Comment by aksh-h** [comment]
Hi @jhart-tygart, this looks like repository is not imported. We haven't seen issue reported much in this. Could you please try again and let us know your updates.

Thanks.

**Comment by jhart-tygart** [comment]
Thank you for the response. I tried this again today, and it worked just fine! :-)
