### ISSUE TITLE
Octopus Pipeline

### ISSUE THREAD

**Issue by sametnur** [microsoft/AzureDevOpsDemoGenerator#414]
Hello,

I've got this error when creating a DevOps Project through the generator. 

The pipeline references a task called '179fac12-2402-486e-80cf-5a6a8571f7c0'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Phase_1', step 'OctopusPack1'.)

[AB#3635](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3635)

**Comment by aksh-h** [comment]
Hi there, thanks for reaching us.
Looks like you are using an older version of the Octopus task or task might be missing. Please install the octopus extension from  https://marketplace.visualstudio.com.

Also please refer the following lab [document](https://azuredevopslabs.com/labs/vstsextend/Octopus/).

Thanks.
