### ISSUE TITLE
Terraform project template broken

### ISSUE THREAD

**Issue by ianwukri** [microsoft/AzureDevOpsDemoGenerator#417]
https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject 

chose the Terraform tmeplate and create a project.

The files inthe Repo are not related to Terraform,they are the Partlsunlimted ecommerce site.

[AB#3645](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3645)

**Comment by aksh-h** [comment]
Hi @ianwukri Thank you for reaching us.

You are right, repository might be PartsUnlimited, Please switch the branch to terraform
![image](https://user-images.githubusercontent.com/38463158/114807938-f2f18f00-9dc4-11eb-9fa5-56163bfc76a2.png)

Refer the following lab [documentation](https://azuredevopslabs.com/labs/vstsextend/terraform/) for more info.

Thanks.
