### ISSUE TITLE
Create Access Rights

### ISSUE THREAD

**Issue by dankuchem** [microsoft/AzureDevOpsDemoGenerator#418]
I'm an Azure App Dev Specialist and received the following message when trying to create an environmen:

Copy Diagnostic Log
×
TF50309: The following account does not have sufficient permissions to complete the operation: Dan Kuchem. The following permissions are needed to perform this operation: Create new projects.

How can my team and I get permissions?

Regards,

Dan Kuchem
dankuchem@microsoft.com

[AB#3649](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3649)

**Comment by aksh-h** [comment]
Hi @dankuchem Thank you for reaching us.

The following thread might help you #319 

Thanks
