### ISSUE TITLE
Looks like all is ok but no project is created.

### ISSUE THREAD

**Issue by hsm-endk-test** [microsoft/AzureDevOpsDemoGenerator#419]
It seem if you had https://azuredevopsdemogenerator-core.azurewebsites.net/Environment/createproject open for some hours and then try create a new template.

It will give a message "Congratulations! Your project is successfully provisioned."
But when following the link there are no project.
I assume it is a session timeout but you forgot to validate it before trying to create a new project

[AB#3650](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3650)

**Comment by aksh-h** [comment]
Hi @hsm-endk-test Thank you for reviewing out test environment. This looks like session expiry issue. We will look into this.

Thanks.

**Comment by aksh-h** [comment]
This could be an intermittent issue, please try to refresh the page using CTRL+F5.
