### ISSUE TITLE
Error on Creating Parts Unlimited project

### ISSUE THREAD

**Issue by gwei2008** [microsoft/AzureDevOpsDemoGenerator#421]
It seems I don't have enough privilege to create the project, Could you please check that for me. My alias is Guowei.
Thanks

Guowei

[AB#3652](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3652)

**Comment by aksh-h** [comment]
Hi @gwei2008 thank you for reaching us.

The following thread might help you. #319 

Thanks.
