### ISSUE TITLE
failure generate project 

### ISSUE THREAD

**Issue by greatglp007** [microsoft/AzureDevOpsDemoGenerator#422]
[AB#3653](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3653)

**Comment by aksh-h** [comment]
Hi @greatglp007 Thank you for reaching us.

Could you please try to provision the project again? Please share more info on which template you tried.

Thanks

**Comment by greatglp007** [comment]
My project name ASK_NB_DEMO, Template I tried to download is Azure Kubernetes Services. But what I am more interested to learn how to get MyHealth.AKS.Build extension or module.
If you can help me I will really appreciated.

***@***.***D73567.07B699B0]

Geirman Prostov
Azure Architect, Cloud Consulting
o: 630.944.22.08
m: 425.749.8463
e: ***@***.******@***.***>
Ensono.com<https://www.ensono.com/>

[Ensono]
[in]<https://www.linkedin.com/company/ensono/>

[Tw]<https://twitter.com/ensonoit>

[FB]<https://www.facebook.com/EnsonoIT/>

**Comment by aksh-h** [comment]
Thank you for showing interest, you can consume any template and learn new modules. Here is our [labs](https://azuredevopslabs.com/) content.

Let us know if you need any help.

Thanks!!
