### ISSUE TITLE
Failure To Import YAML Pipelines

### ISSUE THREAD

**Issue by mindingdata** [microsoft/AzureDevOpsDemoGenerator#424]
I am attempting to clone an existing project in Azure Devops. This project has a repository that contains a YAML pipeline, and the pipeline has been created pointing to that YAML file. The YAML file is not in the root of the project (Instead in a build folder), but the build in the source project works fine. 

When I create a template from this existing project, I can open the zip and check the BuildDefinition JSON. Here I can see this : 

```
"repository": {
    "properties": {
      "cloneUrl": "https://mycompany@dev.azure.com/mycompany/Client%20Template/_git/ProjectTemplate",
      "fullName": "ProjectTemplate",
      "defaultBranch": "refs/heads/develop",
      "isFork": "False",
      "safeRepository": "e12049d1-a409-4338-be23-047638540b99",
      "reportBuildStatus": "true"
    },
    "id": "e12049d1-a409-4338-be23-047638540b99",
    "type": "TfsGit",
    "name": "ProjectTemplate",
    "url": "https://$Organization$@dev.azure.com/$Organization$/$ProjectName$/_git/ProjectTemplate",
    "defaultBranch": "refs/heads/develop",
    "clean": null,
    "checkoutSubmodules": false
  }
```

Notice how the cloneURL for the repo is still pointing to the old repo (Whereas for example the URL lower has been updated).

When I try and import this I get : 

> Error while creating build definition: To get sources from a different team project, on the Options tab you must set the build job authorization scope to ‘Project collection’ and ensure that the 'Limit job authorization scope to current project' pipeline setting is disabled.

Which is expected because the CloneURL is wrong. By the looks of it, all we need to do is update the cloneURL to also match the URL with the tokens, and we should be good to go!

[AB#3656](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3656)

**Comment by aksh-h** [comment]
Hi @mindingdata Thank you for pointing this issue. Our team will look into this.

**Comment by aksh-h** [comment]
Update!!

Team is working on it, will release the hotfix soon.

Thanks,

**Comment by aksh-h** [comment]
#426
