### ISSUE TITLE
Demo Migration Project : System.Threading. Error

### ISSUE THREAD

**Issue by Hamza2404** [microsoft/AzureDevOpsDemoGenerator#431]
I am not been able to create the required environement for this demo project in Azure Devops.
Below are the the diagnostics logs: 

> The SSL connection could not be established !

`System.Threading.Tasks.Task``1.GetResultCore(Boolean waitCompletionNotification) at AzureDevOpsAPI.QueriesAndWidgets.Queries.CreateQuery(String project, String json) in D:\a\1\s\src\AzureDevOpsRestApi\QueriesAndWidgets\Queries.cs:line 77`

[AB#3659](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3659)

**Comment by aksh-h** [comment]
Hi @Hamza2404 Thank you for reaching us.

This could be an intermittent issue. Could you please try it again and let us know your updates?

Thanks!!
