### ISSUE TITLE
Environments Are Not Exported/Imported

### ISSUE THREAD

**Issue by mindingdata** [microsoft/AzureDevOpsDemoGenerator#433]
We are using the AzureDevOpsDemoGenerator to "clone" a base project. As part of this base project, we have environments (Dev, Test, and Production), which are also referenced in the YAML builds. 

Are these able to be exported/imported?

[AB#3661](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3661)

**Comment by Damovisa** [comment]
If there's an environment defined in the build YAML, but it doesn't already exist, an empty environment will be created on the first run.

Are there other properties of that environment you need to be part of the template, or will this work for your purposes?

**Comment by mindingdata** [comment]
Huh.. You know.. This actually works better.. The issue is that if I manually create Environments, they are created with Project Administrators having *reader* access only. It drives me insane because if a developer creates an environment, then others (other than the org admin) cannot edit the Environment, even if they are the Project Administrator. 

![image](https://user-images.githubusercontent.com/1021021/116501814-e7927d80-a905-11eb-9cdb-a6bc836ce084.png)

But it would appear if the Environment is auto created, it adds the Project Administrator as an admin : 

![image](https://user-images.githubusercontent.com/1021021/116501861-0a249680-a906-11eb-8774-77d18627084e.png)

Really really weird. But I guess that works! So more of a feature request : 

- Still I think permissions may want to be set on the base project. e.g. It looks like it adds whoever first ran the Build as the Environment Admin, which we may not always want. 
- Really, it's about us having the same approval gates across projects. If we manually create it, then.. we have to manually create it. if we wait for the first run of the YAML, then it means atleast once we have to deploy to Test/UAT/Prod without a gate, so it can create the Environment, then we can add the gate. 

But, less of an issue now that it auto creates the environments correctly.
