### ISSUE TITLE
Not able to 'select organisation' when trying to login for the first time

### ISSUE THREAD

**Issue by MaxiPalle** [microsoft/AzureDevOpsDemoGenerator#436]
![image](https://user-images.githubusercontent.com/19306466/117150745-b825ba00-adb8-11eb-9688-492f6973b62f.png)

I'm logged in as the owner of the DevOps organisation.

[AB#3664](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3664)

**Comment by aksh-h** [comment]
Hi @MaxiPalle Thank you for reaching us.

Looks like you have logged in into different active directory where you don't have any organizations to list.
This thread might help you #353.

Thanks.

**Comment by MaxiPalle** [comment]
Nope. This is definitely not the case. I'm using an account with the same UPN for my work account (O365 work account, logged in with) and a demo account (Microsoft account, just used for browser and VS code sessions). When starting the AzureDevOpsDemoGenerator in a browser session of the demo account, AzureDevOpsDemoGenerator recognizes the right user and tenant (to be seen in upper right corner).
The problem is that AzureDevOpsDemoGenerator tries to retrieve the organization from the logged-in account (O365 work account), where I don't have a VS Code account and corresponding organisations.
