### ISSUE TITLE
Love the Demo Generator!

### ISSUE THREAD

**Issue by LosAngeles1979** [microsoft/AzureDevOpsDemoGenerator#446]
Using it to study the devops walkthroughs at https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject , THANKS, all of this is very helpful.!  😁

[AB#3682](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3682)

**Comment by aksh-h** [comment]
Thank you so much for your feedback!! 😊
