### ISSUE TITLE
insufficient permissions

### ISSUE THREAD

**Issue by ianhaymaxgeo** [microsoft/AzureDevOpsDemoGenerator#447]
TF50309: The following account does not have sufficient permissions to complete the operation: Ian Hay. The following permissions are needed to perform this operation: Create new projects.

This is supposed to be a test environment, why do I not have access?

[AB#3683](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3683)

**Comment by aksh-h** [comment]
Hello @ianhaymaxgeo Thank you for reaching us.
Hope this thread might help you #319 

Thanks

**Comment by PriyaTsl** [comment]
[ERROR] agent: Failed starting core plugin: error="failed configuring core: organization does not have permission for request forwarding agent: Shutting down Graceful shutdown complete
