### ISSUE TITLE
Docker pipline

### ISSUE THREAD

**Issue by pped1929** [microsoft/AzureDevOpsDemoGenerator#456]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '6975e2d1-96d3-4afc-8a41-498b5d34ea19'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Task1'.) A task is missing. The pipeline references a task called '6975e2d1-96d3-4afc-8a41-498b5d34ea19'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Task2'.)

[AB#3700](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3700)

**Comment by aksh-h** [comment]
Our team investigated this and found no issue with the dicker pipeline.  Request you to retry and let us know.

Thank you!
