### ISSUE TITLE
Preserve query parameters on redirect to new domain name

### ISSUE THREAD

**Issue by tpetchel** [microsoft/AzureDevOpsDemoGenerator#457]
It looks like the domain name has recently changed to azuredevopsdemogenerator-core.azurewebsites.net.

On Microsoft Learn, we have links to specific templates. For example:
https://azuredevopsdemogenerator.azurewebsites.net/?name=scan-open-source

When the redirect happens, any query parameters appear to get dropped. I either get the last template I chose or I get SmartHotel360:

![image](https://user-images.githubusercontent.com/7142397/119867817-28fd5500-bed3-11eb-8026-b39791cbb966.png)

I can update the Learn content to point to the new domain, e.g.:
https://azuredevopsdemogenerator-core.azurewebsites.net/?name=scan-open-source

But I wanted to point this out in case others had inbound links that might break in the same way. Is there any way to preserve the query parameter on redirect?

[AB#3701](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3701)

**Comment by aksh-h** [comment]
Hello @tpetchel, Thank you for pointing this. We will figure out an ideal solution for redirecting with parameters.

Meanwhile, we have enabled A|B testing with .Net core implementation, routing 10-20% of real-time traffic to the [-core](https://azuredevopsdemogenerator-core.azurewebsites.net/?name=scan-open-source) site and this will be active only for a limited period of time.

**Comment by aksh-h** [comment]
Hi @tpetchel I have raised a question on community, kindly track [here](https://docs.microsoft.com/en-us/answers/questions/417459/routing-to-a-web-app-slot-with-query-parameters.html).

Thanks!!
