### ISSUE TITLE
While building template getting error "Error occured while exporting Board Columns: TF400497: The backlog iteration path that you specified is no longer valid"

### ISSUE THREAD

**Issue by rajivkumarmishra** [microsoft/AzureDevOpsDemoGenerator#458]
Hi Team,

I am trying to build my own template using azuredevopsdemogenerator. after analyzing when i click on generate artifacts, getting below error.
![Azuredevopsdemogenerator error](https://user-images.githubusercontent.com/35929792/120317137-e3d68a00-c2fb-11eb-91e5-3b2fe73d1636.PNG)

Error occured while exporting Board Columns: TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Board Rows: TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Fields: TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Styles: TF400497: The backlog iteration path that you specified is no longer valid.

[AB#3702](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3702)

**Comment by rajivkumarmishra** [comment]
Hi Team,

There was some setting issue at my devops project and i fixed it. We can close this request.

Thanks
Rajiv

**Comment by thomasiverson** [comment]
I am getting the same error, What did you do to fix this?

error below

Error occured while exporting Board Columns: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Board Rows: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Fields: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Styles: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Board Columns: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Board Rows: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Fields: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Styles: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Board Columns: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Board Rows: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Fields: 
TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Styles: 
TF400497: The backlog iteration path that you specified is no longer valid.
