### ISSUE TITLE
Unable to create "Tailwind Traders" project 

### ISSUE THREAD

**Issue by az400-hassan** [microsoft/AzureDevOpsDemoGenerator#460]
TF200019: The following project already exists on the Azure DevOps Server: Tailwind Traders. You cannot create a new project with the same name as an existing project. Provide a different name.

[AB#3706](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3706)

**Comment by aksh-h** [comment]
Hi @az400-hassan 
This looks like the project with the same name is already exists in the selected organization. Please select a different organization or provide a different name for the project and try again.

Thanks!!
