### ISSUE TITLE
The Docker template depends on a deprecated plugin (Docker Integration)

### ISSUE THREAD

**Issue by sheltoncj** [microsoft/AzureDevOpsDemoGenerator#461]
The Docket template depends on the no longer available Docker Integration plugin which has been replaced by built in functionality of Visual Studio. It should probably be updated to no longer list the dependency and add any needed instruction changes.

[AB#3707](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3707)

**Comment by aksh-h** [comment]
Hi, @sheltoncj Thank you for reaching us. We will look into this.
