### ISSUE TITLE
traders backend pipeline is failing after resource group creation 

### ISSUE THREAD

**Issue by sameeranamarnath** [microsoft/AzureDevOpsDemoGenerator#463]
traders backend pipeline is failing after resource group creation in the pipeline,
Error Log:
Starting: Azure Deployment:Create Or Update Resource Group action on TailwindTradersBackend
==============================================================================
Task         : Azure resource group deployment
Description  : Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
Version      : 2.184.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
==============================================================================
##[warning]Resource file has already set to: /home/vsts/work/_tasks/AzureResourceGroupDeployment_94a74903-f93f-4075-884f-dc11f34058b4/2.184.1/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
Checking if the following resource group exists: TailwindTradersBackend.
Resource group exists: true.
Creating deployment parameters.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Error: Could not find any file matching the template file pattern
Finishing: Azure Deployment:Create Or Update Resource Group action on TailwindTradersBackend

[AB#3712](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3712)

**Comment by aksh-h** [comment]
Hi, @sameeranamarnath Thank you for posting here. We will look into this.

**Comment by aksh-h** [comment]
It appears to the change in source code, file and folder location. The pipeline needs to be reconfigured. We will update ASAP.

**Comment by aksh-h** [comment]
Update.
Waiting for support from the backend team. We will be able to fix it once we get enhanced support.
Thanks!!

**Comment by aksh-h** [comment]
Please refer to the pipelines on GitHub - [TailwindTraders-Backend](https://github.com/microsoft/TailwindTraders-Backend/tree/main/Pipeline) and [TailwindTraders-Website](https://github.com/microsoft/TailwindTraders-Website/tree/main/.github/workflows)
