### ISSUE TITLE
Template Builder error

### ISSUE THREAD

**Issue by jialiu77845** [microsoft/AzureDevOpsDemoGenerator#464]
Greetings, I'm trying to move code stored in Azure DevOps by our developer from old organization to our new organization. I tried Azure DevOps Demo Generator to export the template. Here's error:
"We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise an issue with the error logs here and we will try to help you.
Click on View Diagnostics button to share logs with us."
The View Diagnostics shows:
"VS403474: You requested 459 work items which exceeds the limit of 200"
So, the questions are:
1. I assume the zipped json output is incomplete?
2. Is there a way to increase the number of work items and how? (Just saw some old posts regarding the same issue. Has this being resolved?)
Thanks!

[AB#3714](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3714)

**Comment by aksh-h** [comment]
Hi @jialiu77845 Thank you for reaching us.

Demo generator is used to set up sample production grade environments. The issue clearly showing the selected project has more than 200 work items (459). There is a limitation from [Azure DevOps REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/get%20work%20items%20batch?view=azure-devops-rest-6.0), which returns only 200 work items of each type.

So the zipped output won't be included the work item which is more than 200. Using the dowinloaded zip file you can still upload and get the repository created in another organization- project. Make sure that you are having necessary permission in both organization to perform this.

In the meantime, you can refer the following document to [import repository](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops) to another project.
