### ISSUE TITLE
Task: VS403474: You requested 459 work items which exceeds the limit of 200

### ISSUE THREAD

**Issue by gidziu** [microsoft/AzureDevOpsDemoGenerator#466]
The error VS403474 keeps popping up for the last two years. Has anyone resolved it?

[AB#3718](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3718)

**Comment by aksh-h** [comment]
Hi @gidziu
Could you please check, the selected organization has more than 200 work items of any type? Is this error occurring for every organization you selected?

Meantime, APIs will not support fetching more than 200 work items of a type at once.
Let me know if this is not the case, we will figure it out. We might need your help to reproduce this behavior?

Thanks!

**Comment by aksh-h** [comment]
Since there is no response, we are closing this thread,
