### ISSUE TITLE
Error while creating Tailwind Traders 

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/AzureDevOpsDemoGenerator#469]
Error while creating wiki: TF401019: The Git repository with name or identifier 7B61FD6E-057F-4D7F-9346-7E642BFA6A8A does not exist or you do not have permissions for the operation you are attempting.

[AB#3723](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3723)

**Comment by aksh-h** [comment]
This looks like a permission issue. Make sure that you have the necessary permission and please try again.
