### ISSUE TITLE
Issue when forking towards to my GitHub account

### ISSUE THREAD

**Issue by Ventilios** [microsoft/AzureDevOpsDemoGenerator#470]
I'm currently working on the DevOps challenge and part of that is using the DevOps Demo generator in several of the exercises. Until last week everything was working fine, but since this weekend I'm getting the following error on forking the GitHub project: 
_Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository._

After trying all several different things: new DevOps org, remove/recreate pipeline permissions, wait for a while, removing spaces from names. Also asked a colleague that's part of the same company, this colleague is hitting the same error.
Only 5 days left on the challenge, why is this happening and how can I resolve this?

Exercise I'm currently wanting to start (having the same issues with other exercises in the learning path): https://docs.microsoft.com/en-us/learn/modules/create-release-pipeline/4-set-up-environment 
Within that exercise I'm following the link towards the generator, select a name, place a checkmark for the GitHub Authorization and select Authorize. When authorizing it pops up a small window and that closes after a couple of seconds. Next step is creating the project; Azure DevOps are created successfully and the fork-step results in the above error. 

[AB#3724](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3724)

**Comment by aksh-h** [comment]
Hi, @Ventilios Thank you for reaching us. We understand your concern. However we unable to reporduce this behavior with any of our GitHub logins.
As of now, we can suggest you an alternative way, please fork the [repository](https://github.com/microsoftdocs/mslearn-tailspin-spacegame-web-deploy.git) to your GitHub account, and continue with your learning modules. 

We will inspect this behavior.

Thank you for your patience!!

**Comment by aksh-h** [comment]
Updates!!

This error can be seen only if the authorized GitHub account protected by SAML enforcement. This may occur If you're log in to GitHub using corporate Id.

We mentioned a workaround in the Azure DevOps Demo Generator portal, once you select the template you will notice a information box at the bottom. Please fork the repository manually from the link provided and link it to the pipeline. Then proceed with the documentation.

![image](https://user-images.githubusercontent.com/38463158/132313033-22ca8ea1-5c03-4f3f-929b-814c8cf6dd6f.png)
