### ISSUE TITLE
Cannot run Azure DevOps Demo Generator with GitHub forking

### ISSUE THREAD

**Issue by gbelenky** [microsoft/AzureDevOpsDemoGenerator#471]
I run this [tutorial](https://docs.microsoft.com/en-us/learn/modules/create-release-pipeline/4-set-up-environment) and receive "Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository."

I am admin in both my Azure DevOps organization (my corp account) and also in GitHub (my Microsoft account). Please help and also re-open [this issue](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/387) 

[AB#3725](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3725)

**Comment by aksh-h** [comment]
Hi, @gbelenky Thank you for reaching us. We understand there is an issue with the forking repo and creating a pipeline.
Could you please help me to debug this? If yes, please write an [email](mailto:akshay.hosur@ecanarys.com)

**Comment by aksh-h** [comment]
@gbelenky could you please login to [this](https://azuredevopsdemogenerator-staging.azurewebsites.net/) site and try? If the same issue persists, please let us know.

**Comment by gbelenky** [comment]
Thanks Akshay. Checking….

**Comment by gbelenky** [comment]
This worked - I had to install additional add-ons to my organization. The GitHub fork was also created
![templatesuccess](https://user-images.githubusercontent.com/26817885/124607550-40364780-de6e-11eb-956e-d184ea51d542.jpg)

**Comment by aksh-h** [comment]
Hey, Thanks for confirming. Could you please mention which add-on you have installed? Let other users know about it.

**Comment by gbelenky** [comment]
You can see the added plugins in the image above. But that worked only for sample you provided above. As I went back to another [template](https://azuredevopsdemogenerator.azurewebsites.net/?x-ms-routing-name=self&name=create-multi-stage-pipeline), it did not work

**Comment by gbelenky** [comment]
I have a workaround for the training forking the github repo manually, but we need to update the documentation explaining the manual path or to fix the forking issue in the template

**Comment by aksh-h** [comment]
We unable to reproduce this behavior, could you please spend your valuable time assisting me to debug this issue locally?

**Comment by gbelenky** [comment]
Happy to assist you, @aksh-h ! How do we connect?

**Comment by aksh-h** [comment]
Can we connect over Microsoft Team? Please [email](mailto:akshay.hosur@ecanarys.com) me.
