### ISSUE TITLE
Lab15 : Deploying Docker containers to Azure App Server web apps 

### ISSUE THREAD

**Issue by VBM001** [microsoft/AzureDevOpsDemoGenerator#483]
Hi Team,

I am performing lab 15  and pipeline runs indefinitely for run services tasks. Please advise .

Starting: Run services
==============================================================================
Task         : Docker Compose
Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
Version      : 0.183.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-compose-tsg
==============================================================================
/usr/local/bin/docker-compose -f /home/vsts/work/1/s/docker-compose.ci.build.yml -f /home/vsts/agents/2.189.0/.docker-compose.1626991615519.yml -p Docker up --build --abort-on-container-exit
Creating network "docker_default" with the default driver
Pulling ci-build (microsoft/aspnetcore-build:1.0-2.0)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

[AB#3739](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3739)

**Comment by aksh-h** [comment]
Hi @VBM001 
Thank you for reaching us. Could you please let us know which lab you're trying? We will try to reproduce and get back to you.

Thanks!

**Comment by aksh-h** [comment]
Please provide the related information to investigate the issue.

Thanks

**Comment by VBM001** [comment]
Hi Akshay,
I am facing the same issue for both of the labs below.

Module 15 - Lab 1 - Deploying Docker containers to Azure App Service web
apps
Module 16 - Lab 1 - Deploying a multi-container application to Azure
Kubernetes Services

-Vishnu

**Comment by aksh-h** [comment]
Thank you for sharing the details.
Could you please share the related links? We will take the necessary action.

**Comment by aksh-h** [comment]
This looks like a problem with the image ```microsoft/aspnetcore-build:1.0-2.0```. Could you please use the following image ```sriramdasbalaji/aspnetcore1.0:1.0.4``` in ```Docker``` and ```docker-compose.ci.build.yml``` files.

Let us know your updates.

Thanks

**Comment by VBM001** [comment]
HI Akshay,
PFB.
https://esi.learnondemand.net
Module 15 - Lab 1 - Deploying Docker containers to Azure App Service web
apps
Module 16 - Lab 1 - Deploying a multi-container application to Azure
Kubernetes Services

-Vishnu

**Comment by VBM001** [comment]
Hi Akshay,

I have raised to grant free parallelism . Once approved , I will try run
and keep you posted.

Error:
No hosted parallelism has been purchased or granted. To request a free
parallelism grant, please fill out the following form
https://aka.ms/azpipelines-parallelism-request

**Comment by aksh-h** [comment]
by replacing the docker image for aspnetcore, you should be able to run the pipeline.
