### ISSUE TITLE
Item Limit on Export

### ISSUE THREAD

**Issue by sperniciaro** [microsoft/AzureDevOpsDemoGenerator#485]
Hello, my colleague and I are trying to export a project for a client. However, we are running in to a query error that says we exceed the limit of 200. I have attached an image to show the errors. Is there was a way to increase the limit? 
![ImportLimitError](https://user-images.githubusercontent.com/54368778/127335460-75fceafb-623c-4faf-b913-34bb8a5287a2.png)

[AB#3741](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3741)

**Comment by aksh-h** [comment]
Hi @sperniciaro 
Thank you for reaching us.
The restriction has been imposed from the Azure DevOps REST API, which returns 200 work items at a time. We are sorry to say, the tool is not designed to read all work items from the selected project.

Thanks!!
