### ISSUE TITLE
Error while creating release definition: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by chelorope** [microsoft/AzureDevOpsDemoGenerator#490]
Error while creating release definition: Index was outside the bounds of the array.

When running: 
https://github.com/pascalvanderheiden/multi-container-wordpress-azure/blob/master/devops/Multi-container%20WordPress%20on%20Azure.zip

[AB#3747](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3747)

**Comment by obtech-ca** [comment]
I am seeing the same issue. It gets to the part of "Board-Column, Swimlane, Styles update" and then errors out with the error the op stated in the title. See screenshots for clarity.

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/20389228/def91104-1af5-4ad2-b737-291a525c62d2)

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/20389228/31a5044e-403c-45db-9d66-385529f153bb)
