### ISSUE TITLE
Erro while creating the project with the following error code:VS403119

### ISSUE THREAD

**Issue by boblechat** [microsoft/AzureDevOpsDemoGenerator#495]
Hi,
I got the following message trying to create an Azure Kubernetes Service demo project: _VS403119: You cannot add a team project with process Scrum as it is disabled. Either choose a different process, or enable process Scrum and try again._

Indeed, for testing purposes I disabled this template.  
It's a quick fix but I think the generator should either:
- use the default template instead of forcing one
- let the user choose when creating the project

[AB#3755](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3755)

**Comment by aksh-h** [comment]
Hi @boblechat Thank you for reaching us.

The defined templates demonstrates certain patterns and follow defined process templates, please give it a try by enabling the scrum process template or select different organization.

Thanks!
