### ISSUE TITLE
Problems with creating a project w/a template (forking)

### ISSUE THREAD

**Issue by jenellea** [microsoft/AzureDevOpsDemoGenerator#502]
Problems with the forking a template using  MS learn  UID learn.azdo.deploy-docker (Unit 3).

Is there an internal (MSFT) organization that will work with this exercise?

2 Typos in UI s/b 3 dot ellipsis see https://www.thepunctuationguide.com/ellipses.html and see image
![image](https://user-images.githubusercontent.com/1796557/131724855-99f2a235-bfd9-49ea-9b81-d0651b1619b5.png)
Scrollable dialog box shows no indication it is scrollable. message cut off.
![image](https://user-images.githubusercontent.com/1796557/131725069-21e2db65-0c2b-4753-997f-104d0b73a6de.png)

Also, Sorry... error message is innocuously stashed in a sidebar, is this a new MSFT paradigm? 

[AB#3781](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3781)

**Comment by aksh-h** [comment]
Hi, @jenellea
Thank you for reaching us. This error can be seen only if the authorized GitHub account protected by SAML enforcement. This may occur If you're log in to GitHub using corporate Id.

We mentioned a workaround in the Azure DevOps Demo Generator portal, once you select the template you will notice a information box at the bottom. Please fork the repository manually from the link provided and link it to the pipeline. Then proceed with the documentation.

![image](https://user-images.githubusercontent.com/38463158/132311778-2ee59342-2c0f-48ea-a57f-611452a95102.png)
