### ISSUE TITLE
Training Builds Failing

### ISSUE THREAD

**Issue by dave-cochran** [microsoft/AzureDevOpsDemoGenerator#503]
No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form

I've filled out the form, but no response yet. 

[AB#3784](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3784)

**Comment by aksh-h** [comment]
Hi, @dave-cochran
Thank you for reaching us. Could you please elaborate the problem?
