### ISSUE TITLE
Azure Demo DevOps Generator, when using LaunchDarkly template, in the resulting DevOps project's the repo is empty

### ISSUE THREAD

**Issue by pluraltouch** [microsoft/AzureDevOpsDemoGenerator#508]
Azure Demo DevOps Generator, when using LaunchDarkly template, in the resulting DevOps project's the repo is empty. (there is only one repo in the project, called LaunchDarkly, which is empty)

I am successfully generating many projects to my DevOps organization with Azure Demo DevOps Generator, many comes with filled repositories. However when using the LaunchDarkly template, the resulting project's repo is empty.

[AB#3790](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3790)

**Comment by aksh-h** [comment]
Hi, @pluraltouch Thank you for reaching us. We will check this and get back to you,
