### ISSUE TITLE
How to request for the authorization for the DevOps ?

### ISSUE THREAD

**Issue by Kimmytsai1120** [microsoft/AzureDevOpsDemoGenerator#510]
TF50309: The following account does not have sufficient permissions to complete the operation: xxxxxx. The following permissions are needed to perform this operation: Create new projects.

**Comment by aksh-h** [comment]
Hi @Kimmytsai1120 
Thanks for reaching us. For the selected organization you don't have create project permission, please request access from your organization owner/admin/project collection administrator.
