### ISSUE TITLE
Ubuntu 16 hosted agent deprecated in Azure DevOps

### ISSUE THREAD

**Issue by yashints** [microsoft/AzureDevOpsDemoGenerator#521]
Hey team,

Since ubuntu 16 is deprecated and not available anymore, could you please update it to 18, 20, or simply use the latest tag instead of a version?

<img width="959" alt="hosted agents" src="https://user-images.githubusercontent.com/13609680/138360407-be3b40c2-678c-4a3b-b386-82a987be4b84.png">

I was going to raise a PR, but didn't know how many places should be updated

**Comment by aksh-h** [comment]
Fixed and release agent specification
