### ISSUE TITLE
Template generator does not include Project iterations in export

### ISSUE THREAD

**Issue by stevns** [microsoft/AzureDevOpsDemoGenerator#527]
When exporting a template via the tool, iterations on project and teams level are missing.
Can this be added?

**Comment by aksh-h** [comment]
Hi @stevns 
Thank you for reaching us, the tool is designed to generate or populate the sample environments with predefined data. It has some [limitations](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)
