### ISSUE TITLE
Python-CD' already exists

### ISSUE THREAD

**Issue by huzaifa-dot** [microsoft/AzureDevOpsDemoGenerator#528]
I am getting error while using the **python template** to create project and pipeline using azure DevOps demo generator. 
"Error while creating release definition: VS402934: A release pipeline with the name 'Python-CD' already exists. Specify a different name and try again."

**Comment by aksh-h** [comment]
Hi @huzaifa-dot 
We will inspect this from our end, if anything from the predefined templated, we will fix it soon. 

Thanks

**Comment by aksh-h** [comment]
Identified the issue and resolved

**Comment by huzaifa-dot** [comment]
Thanks, @aksh-h  for the quick response, identifying the issue and resolving it.

Have a good day!
Thanks-you
