### ISSUE TITLE
Templates affected by Windows-2016 hosted agent removal

### ISSUE THREAD

**Issue by unaihuete93** [microsoft/AzureDevOpsDemoGenerator#530]
Hello,

As part of the **AZ-400: Designing and Implementing Microsoft DevOps Solutions** Microsoft Trainer community we identified quite a big issue we are going to face by March 2022. Windows-2016 (the ones using VS2017) will be removed, affecting many of the templates used on your tool: https://github.com/actions/virtual-environments/issues/4312

Our AZ-400 completely relies on the Demo Generator, and we identified that 80% of labs will be affected by the change. Here I provide a list of templates that we identified will be affected:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-GB style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Demo Generator Template (Repo) | Used Repo Source   (under src/VSTSDemoBuilder/Temaplates/NAME/ImportSourceCode)
-- | --
PartsUnlimited | https://vstsdemodata.visualstudio.com/_git/PartsUnlimited
ReleaseGates | https://vstsdemodata.visualstudio.com/Release%20Gates/_git/PartsUnlimited (different)
PartsUnlimed-YAML | https://dev.azure.com/vstsdemodata/PartsUnlimited_YAML/_git/PartsUnlimited (different)
Selenium | https://vstsdemodata.visualstudio.com/_git/Selenium
LaunchDarkly     (PartsUnlimited) | https://github.com/hsachinraj/PartsUnlimited.git
Terraform | https://dev.azure.com/vstsdemodata/_git/Terraform
Docker | https://vstsdemodata.visualstudio.com/_git/Docker
WhiteSource Bolt | https://vstsdemodata.visualstudio.com/_git/WhiteSource%20Bolt

</div>

</body>

</html>

**Comment by unaihuete93** [comment]
In our case, most of the labs for the AZ-400 course (https://aka.ms/az400labs) depend on the **PartsUnlimited** repo/template. Are you planning on updating the repository to be compatible with VS2019? Lets us know if we can help.

**Comment by prpurand** [comment]
This is a very important change that needs to go on time. Many of our AZ 400 trainers are seeking updates on this issue. It would be good if the Demo Generator Project team can consider this as priority to fix the issue.

**Comment by aksh-h** [comment]
Hi @unaihuete93, thank you for highlighting this. We will consider this on priority.

**Comment by unaihuete93** [comment]
let us know if we can help :)

**Comment by unaihuete93** [comment]
any update? :)

**Comment by aksh-h** [comment]
@unaihuete93 we verified all the templates, wherever it is possible we have changed the agent to windows-2019, most of them are in release pipelines. If we change the agent from VS2017 to other,  build pipelines are failing due to the legacy code. It is unable to find the required pacakges. Eg: pipelines using following source code - Parts Unlimted, My Health Clinic etc.

Kindly let us know if you can help with this.
Thanks!!

**Comment by unaihuete93** [comment]
Do you know who is the owner for the https://vstsdemodata.visualstudio.com/ ADO org?  Partsunlimited repo should be updated to VS2019 (or replaced by another solution compatible with VS2019), the code has some dependencies related to VS2017 (not an expert in .net myself) which makes it fail when building with VS2019.

We need to identify the owner of the ADO org and define if we will update the solution or replace it. I still need to try some other PartsUnlimited repositories found on GitHub to see if they work with VS2019 and the windows-2019 agents.

**Comment by aksh-h** [comment]
Working on it. Trying to fix the possible repositories and build pipelines/agents. Keep you posted.

**Comment by aksh-h** [comment]
Apart from the selenium, all the pipelines mentioned above are working on windows-2019.

**Comment by prpurand** [comment]
This is good news. Pls let us know how you went about changing the project partsunlimited? Would be a good learning to be aware of..

**Comment by unaihuete93** [comment]
wow, did you change the PartsUnlimited repo? or modified pipelines? let us know if we can try those proposed changes

**Comment by aksh-h** [comment]
The PartsUnlimited repository had a live dependency validation project. Since we are not using live dependency validation and it is not enabled in VS2019 by default, the build was failing. We have removed the obsolete project and dependencies from the source repo.
