### ISSUE TITLE
Key Vault template: CD pipeline does not work/render

### ISSUE THREAD

**Issue by unaihuete93** [microsoft/AzureDevOpsDemoGenerator#533]
Hello,

When using the Key Vault Template and trying to **Edit** the CD pipeline, the web browser is not able to render the editing view of the existing pipeline::
![image](https://user-images.githubusercontent.com/64772417/141797586-15b4cb20-6458-47a5-ac3e-d17cadbbfe50.png)
The workaround we found is downloading the JSON file, deleting the **Artifacts [] section between lines 293 and 343** and reimporting the pipeline. Looks like the JSON used for the Release pipeline was updated recently: https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/src/VstsDemoBuilder/Templates/Keyvault/ReleaseDefinitions/SmartHotel-CouponManagement-CD.json

**Comment by raphasi** [comment]
We have same issue :(

**Comment by aksh-h** [comment]
The reported issue has been resolved. Thank you!!

**Comment by unaihuete93** [comment]
![image](https://user-images.githubusercontent.com/64772417/142218157-ef2aa390-2c5b-498d-aaa5-97ee65c3691f.png)
editing works now but it is a bit confusing: release artifact connects to the "classic" CI pipeline but it has **-yaml** on the alias for the artifact

**Comment by aksh-h** [comment]
Good catch. We will address this soon.

**Comment by aksh-h** [comment]
![image](https://user-images.githubusercontent.com/38463158/142224152-54a3c704-4bdb-442d-bdf9-63fdbdbb8ed7.png)

How about this? If anything kindly let us know.

**Comment by unaihuete93** [comment]
looks good!
