### ISSUE TITLE
Devops Demo Generator template - Azure Key Vault

### ISSUE THREAD

**Issue by raphasi** [microsoft/AzureDevOpsDemoGenerator#534]
Hi, good afternoon everyone. I'm using the Devops Demo Generator template (Azure Key Vault) for an Az-400 lab (Module 7 from Github). After deploying the project, when I go to Pipeline/Release and try to edit the release present in the project (SmartHotel-CouponManagement-CD), it doesn't load any release editing screen. I've already tested it in more than one organization, with different users, physical machines, VMs on Azure and the same problem persists.

**Comment by unaihuete93** [comment]
same as https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/533 ;)

**Comment by aksh-h** [comment]
Hi, @raphasi Thank you for pointing this. We have identified and resolved the issue.
