### ISSUE TITLE
Template Builder Export is missing information!

### ISSUE THREAD

**Issue by wd21sos** [microsoft/AzureDevOpsDemoGenerator#537]
When a project is exported with the Template Builder, some information is missing in the ZIP file. For instance the release definitions are quite empty in comparison when a single release is exported as a json file. I was wondering why when I import the project template the releases are not working. The release pipelines are created but inside the pipeline they are empty.

This is a very serious problem that information and dependencies are not included in the export. Mainly this problem is connected to pipelines or release pipelines.

Is there a fix for that?

Thanks

**Comment by aksh-h** [comment]
Hi @wd21sos 

Exporting and Importing pipelines dynamically is a very tedious task, the tool is designed its best to handle the pipelines.
This may happen only when 
1. The Build pipeline has been renamed and the new name is not reflected in the release pipeline.

Solution:
You can find the ```/ReleaseDefinitions/files.json```. if you edit the file you can see the name of your build pipeline in the release pipeline with ```$Old Build Pipeline Name$```
Replace this with ```$Correct Build Pipeline Name$``` from the source project. Try to import, this may resolve the problem.

2. The endpoint ids are not replaced

Identify the endpoint ids from``` /ReleaseDefinitions/files.json``` and remove it.
