### ISSUE TITLE
My Organization is not visible 

### ISSUE THREAD

**Issue by Indra7946** [microsoft/AzureDevOpsDemoGenerator#539]
Even though I have logged in to the Demo generator portal with my correct User Id, I am not able to my Organization in the Demo generator portal.
![image](https://user-images.githubusercontent.com/44440773/142836525-fdb739ff-ccc0-49d0-9ed7-0ac94864d779.png)

I have a Organization created with my user Id in dev.Azure.com.
![image](https://user-images.githubusercontent.com/44440773/142836786-3967a21a-5988-47a3-b6e3-7fe776276ec0.png)

Regards,
Indra.

**Comment by aksh-h** [comment]
Hi, @Indra7946 
Thank you for reaching us. Please refer to #353
