### ISSUE TITLE
Unable to load Organization

### ISSUE THREAD

**Issue by sokpara** [microsoft/AzureDevOpsDemoGenerator#540]
Hello All,
I am unable to use the Azure DevOps generator for the Microsoft CAF as my organization cannot load. Kindly advise.

See error below:

"Could not load your organizations. Please check if the logged in Id contains the Azure DevOps Organizations or change the directory in profile page and try again."

**Comment by aksh-h** [comment]
Hi, @sokpara 
Thank you for reaching us. Please refer to #353
