### ISSUE TITLE
Parts Unlimited Lab Missing TF Files

### ISSUE THREAD

**Issue by lust4boost** [microsoft/AzureDevOpsDemoGenerator#541]
Hi,

I'm trying to complete the Azure Devops lab for automating infrastructure [https://azuredevopslabs.com/labs/vstsextend/terraform/](url)  ,but this lab is missing the terraform branch needed to complete it. 

![Azure Devops - Pipeline Error](https://user-images.githubusercontent.com/46305083/143139902-afe813da-49d7-4a93-a0c3-bfa5d326a274.PNG)

**Comment by aksh-h** [comment]
Hi, @lust4boost 
Looks like you are having a different repository. Kindly try creating a new project - [Terraform](https://azuredevopsdemogenerator.azurewebsites.net/?name=terraform)

This is how the repository and branches looks
![image](https://user-images.githubusercontent.com/38463158/143385265-94c87c51-4031-4e45-8112-8f100ac4efc1.png)

Thanks!
