### ISSUE TITLE
Key Vault template: CD pipeline does not work

### ISSUE THREAD

**Issue by unaihuete93** [microsoft/AzureDevOpsDemoGenerator#542]
Issue related to #533 
![Screenshot 2021-11-24 155257](https://user-images.githubusercontent.com/64772417/143262227-f1bdf978-6a50-43da-bf53-64f2b5950a46.png)
Azur Deployment task references non existing Artifact

**Comment by aksh-h** [comment]
we have fixed this in another PR, please verify.

**Comment by unaihuete93** [comment]
looks like you fixed it right after reporting. Thanks!
