### ISSUE TITLE
Error on Template Builder

### ISSUE THREAD

**Issue by rub7** [microsoft/AzureDevOpsDemoGenerator#547]
I'm trying to build my own template and I got the following error. I think it's because the Release Pipelines.
If I import the result template the new project is created but Release Pipelines are not created. Neither the Variables.
Could you review it please?

`Could not find a part of the path 'D:\home\site\wwwroot\ExtractedTemplate\Plantilla Productos BC\ReleaseDefinitions\Publish to Sharepoint\ Teams.json'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost) at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost) at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost) at System.IO.File.WriteAllText(String path, String contents) at VstsDemoBuilder.Services.ExtractorService.GeneralizingGetReleaseDefinitions(ProjectConfigurations appConfig) in D:\a\1\s\src\VstsDemoBuilder\Services\ExtractorService.cs:line 1331`

**Comment by aksh-h** [comment]
We don't find any issue with the system, this could be intermittent. if the issue persists feel free to reopen or raise another issue.
