### ISSUE TITLE
AzureDevOps Demo Generator not working

### ISSUE THREAD

**Issue by luisdanielmesa** [microsoft/AzureDevOpsDemoGenerator#549]
It can't find my organizations...
![image](https://user-images.githubusercontent.com/1198204/144704581-98ec59b8-9801-49eb-a95e-95a4a16ab7c7.png)

I'm logged in and I can see them:
![image](https://user-images.githubusercontent.com/1198204/144704661-c4e11a89-b29e-4f4f-b864-3379338266dc.png)

Is there a way to make it work by manually entering some information?

**Comment by aksh-h** [comment]
Hi @luisdanielmesa

We don't see any such problems with the loading organization. If you still face the problem of finding the organizations, kindly sign out and sign in back to the Demo Generator. 
Also, try to switch your logged-in directory [here](https://aex.dev.azure.com/me?mkt=en-US#)  

[Documentation](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)

**Comment by luisdanielmesa** [comment]
Thanks! It seems it was having weird issues with the "onmicrosoft" account. I logged out and back in and it worked!
