### ISSUE TITLE
Cannot Create Project

### ISSUE THREAD

**Issue by mrkerusi** [microsoft/AzureDevOpsDemoGenerator#553]
Tried to create a project, no response when clicking view diagnostic, and create was failed

![image](https://user-images.githubusercontent.com/58578547/145363877-7d5daa2e-95cc-4148-be4e-5782d799b9cb.png)

**Comment by aksh-h** [comment]
Hi @mrkerusi 
Thank you for reaching us. Kindly provide more info on which template did you try.
Please make sure that you are having all necessary permission to create and manage the project,

Thanks!
