### ISSUE TITLE
Missing Git repository "Data-Quality-Service"

### ISSUE THREAD

**Issue by DanEvansBI** [microsoft/AzureDevOpsDemoGenerator#558]
Deployed this repo and received following error.   Did a search and appears this repo is no longer available.

Error while creating build definition: TF401019: The Git repository with name or identifier AE0E070C-BF70-4870-8F71-584D884CFCCB does not exist or you do not have permissions for the operation you are attempting. Error while creating build definition: TF401019: The Git repository with name or identifier Data-Quality-Service does not exist or you do not have permissions for the operation you are attempting.

Is there a way to get a detail log so we can "edit" the import and move past removed/depreciated repos?

**Comment by aksh-h** [comment]
Hi @DanEvansBI 
Could you please provide details on the template you used? Let us know if it is custom template you generated.

**Comment by DanEvansBI** [comment]
This was a custom template I created from an existing ADO project.   Not that familiar with the process on what components are extracted and looking for guidance on options to modify/debug the deployment.
