### ISSUE TITLE
Cannot create a project in azure devops demo generator

### ISSUE THREAD

**Issue by rahagarwal** [microsoft/AzureDevOpsDemoGenerator#563]
Hi,

I am using the the devops test labs and while trying to create a project, I am getting the error that I do not have permission to create a project.

Can you help?

**Comment by aksh-h** [comment]
Hi, @rahagarwal Thank you for reaching us.

If the issue is related to permission, please try to get full permission to create a project or create your own organization and try it.

Thanks
