### ISSUE TITLE
Can't provision project

### ISSUE THREAD

**Issue by altwohill** [microsoft/AzureDevOpsDemoGenerator#564]
I sign in, select my personal organisation that I'm an owner of, and select a template and give it a name.

When I click Create Project I see progress, followed by "Congratulations! Your project is successfully provisioned." 
But navigating to the project gives a 404 and the project does not appear to be created at all

**Comment by aksh-h** [comment]
Hi, @altwohill 
Looks like this is an intermittent issue. Could you please try it again and see if the same issue persists.

Thanks
