### ISSUE TITLE
Error while creating template through Azure devops Demo Generator

### ISSUE THREAD

**Issue by pragaInd** [microsoft/AzureDevOpsDemoGenerator#565]
Error occured while exporting Board Columns: TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Board Rows: TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Fields: TF400497: The backlog iteration path that you specified is no longer valid.Error occured while exporting Card Styles: TF400497: The backlog iteration path that you specified is no longer valid.

**Comment by aksh-h** [comment]
Hi @prlangad 
Thank you for reaching us. Kindly let us know which template you have tried. If it is a custom template, please share it with us.

Thanks

**Comment by pragaInd** [comment]
Please find attached the custom template that was used
[Phoenix (1).zip](https://github.com/microsoft/AzureDevOpsDemoGenerator/files/7894816/Phoenix.1.zip)
.

**Comment by pragaInd** [comment]
I am getting this blow error now : 

Error while creating query: TF51011: The specified area path does not exist. The error is caused by «'Phoenix_Trial2\CSG Disney'». 
Error while creating query: TF51011: The specified area path does not exist. The error is caused by «'Phoenix_Trial2\CSG Disney'».
Error while creating query: TF51011: The specified iteration path does not exist. The error is caused by «'Phoenix_Trial2\CSG Disney Japan'». 
Error while creating query: TF51011: The specified iteration path does not exist. The error is caused by «'Phoenix_Trial2\CSG Disney Japan'». 
Error while creating query: TF51011: The specified iteration path does not exist. The error is caused by «'Phoenix_Trial2\TalkTalk'».

PFA the custom template used ...  Please let me know what the issue is. It would be great if you can assist quickly as I have a demo coming up ! ! ! ! 

[Phoenix (1).zip](https://github.com/microsoft/AzureDevOpsDemoGenerator/files/7902562/Phoenix.1.zip)

**Comment by aksh-h** [comment]
Looks like this is about the Area or the Iteration path that you have in your queries. Demo Generator is not setting up the custom area paths or Iteration paths. Default setup might help you.

**Comment by pragaInd** [comment]
Hmm right .

1)  But, how do I change area path / iteration path in the zip file ?  
2) Are ADO dashboards not copied when we try to import ?

**Comment by aksh-h** [comment]
I tried the template shared here, I could see area paths created based on the Team Names. You can edit the area path / Iteration in /Dashboard/Queries location in your zip file.

Sorry to say, Dashboard won't be copied.

**Comment by pragaInd** [comment]
Thanks for your prompt response. Really appreciate it. 

Also, Why is ADO site not opening when connected to VPN ?

**Comment by aksh-h** [comment]
Sorry, no Idea about that. It could be some restrictions if it is an organization VPN.
