### ISSUE TITLE
Demo Generator Permissions Required - Create New Projects

### ISSUE THREAD

**Issue by Shgunter** [microsoft/AzureDevOpsDemoGenerator#568]
TF50309: The following account does not have sufficient permissions to complete the operation: Shawn Gunter (SP). The following permissions are needed to perform this operation: Create new projects.

Will be used for FastTrack for Azure customer delivery

**Comment by aksh-h** [comment]
Hi, @Shgunter Thank you for reaching us.

Please check with your organization admin to provide necessary permission to create a project, or you can create your own organization and try to provision the project.

Thanks
