### ISSUE TITLE
Areas and teams not imported with private template

### ISSUE THREAD

**Issue by paul-msft** [microsoft/AzureDevOpsDemoGenerator#569]
I created a standard Scrum project with a couple of teams and added a few work items and board columns, exported the artifacts, but when I use them to create a new project using the tool, none of the teams or area paths are created.

**Comment by aksh-h** [comment]
Hi @paul-msft 
Thank you for reaching us. If your template has the ```\Teams``` folder, you'll be able to see all the existing team names in the ``` Teams.json``` file. The Demo Generator will create only those teams and corresponding areas in the newly created project.

If the same issue persists you can share your zip file with us here.

Thanks

**Comment by paul-msft** [comment]
> Hi @paul-msft Thank you for reaching us. If your template has the `\Teams` folder, you'll be able to see all the existing team names in the ` Teams.json` file. The Demo Generator will create only those teams and corresponding areas in the newly created project.
> 
> If the same issue persists you can share your zip file with us here.
> 
> Thanks

Hi @aksh-h I've just tried again and the .zip file contains everything it should have by the looks of it ([Project1.zip](https://github.com/microsoft/AzureDevOpsDemoGenerator/files/7970029/Project1.zip)), but the tool doesn't create the teams or boards as they should be.

As a side note - The old demo generator tool does work with the same .zip file, it's just the new version that doesn't work.

Hope this helps!

**Comment by aksh-h** [comment]
@paul-msft Thanks for sharing the template, we will look into this.

**Comment by aksh-h** [comment]
@paul-msft
We have only one version of Demo Generator. Based on the analysis, your zip file has ```/Teams/Teams.json``` and it has ```P1 Team 1 and P1 Team 2``` as Teams. Respective team areas has been created in the project.  Other custom areas won't created as part of the new project, This has to be configured manually.

![image](https://user-images.githubusercontent.com/38463158/152089934-ea70f7a8-c8b7-4b73-a848-b9cb4a60ebb2.png)

Also, I could see work items created in the respective Team Areas
![image](https://user-images.githubusercontent.com/38463158/152090162-cdc8ff77-3f95-4f80-b922-d7b3a1254428.png)

Please let us know if you need any help from us.

**Comment by paul-msft** [comment]
> @paul-msft We have only one version of Demo Generator. Based on the analysis, your zip file has `/Teams/Teams.json` and it has `P1 Team 1 and P1 Team 2` as Teams. Respective team areas has been created in the project. Other custom areas won't created as part of the new project, This has to be configured manually.
> 
> ![image](https://user-images.githubusercontent.com/38463158/152089934-ea70f7a8-c8b7-4b73-a848-b9cb4a60ebb2.png)
> 
> Also, I could see work items created in the respective Team Areas ![image](https://user-images.githubusercontent.com/38463158/152090162-cdc8ff77-3f95-4f80-b922-d7b3a1254428.png)
> 
> Please let us know if you need any help from us.

The "old" one I'm referring to that works is: [https://azuredevopsdemogenerator.azurewebsites.net/](https://azuredevopsdemogenerator.azurewebsites.net/). The "new" one that doesn't work is: [https://demogen-code.azurewebsites.net/](https://demogen-code.azurewebsites.net/).

Using the new tool and that same .zip file:
![image](https://user-images.githubusercontent.com/47188956/152125865-8b3f781b-9b9d-4735-a27c-2e620c11eb83.png)

It says it's been completed, but you can see that teams and areas aren't listed:
![image](https://user-images.githubusercontent.com/47188956/152125939-c3c389ae-1569-4c9b-840b-4191145d3202.png)

Within the newly created project, it only creates a single team:
![image](https://user-images.githubusercontent.com/47188956/152125988-839b017b-7551-4937-92bc-16d1f1f6c88b.png)

And a single area path:
![image](https://user-images.githubusercontent.com/47188956/152126007-b069782f-9a31-4f88-b768-c99cd83a861b.png)

I hope that helps clarify.

**Comment by aksh-h** [comment]
Thanks for more details. The site to which you are referring https://demogen-code.azurewebsites.net/ is a test, we suggest you to use the production one  https://azuredevopsdemogenerator.azurewebsites.net/

**Comment by paul-msft** [comment]
That's fine, on the test site it says to raise an issue here if there are any issues with it, so that's all I'm doing 🙂

![image](https://user-images.githubusercontent.com/47188956/152142160-94a91e3d-a9d3-4ade-9384-e3cd226bb2c9.png)

**Comment by aksh-h** [comment]
Understood, thank you 🙂
