### ISSUE TITLE
Could not load your organizations

### ISSUE THREAD

**Issue by sayedimac** [microsoft/AzureDevOpsDemoGenerator#573]
We keep getting this error. It is inconsistent and sometimes ensuring the Default Directory is selected when you create the Org seems to work, sometimes even with that it does not show any Orgs. 

I need a consistent solution as I train the AZ400 often. 
What can we do? Is there a workaround delegates can follow?

Full error:
_Could not load your organizations. Please check if the logged in Id contains the Azure DevOps Organizations or change the directory in profile page and try again_

**Comment by aksh-h** [comment]
Hi @sayedimac 
Thank you for reaching us, please refer to the similar issue reported [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/353)

This might help you.
Thanks
