### ISSUE TITLE
Terraform template does not deploy successfully

### ISSUE THREAD

**Issue by mkennten** [microsoft/AzureDevOpsDemoGenerator#574]
Since today I see the Terraform template stops with the error "Error while creating release definition". The project is created, but there's no release pipeline.

![image](https://user-images.githubusercontent.com/37703728/152365166-57a9274b-cbed-44f2-b0ed-bb38c2e206b9.png)

**Comment by aksh-h** [comment]
Hi @mkennten 
Thank you for reaching us. We will look into this.

Thanks

**Comment by mkennten** [comment]
@aksh-h I works now, did you already change something? I imported it a minute ago and no error occurred.

**Comment by aksh-h** [comment]
No, we are still working on it.
Sometime the third party task may take time to install and load in pipeline. So this might have thrown error.
