### ISSUE TITLE
Error - Creating Project based on LaunchDarkly template

### ISSUE THREAD

**Issue by vgaz400** [microsoft/AzureDevOpsDemoGenerator#575]
## Getting below error while creating the project:
**Error while creating release definition: Tasks with versions 'LaunchDarkly Rollout:3.*' are not valid for deploy job 'Agent job' in stage Stage 1.**

**Comment by vgaz400** [comment]
![Annotation 2022-02-03 142258](https://user-images.githubusercontent.com/98848549/152439470-341ac9e1-4613-4de2-adc3-bc1786315d3c.png)
![Annotation 2022-02-03 1422581](https://user-images.githubusercontent.com/98848549/152439511-042029d1-f4fc-42d1-9fc8-0ded1de3cf53.png)

**Comment by aksh-h** [comment]
Hi @vgaz400 

This seems to be an issue with an extension that needs to be installed and enabled before provisioning the project, Kindly try to install the [LaunchDarkly](https://marketplace.visualstudio.com/items?itemName=launchdarkly.launchdarkly-extension) extension from Azure DevOps Marketplace and try to provision the project.

Thanks

**Comment by aksh-h** [comment]
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626
