### ISSUE TITLE
Azure DevOps Demo Generator

### ISSUE THREAD

**Issue by jacquelineTML** [microsoft/AzureDevOpsDemoGenerator#577]
No permission, no rights to access.  

TF50309: The following account does not have sufficient permissions to complete the operation: Jacqueline Tan. The following permissions are needed to perform this operation: Create new projects.

How do I unlock this?

**Comment by aksh-h** [comment]
Hi @jacquelineTML 
This is about permission issues with your organization, you can contact your organization admin to provide necessary access to create and manage a project or you can create your own organization and try it.

Thanks!
