### ISSUE TITLE
added 

### ISSUE THREAD

**Issue by Samyuktha21** [microsoft/AzureDevOpsDemoGenerator#578]

**Comment by aksh-h** [comment]
@Samyuktha21 if this is the beginning of any issues, kindly provide more information.

Thanks!

**Comment by Samyuktha21** [comment]
Hello,
I am facing issue while adding demo generated project to my DevOps portal
Not sure what is causing the issue

Request you to help me on this issue.

Regards,
Samyuktha

**Comment by aksh-h** [comment]
Hi, It would be helpful if you provide more info to troubleshoot the issue.
