### ISSUE TITLE
Cant build pipeline for MyHealthClinic and showing below error

### ISSUE THREAD

**Issue by shanthan2108** [microsoft/AzureDevOpsDemoGenerator#579]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)

**Comment by aksh-h** [comment]
Hi @shanthan2108 
Thank you for reaching us.
Looks like the Bower extension is not istalled.
My Health Clinic template requires the Bower extension to be installed and enabled in your organization. We provide the extension URL and ask you to install it eight manually or by the Demo Generator itself.

Please try again to provision the project by installing the Bower extension.

Thanks
