### ISSUE TITLE
Azure devops demo generator with terraform error

### ISSUE THREAD

**Issue by shruthi-de** [microsoft/AzureDevOpsDemoGenerator#581]
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:3.*, Install Terraform 0.12.3:0.*, Terraform : init:0.*, Terraform : plan:0.*, Terraform : apply -auto-approve:0.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
This looks like an issue with Terraform extension, which needs to be installed and enabled before provisioning the project.
Please try to install the extension manually from the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks) and provision the project.

Thanks!
