### ISSUE TITLE
I can not create a a project with a template of Terraform

### ISSUE THREAD

**Issue by moosexiegithub** [microsoft/AzureDevOpsDemoGenerator#582]
I can not create a a project with a template of Terraform...
I am in AZsure DevOps 400 class.

Thanks,
Megan Xie

**Comment by aksh-h** [comment]
Please provide more information on what issue you are facing. If the template demands any extension to be installed, please install it manually and try to provision the project.
Let us know if you need any more assistance.

Thanks
