### ISSUE TITLE
Newbie, need help setting up demo project template

### ISSUE THREAD

**Issue by paks786** [microsoft/AzureDevOpsDemoGenerator#586]
I keep on getting this error when trying to create a project template from the demo generator. What do I need to fix this issue?

Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)

**Comment by aksh-h** [comment]
@paks786 please provide more info on which template you tried. If the template demands any extension to be installed, try to install that extension manually and provision the project. Let us know if you need any more help.

Thanks
