### ISSUE TITLE
Error deploying Azure Kubernetes Service template

### ISSUE THREAD

**Issue by ececiu** [microsoft/AzureDevOpsDemoGenerator#587]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.) A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
This looks like an issue with Kubernetes extension, which needs to be installed and enabled before provisioning the project.
Please try to install the extension manually from the [marketplace ](https://marketplace.visualstudio.com/items?itemName=tsuyoshiushio.k8s-endpoint)and provision the project.

Thanks!
