### ISSUE TITLE
Project creation ran into an issue in Azure DevOps demo generator 

### ISSUE THREAD

**Issue by Maria-98-ui** [microsoft/AzureDevOpsDemoGenerator#589]
Hello,, I tried to create a new project by choosing MyHealthClinic template in azure devops demo generator but it keeps running into an issue. Can someone please provide a solution as to how to resolve it as I am new to this? Thank you in advance.

![fail](https://user-images.githubusercontent.com/68734768/153612741-dff9b196-691d-4c8a-a0f8-a3b8291bcf26.JPG)

**Comment by aksh-h** [comment]
@Maria-98-ui please share more details by clicking on the ```View Diagnostics``` button to see the more detailed error message.
