### ISSUE TITLE
Having an issue while creating a project using template MyHealth Clinic

### ISSUE THREAD

**Issue by ramanaidu9989** [microsoft/AzureDevOpsDemoGenerator#592]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)

**Comment by aksh-h** [comment]
Hi @ramanaidu9989 

Please refer to the [link](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/579). This might help you to resolve the issue
