### ISSUE TITLE
INCLUDE switch directory option for demo generator

### ISSUE THREAD

**Issue by unaihuete93** [microsoft/AzureDevOpsDemoGenerator#593]

**Comment by unaihuete93** [comment]
It looks like demogenerator takes a default directory from https://aex.dev.azure.com/, which does not make it easy when needing to change it:
1. Open private browser
2. go to https://aex.dev.azure.com/ and select the new directory
3. Open demo generator and sign in 

It should include something similar to Azure DevOps portal to swith the related Azure AD easier:
![image](https://user-images.githubusercontent.com/64772417/153894660-a821f964-936d-4ad8-bec0-f72548a91b99.png)

**Comment by aksh-h** [comment]
Implemented the feature to switch between directories. Please click on the profile icon to see the option.

**Comment by unaihuete93** [comment]
it looks like we still need to clean cache before opening demogenerator again with another active directory, if we dont, it open demogenerator with the first directory

**Comment by unaihuete93** [comment]
maybe we can choose the directory when signing in?

**Comment by aksh-h** [comment]
we have tested the feature, looks like it is working fine, as we are reading all the tokens from the new/changed active directory.

**Comment by unaihuete93** [comment]
In my case I need to click on switch directory, change it in https://aex.dev.azure.com/ and open a clean browser in incognito. It does not work if the other directory is on cache or so :( It would amazing to be able to change the directory on the same demogenerator website (as Azure Devops does)
