### ISSUE TITLE
Error while trying to use terraform template

### ISSUE THREAD

**Issue by terinvarghese** [microsoft/AzureDevOpsDemoGenerator#594]
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:3.*, Install Terraform 0.12.3:0.*, Terraform : init:0.*, Terraform : plan:0.*, Terraform : apply -auto-approve:0.*' are not valid for deploy job 'Agent job' in stage Dev.

Tried deleting the project and recreating it a few times. Everytime it fails with the same error.

**Comment by terinvarghese** [comment]
I tried installing terraform extension from the marketplace and tried to use the template again through Demo Generator. This time i get error as below 

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:3.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by benhec** [comment]
Im experiencing the same issue

**Comment by benhec** [comment]
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626
