### ISSUE TITLE
Issue while creating terraform project

### ISSUE THREAD

**Issue by pa-titly** [microsoft/AzureDevOpsDemoGenerator#599]
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:3.*, Install Terraform 0.12.3:0.*, Terraform : init:0.*, Terraform : plan:0.*, Terraform : apply -auto-approve:0.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by unaihuete93** [comment]
For some reason this is happening to every student in our AZ-400 courses. When running it for a second time it works (of course either choosing different project name or deleting first one)
![image](https://user-images.githubusercontent.com/64772417/154496899-9fcf9673-afe8-4aba-bb59-760035e6566d.png)

**Comment by unaihuete93** [comment]
related https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/585

**Comment by davidokeyode** [comment]
Got the same issue in class today. We worked around by installing the extensions manually (but it did not even give the option to add the extensions in the DevOps demo generator). Thanks.

Install the terraform extension to your ORG - https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks
Install the Replace tokens extension to your ORG - https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens

**Comment by unaihuete93** [comment]
@davidokeyode it does not give the option because now new ADO orgs have this setting disabled by default. Even if enabled it fails, the need to be installed manually, or run the generator template twice:
![image](https://user-images.githubusercontent.com/64772417/154662085-bbd5671f-0153-447b-828f-32dfc1e1801f.png)
