### ISSUE TITLE
Error during template generation "Azure Kubernetes Service" template

### ISSUE THREAD

**Issue by igorvuleta** [microsoft/AzureDevOpsDemoGenerator#600]
I have gotten the following error while generating a azure devops template. Note that the Project is generated but the pipeline definition is faulty.

Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.) A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
Please install the required extension manually and try to provision the project.
