### ISSUE TITLE
AzureDevOpsDemoGenerator : Deploying a multi-container application to AKS Issue 

### ISSUE THREAD

**Issue by nayakkartik** [microsoft/AzureDevOpsDemoGenerator#601]
Hi,
While creating the project from the AzureDevOpsDemoGenerator : for Deploying a multi-container application to AKS , finding the below Issue/error/
Unable to create the project. 
The error message showing as below.

86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.) A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 3.*, job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
we don't see any issue with the AKS template, if anything is related to the extension, please install the extension manually and try to provision the project.

Thanks!
