### ISSUE TITLE
Whitesource bolt project template is not working

### ISSUE THREAD

**Issue by alodha100** [microsoft/AzureDevOpsDemoGenerator#604]
After logging into the Demo generator page, when we select the whitesource bolt project, it is not getting created. 
I tried to install the whitesource extension from the marketplace, but it is still not working. 
![whitesourcebolt](https://user-images.githubusercontent.com/24890101/154672168-88f6b817-773c-4fc1-9cab-e25a058afca1.png)

**Comment by aksh-h** [comment]
@alodha100 we don't see any problem with White Source Bolt template. Click on the view diagnostics button to see more info and share with us. 
If any issues related to extensions, please install it manually and try to provision the project.

Thanks.
