### ISSUE TITLE
using Tailwind Traders

### ISSUE THREAD

**Issue by padaukwai** [microsoft/AzureDevOpsDemoGenerator#610]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
Kindly retry to provision the project.

**Comment by aksh-h** [comment]
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626
