### ISSUE TITLE
Demo Generator Failed to setup a new project

### ISSUE THREAD

**Issue by zeeshan79** [microsoft/AzureDevOpsDemoGenerator#612]
Hi there, I'm trying to setup a new project using existing templates in DevOps for DevOps DoJo white belt training, but I get the following error, does anyone know how to fix it?

**Error while creating release definition: Tasks with versions 'ARM Outputs:4.*' are not valid for deploy job 'Run on agent' in stage Stage 1.** 

Thanks,
Zeeshan

**Comment by aksh-h** [comment]
This looks like issue with ARM Outputs extension, please install the extension in the selected organization and try to provision the project.
