### ISSUE TITLE
Error while creating build definition: The pipeline is not valid. A task is missing. 

### ISSUE THREAD

**Issue by arpit0105** [microsoft/AzureDevOpsDemoGenerator#616]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.)

**Comment by arpit0105** [comment]
It is working fine now. Thanks @aksh-h

**Comment by AbdulRasheedFerozKhan** [comment]
Hey @aksh-h, am facing the same perhaps I have the extension installed as well. Would appreciate if you can share your insights on the same. Thanks!!

**Comment by sidinai** [comment]
> 

This has been renamed to Mend Bolt
