### ISSUE TITLE
WhiteSource Bolt Project creation failed

### ISSUE THREAD

**Issue by agentp-1337** [microsoft/AzureDevOpsDemoGenerator#617]
During the DemoProject creation for WhiteSource Bolt I'm getting the following error message
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.) 

The task outlined seems to be strange at list its name.

**Comment by aksh-h** [comment]
Hi, @agentp-1337  Please install the [whitesource bolt ](https://marketplace.visualstudio.com/items?itemName=whitesource.whitesource)extension from the marketplace and try again.

Thanks

**Comment by aksh-h** [comment]
#616
