### ISSUE TITLE
Template uses "master" instead of "main"

### ISSUE THREAD

**Issue by dbroin** [microsoft/AzureDevOpsDemoGenerator#620]
The "Create a release pipeline with Azure Pipelines" template references the "master" branch instead of "main".
So breaks Azure pipeline runs, with error:
Encountered error(s) while parsing pipeline YAML: Could not get the latest source version for repository dbroin/mslearn-tailspin-spacegame-web-deploy hosted on https://github.com/dbroin/mslearn-tailspin-spacegame-web-deploy using ref refs/heads/**master**. GitHub reported the error, "No commit found for SHA: refs/heads/**master**"

**Comment by aksh-h** [comment]
@dbroin Thanks for pointing. We will look into this.

**Comment by MartGordon-CCEW** [comment]
I also encountered such an error:


Encountered error(s) while parsing pipeline YAML:
Could not get the latest source version for repository MartGordon-CCEW/mslearn-tailspin-spacegame-web-deploy hosted on https://github.com/MartGordon-CCEW/mslearn-tailspin-spacegame-web-deploy using ref refs/heads/master. GitHub reported the error, "No commit found for SHA: refs/heads/master"
