### ISSUE TITLE
Tasks are not created 

### ISSUE THREAD

**Issue by manip4509** [microsoft/AzureDevOpsDemoGenerator#622]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.) A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626
