### ISSUE TITLE
No process template with type {guid} was found

### ISSUE THREAD

**Issue by MattLeach25** [microsoft/AzureDevOpsDemoGenerator#624]
Hi all,

I've tried to use the demo generator build tool to export an ADO project. This works. I then attempt to import it into another ADO organisation and i get the error 'No process template with type {guid} was found'.

I can't seem to find anything related to why this may be happening. Could anyone shed some light on what may be causing this?

Thank you.

**Comment by aksh-h** [comment]
Hi @MattLeach25 
Thanks for reaching us. If you are trying with a custom template, source and destination organizations must have the same process template Id.
If the source project is using a custom/inherited process template, you cannot have the same process in the destination/target organization. You must use the same organization to import it back.

**Comment by MattLeach25** [comment]
Hi there, thank you for your response. So if i understand the above correctly, if the source project is using a custom process template, you cannot simply export it and put it in another ADO org? If this is the case, this sadly will not work as we would like to make this template available for other people to use.

Thank you @aksh-h

**Comment by aksh-h** [comment]
@MattLeach25 yes, you're correct.
