### ISSUE TITLE
Issue with Terraform Template 

### ISSUE THREAD

**Issue by pav-subra** [microsoft/AzureDevOpsDemoGenerator#629]
Tried to create a Project using https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject and received the error while using Terraform Template

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
Please refer to#626, let us know if that helps

**Comment by muhammedeid** [comment]
see this link 
https://www.editcode.net/forum.php?mod=viewthread&tid=820823&extra=page%3D1&mobile=2

**Comment by aksh-h** [comment]
we don't see any issue with terraform template. Kindly try again.
