### ISSUE TITLE
ISSUE IN MANY TEMPLATES: PartsUnlimited template needs .netcore 2.0 and windows-2019 does not have it

### ISSUE THREAD

**Issue by unaihuete93** [microsoft/AzureDevOpsDemoGenerator#631]
fixed the issue with my students by including this task 
![image](https://user-images.githubusercontent.com/64772417/157474331-159f72b5-f7fa-46ca-a806-22063db3b108.png)
vs2017-win2016 not allowed for many, deprecated next week

**Comment by aksh-h** [comment]
@unaihuete93 This will help us. We will include this task as part of the pipeline.

Meanwhile, If you are proposing any other source code which replaces the PartsUnlimited, we are happy to assist you to onboard that into Azure DevOps Demo Generator.

**Comment by unaihuete93** [comment]
Not sure about which repo could be useful, but the ones in **DevOps Starter** of the **Azure Portal** are quite updated, the .net core one is 3.1 and has unit and functional tests too 
![image](https://user-images.githubusercontent.com/64772417/158579769-bbccac41-31ec-4779-9308-a11d16d328d0.png)

**Comment by aksh-h** [comment]
Added a fix and release
Closes #628
