### ISSUE TITLE
Unable to create project using template

### ISSUE THREAD

**Issue by mrvaibhavsharma** [microsoft/AzureDevOpsDemoGenerator#632]
![image](https://user-images.githubusercontent.com/89836288/157582540-62b87a6e-06b0-4f41-ac35-7917ea27f436.png)

**Comment by hellomattbrooks** [comment]
We have found during a training course that multiple people were not receiving the prompt in the template generator to install the required plugins. You need to do the following to fix this:

In ADO, go to your organisation settings. Got To Policies (under Security) and enable Third-party application access via OAth

**Comment by aksh-h** [comment]
#626
