### ISSUE TITLE
Cannot create project "Azure Kubernetes Service"

### ISSUE THREAD

**Issue by mdx-lab06** [microsoft/AzureDevOpsDemoGenerator#633]
this is an error
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.) A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
@mdx-lab06 Kindly refer to #626 
In ADO, go to your organization settings. Got To Policies (under Security) and enable Third-party application access via OAth
