### ISSUE TITLE
Azure DevOps Demo Generator

### ISSUE THREAD

**Issue by az400pipawinee** [microsoft/AzureDevOpsDemoGenerator#634]
Error while creating build definition: The pipeline is not valid. A task is missing. 
The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. 
This usually indicates the task isn't installed, and you may be able to install it from the
Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.) 
A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. 
This usually indicates the task isn't installed, and you may be able to install it from the 
Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.)

Azure DevOps Demo Generator
Template -> DevOps Lab -> Azure Kubernetes Server

**Comment by hellomattbrooks** [comment]
We have found during a training course that multiple people were not receiving the prompt in the template generator to install the required plugins. You need to do the following to fix this:

In ADO, go to your organisation settings. Got To Policies (under Security) and enable **Third-party application access via OAth**

**Comment by aksh-h** [comment]
@az400pipawinee Kindly refer to #626 
In ADO, go to your organization settings. Got To Policies (under Security) and enable Third-party application access via OAth
