### ISSUE TITLE
Not able to create project with LaunchDarkly template

### ISSUE THREAD

**Issue by dineshtest12** [microsoft/AzureDevOpsDemoGenerator#635]
Error while creating release definition: Tasks with versions 'LaunchDarkly Rollout:3.*' are not valid for deploy job 'Agent job' in stage Stage 1.

**Comment by aksh-h** [comment]
@dineshtest12 Kindly refer to https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626
In ADO, go to your organization settings. Got To Policies (under Security) and enable Third-party application access via OAth

Thanks
