### ISSUE TITLE
Cannot create Project using WhiteSource Bolt Template

### ISSUE THREAD

**Issue by pav-subra** [microsoft/AzureDevOpsDemoGenerator#636]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.)

**Comment by hellomattbrooks** [comment]
WhiteSourceBolt extension required for the template is older than the one available from the marketplace. We have experienced a number of people in a training exercise not getting the prompt to install extensions when deploying templates. You need to do the following to fix this:

In ADO, go to your **organisation settings**. Got To **Policies** (under **Security**) and enable **Third-party application access via OAth**

You may still need to install the latest version of the White Source Bolt extension as well to get this template to work for some reason.

**Comment by awdavies90** [comment]
Thanks @hellomattbrooks. Top bloke!

**Comment by aksh-h** [comment]
@awdavies90 Thanks for the information.
Since this setting needs to be enabled at the organization level, we cannot handle this. We are finding an alternative way for this.

Kindly refer to https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626 and try again
