### ISSUE TITLE
Not able to create a project named 'Azure Kubernetes Service' from demo generator

### ISSUE THREAD

**Issue by KranthiGajjelli** [microsoft/AzureDevOpsDemoGenerator#638]
Hi, While i am creating a project for 'Deploying a multi-container application to AKS' using 'Azure Kubernetes Service template' from https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject, i am getting an error as

'Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.) A task is missing. The pipeline references a task called 'a8515ec8-7254-4ffd-912c-86772e2b5962'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step ''.)'

Please help fix this issue
![Error_AKS](https://user-images.githubusercontent.com/72626270/158407461-915935f9-5896-4580-8eca-ac4908f7d7eb.JPG)

**Comment by aksh-h** [comment]
@KranthiGajjelli Kindly refer to #626
