### ISSUE TITLE
It doesn't appear any organizations in my profile

### ISSUE THREAD

**Issue by cmmanuel** [microsoft/AzureDevOpsDemoGenerator#645]
Hi there,

I have an issue when I'm going to create a template in my org, because it doesn't appear my org on the select box.

My org is created under AAD.

Could you help me with this issue?

Thanks you very much!

Regards.

**Comment by aksh-h** [comment]
Use the switch directory option for switching between your AAD. You can find the switch directory option on the top right corner of the Azure DevOps Demo Generator.
