### ISSUE TITLE
Sorry….We ran into an issue!

### ISSUE THREAD

**Issue by pauladityashaw** [microsoft/AzureDevOpsDemoGenerator#649]
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

**Comment by aksh-h** [comment]
Hi @pauladityashaw 
Kindly click on the View Diagnostics button and share the logs with us.

**Comment by jamesyoung007** [comment]
Copy Diagnostic Log
×
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
Please install the required extension from the marketplace.

In ADO, go to your organization settings. Go To Policies (under Security) and enable Third-party application access via OAth
You may still need to install the latest version of the extension as well to get this template to work for some reason. 
#626
