### ISSUE TITLE
Terraform template doesn't load and gives error 

### ISSUE THREAD

**Issue by umzyin** [microsoft/AzureDevOpsDemoGenerator#652]
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

**Comment by umzyin** [comment]
this is happening for more than week now!

**Comment by umzyin** [comment]
more info:
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
we don't see any issue with terraform template. Hence closing this issue.
