### ISSUE TITLE
Cannot create a project "Sharing Team Knowledge using Azure Project Wikis"

### ISSUE THREAD

**Issue by hothotsyu** [microsoft/AzureDevOpsDemoGenerator#656]
I cannot create a project with template "Tailwind Traders".
The error is as follows from the diagnostics log:
======================================================
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.)
======================================================
Would you like to help me fixed?

Best Regards,
Peter.Woodland

**Comment by aksh-h** [comment]
Kindly follow #626 and install the required extension.
