### ISSUE TITLE
Boot-Strapping "My Health Clinic" template fails

### ISSUE THREAD

**Issue by tijko** [microsoft/AzureDevOpsDemoGenerator#659]
`Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)`

It appears that the pipeline has an invalid reference to a task.  

I am using all free services with the account I was attempting to deploy to.  My organization name is `tkon781` I have a couple of local agents running.  One agent in a Windows container and the other running as a service in my host operating system which is WIndows 10 Enterprise Build 10.0.19042.

**Comment by aksh-h** [comment]
Kindly refer to #626 
Install the required extension and try again.
