### ISSUE TITLE
Tailwind traders won't build - get this error 

### ISSUE THREAD

**Issue by DanDevopsCD** [microsoft/AzureDevOpsDemoGenerator#661]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.)

**Comment by aksh-h** [comment]
Please install the required extension from the marketplace. 

In ADO, go to your organization settings. Go To Policies (under Security) and enable Third-party application access via OAth
You may still need to install the latest version of the extension as well to get this template to work for some reason. #626
