### ISSUE TITLE
Error creating build definition

### ISSUE THREAD

**Issue by labtestharald** [microsoft/AzureDevOpsDemoGenerator#663]
Hi,
I get this error while trying to create a new project (using DemoGenerator) with template "WhiteSource Bolt".

Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.)

//Harald

**Comment by aksh-h** [comment]
Please install the required extension from the marketplace.

In ADO, go to your organization settings. Go To Policies (under Security) and enable Third-party application access via OAth
You may still need to install the latest version of the extension as well to get this template to work for some reason.
#626
