### ISSUE TITLE
generating project template - copying board, card styles, columns error

### ISSUE THREAD

**Issue by jbp-ey** [microsoft/AzureDevOpsDemoGenerator#664]
I'm using the ADO Demo Generator to create a template of an existing project in my org. Some key aspects of my project are:
1. Underlying project process is Agile, which is further customized as noted below
2. I have about 10 custom work item types (WIT)
3. Each of these WIT are mapped to different backlog (kanban)
4. Each of the Kanbans have different columns

Steps I took:
1. Navigate to this url: https://azuredevopsdemogenerator.azurewebsites.net/extractor/index
2. Select my organization and project
3. Press the "Analyze" button. It generated an Artifacts Analysis listing my work item types and the count as well as some basic teams, iterations info
4. Press the "Generate Artifacts" button.
5. Download the zip file but also received the error message

> Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.Error occured while exporting Board Columns: TF401501: The board does not exist.Error occured while exporting Board Rows: TF401501: The board does not exist.Error occured while exporting Card Fields: TF401501: The board does not exist.Error occured while exporting Card Styles: TF401501: The board does not exist.

![ado_demo_generator_error](https://user-images.githubusercontent.com/103208925/162256372-0b657ea7-2348-4a1c-afdc-e87be59364b5.png)

**Comment by aksh-h** [comment]
There are some limitations to Demo Generator. Please follow the limitation document [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)
