### ISSUE TITLE
An error occurred when I create a project from template "LaunchDarkly"

### ISSUE THREAD

**Issue by hothotaz400-202203** [microsoft/AzureDevOpsDemoGenerator#665]
Diagnostic Log as bellow:

Error while creating release definition: Tasks with versions 'LaunchDarkly Rollout:3.*' are not valid for deploy job 'Agent job' in stage Stage 1.
I hope you can help me to fix the issue as soon as possible.

Best Regards,
Peter

**Comment by aksh-h** [comment]
Please install the required extension from the marketplace.

In ADO, go to your organization settings. Go To Policies (under Security) and enable Third-party application access via OAth
You may still need to install the latest version of the extension as well to get this template to work for some reason.
#626
