### ISSUE TITLE
I cannot create a project by using the template Terraform.

### ISSUE THREAD

**Issue by hothotaz400-202203** [microsoft/AzureDevOpsDemoGenerator#667]
The Error message details:
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev
![FailedCreatinTerraformProject](https://user-images.githubusercontent.com/102862853/162621722-fb607ebf-3cbf-42c8-8db5-eca88989b4a7.jpg)
.

**Comment by aksh-h** [comment]
@hothotaz400-202203 please follow the note provided, you must be able to create the project.
