### ISSUE TITLE
change trunk name to main from master

### ISSUE THREAD

**Issue by ozgurgul** [microsoft/AzureDevOpsDemoGenerator#668]
Docs mention the name of the trunk is main rather than master. Please remove master from repos.

**Comment by aksh-h** [comment]
Hi @ozgurgul 

Could you please provide more information on which template you tried? We will do the needful changes.

**Comment by ozgurgul** [comment]
It is https://github.com/microsoft/AzureDevOpsDemoGenerator

Sent from my mobile

Ozgur Gul
