### ISSUE TITLE
Unable to install the Teraform template

### ISSUE THREAD

**Issue by marcelin-ndjila** [microsoft/AzureDevOpsDemoGenerator#671]
Unable to install the Teraform template with AzureDevOpsDemoGenerator

**Comment by marcelin-ndjila** [comment]
find bellow the logs

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
@marcelin-ndjila, please follow the note provided before provisioning the project. You can also install the extension manually and create a new project.

Thanks
