### ISSUE TITLE
Unable to install extension WhiteSourceBolt on AzureDevOpsDemoGenerator

### ISSUE THREAD

**Issue by marcelin-ndjila** [microsoft/AzureDevOpsDemoGenerator#673]
Hi,

Unable to create project WhiteSourceBolt on AzureDevOpsDemoGenerator

find bellow the error message

Error while Installing extensions: TF400898: An Internal Error Occurred. Activity Id: 95d2b801-2436-44c7-ad61-2eb933322a00.Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.)

**Comment by aksh-h** [comment]
Please install the require extension in your organization. In this case, it is WhiteSourceBolt. 
Follow the note provided once you select the template and try again.
