### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by yomique** [microsoft/AzureDevOpsDemoGenerator#679]
Hi there, I'm a student currently studying Front End Developer at Learning People Global. As part of my work, I'm tasked with creating a project on Azure DevOps, but this isn't going through and it says something about 'marketplace'. Please, how do I resolve this?
Thanks

**Comment by aksh-h** [comment]
If the template that you selected requires some extension, kindly install the extension from marketplace or follow the information provided to enable the third party authentication via OAuth.

Make sure that you have all the rights to create project in the selected organization and provision the project with necessary details.
