### ISSUE TITLE
Not able to create project with LaunchDarkly template

### ISSUE THREAD

**Issue by Gowthaminr** [microsoft/AzureDevOpsDemoGenerator#684]

**Comment by Gowthaminr** [comment]
Tried creating project for Az-400, Lab 10: Feature Flag Management with LaunchDarkly and Azure DevOps. Is it throwing error.

**Comment by Gowthaminr** [comment]
Tried creating project for Az-400, Lab 10: Feature Flag Management with LaunchDarkly and Azure DevOps. Is it throwing error.

**Comment by aksh-h** [comment]
Kindly share the error details.
If it is related to extension installation, kindly install the LaunchDarkly extension from marketplace and try again.
Follow #626 to enable the policy at organization level.
