### ISSUE TITLE
Project creation fails in Lab 23 Implement Security and Compliance in an Azure DevOps pipeline Project creation

### ISSUE THREAD

**Issue by Mika-Juhani** [microsoft/AzureDevOpsDemoGenerator#685]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.)

I installed WhiteSource Bolt from the marketplace ,but I still get the same error message

**Comment by aksh-h** [comment]
Kindly try again in incognito mode or with different organization and let us know.
