### ISSUE TITLE
Azure DevOps Demo Generator issue: Pipeline is not valid due to missing task

### ISSUE THREAD

**Issue by BZhang787** [microsoft/AzureDevOpsDemoGenerator#690]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)

**Comment by aksh-h** [comment]
Kindly install the necessary extensions from marketplace. These are required for the template to provision the project correctly.

**Comment by aksh-h** [comment]
#626
