### ISSUE TITLE
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1. 

### ISSUE THREAD

**Issue by mor2uyii** [microsoft/AzureDevOpsDemoGenerator#697]
[AB#3845](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3845)

**Comment by aksh-h** [comment]
Hi @mor2uyii 
Are you able to see the following screen once you select the template and organization?

![image](https://user-images.githubusercontent.com/38463158/169787845-8ee1b1ad-edfa-4a0c-8a27-ed1f9d40ac56.png)
