### ISSUE TITLE
LED Immersion trainng Azure DevOps Demo Generator problem

### ISSUE THREAD

**Issue by PerttuVaisanen** [microsoft/AzureDevOpsDemoGenerator#702]
I´m getting below message when trying to create a project:

 "TF50309: The following account does not have sufficient permissions to complete the operation: Perttu Väisänen. The following permissions are needed to perform this operation: Create new projects."

**Comment by aksh-h** [comment]
Please make sure that you have the necessary permission to create a project in your organization. 
You can create your own organization and try to provision projects.

Thanks.
