### ISSUE TITLE
 Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines 

### ISSUE THREAD

**Issue by vargheseibm** [microsoft/AzureDevOpsDemoGenerator#707]
while uploading the template terraform using Demo generator it fails with the following message:
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

[AB#3835](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3835)

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

As a workaround, you can install the extension from marketplace.

Thanks
