### ISSUE TITLE
WhiteSource Bolt project creation fails

### ISSUE THREAD

**Issue by preethikanji12** [microsoft/AzureDevOpsDemoGenerator#708]
Error message-
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.)

[AB#3836](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3836)

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

Thanks
