### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by boppanaushasri** [microsoft/AzureDevOpsDemoGenerator#711]
I am getting this error while I am creating new project in Azure DevOps Demo generator.

**Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)**

[AB#3839](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3839)

**Comment by aksh-h** [comment]
Kindly install the required task from the marketplace and provision the new project using the template

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

Thanks
