### ISSUE TITLE
Demo Generator does not pick up the custom template configurations. 

### ISSUE THREAD

**Issue by vish-thakur** [microsoft/AzureDevOpsDemoGenerator#713]
Hi Team

We want to use the Demo Generator(DG) to create projects from a template. We created a sample project and extracted a template. I am a PCA(Project Collection Admin) for the Org. Now when we create a project using the template, it simply creates the project and does not create along with that the built-in groups, custom permissions and policies on the groups and repos. 

We also have environments and the approvals for those environments in the sample project and none of them are created when we create a new project with DG using the Custom template. 

The template extractor does not pick up the user and when I manually add user in Json zip file, the DG does not add the users to the new project created. 

Can you please advise if I am doing something wrong?

Thanks
Vish

[AB#3841](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3841)

**Comment by aksh-h** [comment]
Hi @vish-thakur 
Azure DevOps Demo Generator helps teams create projects on their Team Services account with pre-populated sample content that includes source code, work items, iterations, service endpoints, and pipelines based on a chosen template.

Please refer to [limitations](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md) document here.

Let us know if anything is needed.
