### ISSUE TITLE
Got an issue

### ISSUE THREAD

**Issue by vmagit** [microsoft/AzureDevOpsDemoGenerator#718]
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

[AB#3852](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3852)

**Comment by aksh-h** [comment]
@vmagit Please click on **View Diagnostics** button and share the additional details.
