### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by vmagit** [microsoft/AzureDevOpsDemoGenerator#719]
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

[AB#3853](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3853)

**Comment by aksh-h** [comment]
Please install the required extension from marketplace and try agian.
