### ISSUE TITLE
error creating new project

### ISSUE THREAD

**Issue by Chacha65** [microsoft/AzureDevOpsDemoGenerator#729]
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

[AB#3859](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3859)

**Comment by aksh-h** [comment]
Kindly install the ARM Outputs extension from Marketplace.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

Thanks
