### ISSUE TITLE
Terraform-CD pipeline is missing when using the generator and following steps

### ISSUE THREAD

**Issue by MohnJadden** [microsoft/AzureDevOpsDemoGenerator#734]
My team is following through the steps listed at https://www.azuredevopslabs.com/labs/vstsextend/terraform/ and have proceeded without issue through Exercise 1 and 2.  In Exercise 3, when we navigate to Pipelines -> Releases, there is no Terraform-CD pipeline.   

We re-ran the demo from the start and created a new project.  The Terraform-CD pipeline was visible in the releases at that point.  

There should either be a fix to ensure the pipeline generates with the generator or notes added in the guide that advise on generating a fresh project if the release is not present.

[AB#3869](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3869)

**Comment by aksh-h** [comment]
@MohnJadden Could you please rerun the template to provision a new project?
You must be able to see the release pipeline as shown below.

![image](https://user-images.githubusercontent.com/38463158/180129140-eea390c2-111c-48ef-a7b3-9ea403d38d6e.png)
