### ISSUE TITLE
Unable to created Project 

### ISSUE THREAD

**Issue by ranaerra8058** [microsoft/AzureDevOpsDemoGenerator#737]
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

[AB#3872](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3872)

**Comment by aksh-h** [comment]
Kindly install the ARM Outputs task manually from Marketplace.
Please refer to #626
