### ISSUE TITLE
Unable to create the project completely through demo generator

### ISSUE THREAD

**Issue by nath-sanjay** [microsoft/AzureDevOpsDemoGenerator#739]
No code is seen in git repo. in azure devops after the creation of the project from azure demo generator.
I was trying the steps mentioned in this lab: https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M03_L04_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.html
This was working till last week. The demo generator never completes successfully. It just stalls at one point, the project gets created in azure devops but then there's no file/code in the git repo

[AB#3874](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3874)

**Comment by nath-sanjay** [comment]
![image](https://user-images.githubusercontent.com/13308671/179155164-8867c468-3eb2-408b-85cd-c60ae3618730.png)
![demo gen problem](https://user-images.githubusercontent.com/13308671/179155245-a2df67cd-625f-4cec-8f4c-b223c147e501.JPG)

**Comment by nath-sanjay** [comment]
Closed it by mistake. trying to reopen it

**Comment by aksh-h** [comment]
@nath-sanjay we don't see any issue with the selected templated - **PartsUnlimited**. Could you please try to create the project with a short name and try? Let us know your updates.
