### ISSUE TITLE
Error log 

### ISSUE THREAD

**Issue by hackademy-lab-azure** [microsoft/AzureDevOpsDemoGenerator#740]
Hi, you can help me with this?

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

[AB#3875](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3875)

**Comment by aksh-h** [comment]
Kindly install the Terraform extension manually and proceed to create the project.
