### ISSUE TITLE
Azure demo data generator

### ISSUE THREAD

**Issue by ehsan-shirazi** [microsoft/AzureDevOpsDemoGenerator#741]
Hi,

I tried to generate data for my account multiple times and fails!

Thanks,
Ehsan

[AB#3876](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3876)

**Comment by aksh-h** [comment]
Hi, @ehsan-shirazi Could you please share more info about what went wrong? If you faced any errors, click on the ```View Diagnostic Logs``` button and share more details here.

**Comment by ehsan-shirazi** [comment]
Hi,

I tried to get a template from AzureDevOpsDemoGeneratore, but it gave error
message as below:
[image: image.png]
But later on, I realized that the Demo template has been added into my
account despite the error message.
Thank you for following up.

Respectfully,
Ehsan
