### ISSUE TITLE
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

### ISSUE THREAD

**Issue by mkrsnadas** [microsoft/AzureDevOpsDemoGenerator#745]
Hi Team,

I was unable to create the project  due to the following error:

Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

This is for my AZ-400 labs. Can you please help fix this ?

Thanks
Krishna.

[AB#3879](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3879)

**Comment by aksh-h** [comment]
Kindly install the ARM Outputs extension from the marketplace and try to provision the project.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.
