### ISSUE TITLE
Python template Release Pipeline Edit blank page

### ISSUE THREAD

**Issue by effistvan** [microsoft/AzureDevOpsDemoGenerator#746]
Hi,
I've created a project from Python template, but unable to edit the generated Python-CD release pipeline, only blank page appears.
I can reach tasks via direct link: ..."project"/_releaseDefinition?definitionId=1&_a=definition-tasks&environmentId=2
But this gives also  a blank page: ..."project"/_releaseDefinition?definitionId=1&_a=definition-pipeline

I've tried with different browsers, different machine, different generated projects, same result.

Do you have any suggestion?

Thanks,

Istvan

[AB#3880](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3880)

**Comment by aksh-h** [comment]
Hi @effistvan Are you using a custom-generated template using Template builder?
If so, please share the template zip file to this [mail](mailto:akshay.hosur@ecanarys.com) and we will inspect the issue.

Thanks

**Comment by effistvan** [comment]
Hi Akshay,

I am trying to go through this tutorial: Deploying a CD pipeline for a Django-based Python app | Azure DevOps Hands-on-Labs (azuredevopslabs.com)<https://www.azuredevopslabs.com/labs/vstsextend/python/>

Starting with this link:
https://azuredevopsdemogenerator.azurewebsites.net/?Name=Python&TemplateId=77369
(Name=Python&TemplateId=77369)


But now, it look OK.



Thanks,

Istvan

**Comment by effistvan** [comment]
Sorry, it does not work ☹

I’ve mixed the build pipeline and release pipeline.

Release pipeline has problem showing the preview tab.

***@***.***

I’ve generated a template from the project created by the demo generator.



Thanks,

Istvan


From: István FERENCZ
Sent: Monday, August 1, 2022 12:25 PM
To: microsoft/AzureDevOpsDemoGenerator ***@***.***>; microsoft/AzureDevOpsDemoGenerator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoft/AzureDevOpsDemoGenerator] Python template Release Pipeline Edit blank page (Issue #746)

Hi Akshay,

I am trying to go through this tutorial: Deploying a CD pipeline for a Django-based Python app | Azure DevOps Hands-on-Labs (azuredevopslabs.com)<https://www.azuredevopslabs.com/labs/vstsextend/python/>

Starting with this link:
https://azuredevopsdemogenerator.azurewebsites.net/?Name=Python&TemplateId=77369
(Name=Python&TemplateId=77369)


But now, it look OK.



Thanks,

Istvan
