### ISSUE TITLE
Error While creating Project

### ISSUE THREAD

**Issue by ravikumargunge** [microsoft/AzureDevOpsDemoGenerator#748]
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

![image](https://user-images.githubusercontent.com/4901284/180919887-f033528e-c278-4b1b-ad3d-19a9a2954ec3.png)

[AB#3882](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3882)

**Comment by aksh-h** [comment]
Kindly install the ARM Outputs extension from the marketplace and try to provision the project.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.
