### ISSUE TITLE
setting up azure pipeline demo failed

### ISSUE THREAD

**Issue by RemcoBartelink** [microsoft/AzureDevOpsDemoGenerator#749]
Hi,

I tried setting up an Azure Pipeline demo but provisioning failed with this error:

Error while creating release definition: Tasks with versions 'Replace variables in Ansible script to deploy Azure resources:4.*, Run playbook to deploy Azure resources:0.*' are not valid for deploy job 'Agent job' in stage Azure Dev.

Are these demos still maintained?

[AB#3883](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3883)

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

Thanks
