### ISSUE TITLE
Azure demo data generator, project created but work items are missing

### ISSUE THREAD

**Issue by pietklop** [microsoft/AzureDevOpsDemoGenerator#750]
HI,
I have setup a customer template project with a set of work items defined. When creating the final project with use of the template it kind of works. But all the work items are missing. This has worked before, but is broken since a couple of weeks.

The work items are setup hierarchical in the backlog like Epic.Feature.UserStory. I can see that they are existing in the related json files within the builded zip file. The generator reports all fine, even 'Work items created'

Hopefully you have enough data to reproduce the issue.

![image](https://user-images.githubusercontent.com/8931114/181192390-dde7ead7-7fae-41c3-beb5-3ff8a7d82ae8.png)

[AB#3884](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3884)

**Comment by aksh-h** [comment]
@pietklop Kindly share the generated template to inspect the issue.

**Comment by pietklop** [comment]
Hi, with this the generated template.
[Customer template.zip](https://github.com/microsoft/AzureDevOpsDemoGenerator/files/9229601/Customer.template.zip)
