### ISSUE TITLE
WhiteSource Bolt Project on Azure DevOps Demo Generator

### ISSUE THREAD

**Issue by OreCB** [microsoft/AzureDevOpsDemoGenerator#757]
[AB#3890](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3890)

**Comment by OreCB** [comment]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '521d1e00-f5fb-4b73-a93b-b2fe88a9af91'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version , job 'Phase_1', step 'WhiteSourceBolt3'.)

**Comment by aksh-h** [comment]
Kindly install the whitesource-bolt extension from Azure DevOps Marketplace and try to provision the project,
