### ISSUE TITLE
Error Terraform template

### ISSUE THREAD

**Issue by alibhayani** [microsoft/AzureDevOpsDemoGenerator#760]
Getting following error when generating a new devops project:
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

[AB#3893](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3893)

**Comment by aksh-h** [comment]
Kindly install the Replace Tokens Task from the marketplace and try to provision the project,

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.
