### ISSUE TITLE
Parts Unlimited Project Template 

### ISSUE THREAD

**Issue by Jrogers07** [microsoft/AzureDevOpsDemoGenerator#765]
TASK 6 Issue - Phase_1

**Copy Diagnostic Log**
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (**Task version 6**.*, job 'Phase_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.)r

[AB#3896](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3896)

**Comment by ancgate** [comment]
@Jrogers07 , can you check this one #626 ?

**Comment by aksh-h** [comment]
Kindly Install the required extensions manually from the marketplace and try to provision the project.

Refer to https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626 for more info

**Comment by Jrogers07** [comment]
Akshay,

Thanks I will the Third Party application access and get back to you

[image: image.png]


*James*
