### ISSUE TITLE
Whitesource Bolt lab should be updated to use Mend (new name and extension)

### ISSUE THREAD

**Issue by unaihuete93** [microsoft/AzureDevOpsDemoGenerator#766]
[AB#3897](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3897)

**Comment by unaihuete93** [comment]
Please update to renamed tool/extension: https://marketplace.visualstudio.com/items?itemName=whitesource.whiteSource-bolt-v2

**Comment by aksh-h** [comment]
@unaihuete93 Thanks for providing the details. We will take a look.

**Comment by aksh-h** [comment]
We will do the deployment once the necessary changes are done in labs.

**Comment by unaihuete93** [comment]
amazing, thanks!
