### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by YoureBeloved** [microsoft/AzureDevOpsDemoGenerator#770]
TF200019: The following project already exists on the Azure DevOps Server: MyHealthClinic. You cannot create a new project with the same name as an existing project. Provide a different name.

[AB#3900](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3900)

**Comment by aksh-h** [comment]
Kindly get the required access to create a project from the organization admin and try to provision the project.
