### ISSUE TITLE
Failed to create a new project based on the Tailwind Traders template

### ISSUE THREAD

**Issue by cek-roadmunk-tempo** [microsoft/AzureDevOpsDemoGenerator#774]
I tried to use  Azure DevOps Demo Generator to generate a project based on the Tailwind Traders template.

After clicking 'Create Project' it progresses but then fails with the following error:
```
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.) Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '584bcff2-3353-4f11-872b-6ba01267a972'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 6.*, job 'Phase_1', step ''.)
```

[AB#3903](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3903)

**Comment by ancgate** [comment]
@cek-roadmunk-tempo , check the following #626

**Comment by cek333** [comment]
Thanks @ancgate. However, I did see that in the documentation, so I did have `Third-party application access via OAuth` enabled.

I should add though ... even though the process did end in an error, at least the Azure DevOps Boards were created.

**Comment by cek-roadmunk-tempo** [comment]
Thanks @ancgate. However, I did see that in the documentation, so I did have Third-party application access via OAuth enabled.

I should add though ... even though the process did end in an error, at least the Azure DevOps Boards were created.

**Comment by ancgate** [comment]
if a task is missing, it is giving the task that is missing 

![image](https://user-images.githubusercontent.com/4063982/192598307-62dae123-df59-4dca-a235-f573ea93495d.png)

**Comment by cek-roadmunk-tempo** [comment]
I can't recall all the steps I took when I first created this issue, so I just re-ran the steps.

I see the screenshot you posted above and I enabled the checkbox to have it "installed automatically". This time the project generation did run to completion. Thanks.
