### ISSUE TITLE
Error using demo generator for Whitehouse Bolt template

### ISSUE THREAD

**Issue by ferhanopai** [microsoft/AzureDevOpsDemoGenerator#776]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '58dccf9e-3eaf-4533-a9b6-1e5a1845d036'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 21.*, job 'Phase_1', step ''.)

Can you help fixing this issue

[AB#3905](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3905)

**Comment by ancgate** [comment]
@ferhanopai , you can refer to this link #626
