### ISSUE TITLE
Terraform Folder not available in DevOps demogenerator

### ISSUE THREAD

**Issue by chandainfy** [microsoft/AzureDevOpsDemoGenerator#777]
unable to locate Terraform folder in terraform demo project. link to repo: 
https://dev.azure.com/chandainfy/PartsTF/_git/PartsUnlimited

[AB#3906](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3906)

**Comment by aksh-h** [comment]
Terraform template is available in the DevOps labs section of the Azure DevOps Demo Generator. If you are trying any private template please provide more info.
