### ISSUE TITLE
Error provisioning

### ISSUE THREAD

**Issue by alexcatalinb** [microsoft/AzureDevOpsDemoGenerator#778]
Hello,

I am trying to import a demo and I've got this error:

Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

How to resolve that?

[AB#3907](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3907)

**Comment by aksh-h** [comment]
Kindly install the required extension manually and try to provision the project.
Follow #626 for more info.
