### ISSUE TITLE
Error creating Terraform demo

### ISSUE THREAD

**Issue by jonathonstevensls** [microsoft/AzureDevOpsDemoGenerator#780]
I attempted to create the demo for Terraform and received the following:

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*' are not valid for deploy job 'Agent job' in stage Dev.

[AB#3908](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3908)

**Comment by aksh-h** [comment]
Kindly Install the required extensions manually from the marketplace and try to provision the project.

Refer to https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/626 for more info
