### ISSUE TITLE
Not able to create a project from 'MyHealthClinic' template 

### ISSUE THREAD

**Issue by ed-the-tester** [microsoft/AzureDevOpsDemoGenerator#782]
I have attempted to create a new project multiple times from this template, though this doesn't appear to work. I receive a box 'sorry...we ran into an issue!'. When I click into it to view logs I receive an error message indicating a task is missing.

![image](https://user-images.githubusercontent.com/33628919/191041378-26875167-9ace-4c70-b7f1-5ffa37b4540e.png)

[AB#3910](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3910)

**Comment by ancgate** [comment]
@ed-the-tester , can you try take a look at this one #626 ?

**Comment by aksh-h** [comment]
Please install the necessary extension from the marketplace or follow the instruction to enable the third-party authentication via OAuth in the organization settings and try again.
