### ISSUE TITLE
SharePoint Files Uploader no longer available

### ISSUE THREAD

**Issue by ryanferguson** [microsoft/AzureDevOpsDemoGenerator#784]
When trying to create a project based on an exported template, I am getting an error that the org needs this app:
https://marketplace.visualstudio.com/items?itemName=projectumapsvsts.upload-sp-files-app&ssr=false#overview

This app is no longer available though which means there is no way to deploy it to an org that requires it to get the project.

To re-create the error, create a template from an existing project and try to import it into a brand new org that doesn't have that app installed within it.  Since there is no way to install the app any longer, there is no way to use the import features from what I can tell.

![image](https://user-images.githubusercontent.com/13313299/192509998-a1036272-df23-4ee4-8ae5-03ce1c8081fd.png)

[AB#3912](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3912)

**Comment by aksh-h** [comment]
Thank you for reaching us. 
Looks like this is private template, please clean up your template before you use it. 

Thanks.
