### ISSUE TITLE
error while creating release

### ISSUE THREAD

**Issue by abinayap2000** [microsoft/AzureDevOpsDemoGenerator#786]
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

[AB#3914](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3914)

**Comment by aksh-h** [comment]
#626
