### ISSUE TITLE
Issue with deploying this lab template: MyHealthClinic

### ISSUE THREAD

**Issue by HeikaGrant** [microsoft/AzureDevOpsDemoGenerator#788]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)

[AB#3915](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3915)

**Comment by aksh-h** [comment]
Please install the Bower extension manually and try to provision the project.

Please refer to #626 for more info
