### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by btavr** [microsoft/AzureDevOpsDemoGenerator#790]
When trying to create the template i get this error message:

Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '58dccf9e-3eaf-4533-a9b6-1e5a1845d036'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 21.*, job 'Phase_1', step ''.)Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '58dccf9e-3eaf-4533-a9b6-1e5a1845d036'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 21.*, job 'Phase_1', step ''.)

but the project is created anyway

[AB#3916](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3916)

**Comment by aksh-h** [comment]
Kindly Install the required extensions manually from the marketplace and try to provision the project.

Refer to #626 for more info
