### ISSUE TITLE
Error while AKS project creation

### ISSUE THREAD

**Issue by jaganmodepu** [microsoft/AzureDevOpsDemoGenerator#795]
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

[AB#3921](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3921)

**Comment by mwdarab** [comment]
I ran into same issue trying to create an AKS project. It seems like the "appsettings.json" and other pipeline components do not get deployed. I got stuck at #4 [here](https://azuredevopslabs.com/labs/vstsextend/kubernetes/#exercise-1-configure-build-pipeline).

**Comment by aksh-h** [comment]
Thank you for reaching us. We will look into this.
