### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by sonofralph** [microsoft/AzureDevOpsDemoGenerator#797]
Having issue generating a new demo

[AB#3923](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3923)

**Comment by aksh-h** [comment]
@sonofralph kindly provide more info on which template did you try and what the issue you faced,
If it is a private template, kindly share the template zip file here.
