### ISSUE TITLE
Error while loading Contoso Air demo

### ISSUE THREAD

**Issue by jkubikng** [microsoft/AzureDevOpsDemoGenerator#803]
Hello,

I am receiving this error when trying to make a new project using the demo Contoso Air

"Error while creating release definition: Tasks with versions 'ARM Outputs:4.*' are not valid for deploy job 'Run on agent' in stage Stage 1."

I did try to delete the project it half created, reloaded the demo generator page and tried again with this same error.

[AB#3930](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3930)

**Comment by aksh-h** [comment]
Hi @jkubikng 
Looks like you are using the Demo Generator for the first time. Please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies ```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

**Comment by jkubikng** [comment]
Thank you!  When I pick Contoso Air template the directions for how to enable OAuth disappeared so I never noticed them.

Now with OAuth enabled I see further instructions to enable ARM Outputs.  Once I did that now the demo loaded correctly.

Thank you!

**Comment by aksh-h** [comment]
Thank you for sharing the updates.
