### ISSUE TITLE
Provisioning failed for Terraform template

### ISSUE THREAD

**Issue by GodChosen** [microsoft/AzureDevOpsDemoGenerator#808]
Hello Team,

I need assistance fixing the provisioning of a project with Terraform template, as I am getting the error below:

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

Looking forward to your response.

[AB#3935](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3935)

**Comment by aksh-h** [comment]
@bharath199406 If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

Thanks
