### ISSUE TITLE
Error on the created build

### ISSUE THREAD

**Issue by mc220517312** [microsoft/AzureDevOpsDemoGenerator#821]
Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '58dccf9e-3eaf-4533-a9b6-1e5a1845d036'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 21.*, job 'Phase_1', step ''.)

[AB#3946](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3946)

**Comment by aksh-h** [comment]
@bharath199406 If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

Thanks
