### ISSUE TITLE
Configuring Agent Pools and Understanding Pipeline Styles hanging

### ISSUE THREAD

**Issue by artcodatacompany** [microsoft/AzureDevOpsDemoGenerator#822]
"Configuring Agent Pools and Understanding Pipeline Styles created" hanging
![Untitled](https://user-images.githubusercontent.com/119485123/206889005-87adf632-5103-4d63-b816-edd45acb0f9d.png)

[AB#3947](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3947)

**Comment by aksh-h** [comment]
Hi @artcodatacompany 
This message doesn't belong to Azure DevOps Demo Generator. If this is your private instance and if you are planning to contribute back to the Demo Generator we can assist you.
