### ISSUE TITLE
MyHealthClinic

### ISSUE THREAD

**Issue by avenir1984** [microsoft/AzureDevOpsDemoGenerator#829]
TF200019: The following project already exists on the Azure DevOps Server: MyHealthClinic. You cannot create a new project with the same name as an existing project. Provide a different name.

[AB#3951](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3951)

**Comment by aksh-h** [comment]
As the error is showing, the project with the name MyHealthClinic is already present in your selected DevOps Organization.
Please provide a different name and try again.
Thanks
