### ISSUE TITLE
I am not able to create project from Demo Generator

### ISSUE THREAD

**Issue by sandraelsitgeorge-new** [microsoft/AzureDevOpsDemoGenerator#835]
<img width="440" alt="Screenshot 2023-01-18 102722" src="https://user-images.githubusercontent.com/119250473/213213010-cfd14ac4-e494-45ce-b8a0-2bb1bb28f88a.png">

Error while creating build definition: The pipeline is not valid. A task is missing. The pipeline references a task called '4fa3aac0-0020-4832-9089-9979c9dd3e69'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.*, job 'Phase_1', step 'Bower_3'.)

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies ```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Run the demo generator again and try to install the extension needed by the template.

Thanks
