### ISSUE TITLE
Is there a way to pull chunks of 200 for larger projects?

### ISSUE THREAD

**Issue by mmBPCS** [microsoft/AzureDevOpsDemoGenerator#837]
New here, so apologies if I missed a listing outside the limitations article. 

Thanks in advance!

**Comment by aksh-h** [comment]
@mmBPCS The Azure DevOps Services Demo Generator is a service that helps you provision projects in your organization with pre-populated sample content that includes source code, work items, iterations, service connections, and build and release pipelines based on a template you choose.

I assume you are trying to export or migrate the data from multiple projects, there could be other tools on the marketplace that can fulfill your requirement.
