### ISSUE TITLE
Upload errors after building custom templates

### ISSUE THREAD

**Issue by mmBPCS** [microsoft/AzureDevOpsDemoGenerator#839]
Hi again, 

I've managed to download a fair amount of the projects in my team's organizations, but am running into the following error when attmpting upload to a new test org and generate a new project;

           _VS402362: No process template with type f6e0c2f1-d73e-44ee-bdcb-5ff8a77f5b85 was found._

![image](https://user-images.githubusercontent.com/105120290/214979400-d7b01ac2-fe87-487a-ae44-f79e1eecec61.png)

I've checked in the processes section of the originating org, and they're almost all standard Agile, with 2 set to Scrum. Any ideas what might be causing this, or suggestions for a workaround?

**Comment by aksh-h** [comment]
@mmBPCS we have limited support on custom templates. Please find the limitation document [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md).

To make use of the custom template, the source, and the target organization must be the same or use the same standard process template. You may encounter this issue when you're using a target organization that doesn't match the source project process template.
