### ISSUE TITLE
Error to create project with terraform template

### ISSUE THREAD

**Issue by alexandremjcastro** [microsoft/AzureDevOpsDemoGenerator#840]
Hello Guys.

I´m creating a project with template terraform and I get this error below:

![image](https://user-images.githubusercontent.com/39839867/215234807-7d42472d-ebe8-4e54-bab8-5b21e3522d22.png)

**Comment by aksh-h** [comment]
Please install the required extension from the marketplace.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
