### ISSUE TITLE
Lab issue terraform

### ISSUE THREAD

**Issue by HemSarz** [microsoft/AzureDevOpsDemoGenerator#841]
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
Please install the [replace tokens](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens) extension from the marketplace.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
