### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by Foster24** [microsoft/AzureDevOpsDemoGenerator#846]
can anyone help me as i'm really confused on exactly how to get started on this project
as trying to find the right template but then it says it ran into an issue if anyone could
help me at all i would really appreciate it

**Comment by aksh-h** [comment]
Hi, @Foster24 Azure DevOps Demo Generator helps you create projects on your Azure DevOps Organization with pre-populated sample content that includes source code, work items, iterations, service endpoints, and build and release definitions based on a template you choose.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Please refer to the following [documentation ](https://learn.microsoft.com/en-us/azure/devops/demo-gen/?toc=%2Fazure%2Fdevops%2Fdemo-gen%2Ftoc.json&view=azure-devops)before you begin.

For each of the templates in the Azure DevOps Demo Generator, we have the [Azure DevOps Lab](https://azuredevopslabs.com/) section, please refer to the following Lab content. 

Once you choose any template, on the right side you can see the template description along with the documentation link to it. Please follow the necessary document given for each template.
