### ISSUE TITLE
Issue while creating project with AzureDevopsDemoGenerator 

### ISSUE THREAD

**Issue by jaysanala** [microsoft/AzureDevOpsDemoGenerator#851]
Hi, i m trying to create a project using AzureDevopsDemoGenerator and i m getting this error when i click on create project 

![AzureDeopsDemoError](https://user-images.githubusercontent.com/61952493/218939619-48293060-c3dd-48d5-a503-05fa19aa1e4d.JPG)

**Comment by aksh-h** [comment]
This shows the project with the same name already exists in the selected organization, please provide a different name and try again.
