### ISSUE TITLE
Error while trying to create project SmartHotel360

### ISSUE THREAD

**Issue by subbydavid** [microsoft/AzureDevOpsDemoGenerator#853]
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

**Comment by aksh-h** [comment]
Please install the ARM Outputs extension from the marketplace.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
