### ISSUE TITLE
Terraform demo project deployment issue for the release pipeline. 

### ISSUE THREAD

**Issue by jimblizzard** [microsoft/AzureDevOpsDemoGenerator#854]
Received this error message when deploying the Terraform project into my DevOps environment:

"Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*' are not valid for deploy job 'Agent job' in stage Dev."

The release pipeline definition was not created and no additional information was provided.

**Comment by aksh-h** [comment]
Please install the [replace tokens](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens) extension from the marketplace.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
