### ISSUE TITLE
Build your template: Provisioning Failed with Generated template with scrum process

### ISSUE THREAD

**Issue by kiwatana** [microsoft/AzureDevOpsDemoGenerator#856]
I have the following errors when provisioning a new template developed by AzureDevOpsDemoGenerator template generation. Here is the error. 

Error while updating board column Error on column New: Board column must define state mapping for all work item types in the 'Microsoft.RequirementCategory' backlog. Error while updating board column Error on column New: Board column must define state mapping for all work item types in the 'Microsoft.RequirementCategory' backlog.

I am not sure what does it mean to fix the issues. If you can point to a right direction, it is really appreciated.

**Comment by aksh-h** [comment]
Hi, @kiwatana the project you're using to export the template might be using a customized process that has multiple work items in the Requirement category. The board column setting for one of the teams might not be matching. 

We have limited support on Custom generated templates. Please find the [limitation document](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)
