### ISSUE TITLE
Ansible project error in demo generator tool

### ISSUE THREAD

**Issue by touseefgit764** [microsoft/AzureDevOpsDemoGenerator#860]
Error while creating release definition: Tasks with versions 'Replace variables in Ansible script to deploy Azure resources:4.*, Run playbook to deploy Azure resources:0.*' are not valid for deploy job 'Agent job' in stage Azure Dev.

When trying to install the Ansible project, I can't see the Ansible and Replace Tokens installation option as a pre-requisite and keep failing with above error. I manage to figure it out what is missing and installed those two extensions but not other people will so please check.

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
