### ISSUE TITLE
AzureDevOpsDemoGenerator - Tasks are not valid for deploy

### ISSUE THREAD

**Issue by PatrykBiernacki** [microsoft/AzureDevOpsDemoGenerator#863]
Hi. I'm following microsoft learn AZ-400: Implement CI with Azure Pipelines and GitHub Actions.
I wanted to start Demo Generator with SmartHotel360 template. I have ran into an issue:
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

**Comment by aksh-h** [comment]
Please install the ARM Outputs extension from the marketplace and try again.
