### ISSUE TITLE
Issue while using DevOps tool generator

### ISSUE THREAD

**Issue by shrivyas** [microsoft/AzureDevOpsDemoGenerator#864]
1.	When I did the import – it errored out that only 250 items could be done and after that it showed up as limit exceeded. 
2.	The Zip file has all the items upto 250.
3.	I tried to import that in the tool and it said project template is not found.
I thought because it errored out I wasn’t able to import it.
So,
4.	I tried importing a smaller project with not much workitems in it. 
5.	Imported successfully without error.
6.	Tried to import it and gave the template not found error again.

**Comment by Chai-NED** [comment]
+1 here. The tool works for smaller number of work items, but has this template not found with larger project.

**Comment by aksh-h** [comment]
@shrivyas Azure DevOps Demo Generator is to set up the Demo Environments with a production grate template having a limited set of data. For custom templates, we have limitations on work items.

Please find the limitation [document](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)
