### ISSUE TITLE
required extensions are not installed 

### ISSUE THREAD

**Issue by Pravallikavennapusa** [microsoft/AzureDevOpsDemoGenerator#881]
my issue is work items boards and extensions are not able to see in my project

**Comment by aksh-h** [comment]
@Pravallikavennapusa could you please mention which template you've used?
if it is any custom template, please share more details along with the template zip file.

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
