### ISSUE TITLE
Terraform Template error

### ISSUE THREAD

**Issue by sonnguyen4496** [microsoft/AzureDevOpsDemoGenerator#885]
Getting below error while trying to add Terraform Template:

Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by lalitbit** [comment]
I faced the same issue exactly with same error.  You can try below steps
Go to you **Organization settings** -> **Policies**.
Enable **"Third party application access via OAuth**".

once this is enabled, try again the generator.

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
