### ISSUE TITLE
Issue in cration

### ISSUE THREAD

**Issue by mahmoudrabiewesite** [microsoft/AzureDevOpsDemoGenerator#887]
Sorry….We ran into an issue!
We ran into some issues and we are sorry about that!
The log below will provide you insights into why the provisioning failed. You can raise and issue with the logs [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/new) and we will try to help you.

Click on View Diagnostics button to share logs with us.

Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

**Comment by aksh-h** [comment]
Kindly install the ARM Outputs task manually from the marketplace and try again.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
