### ISSUE TITLE
Azure DevOps Demo Generator : Create New Terraform Project issue

### ISSUE THREAD

**Issue by jeje232** [microsoft/AzureDevOpsDemoGenerator#896]
Hello,

Copy Diagnostic Log
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

Regards

**Comment by aksh-h** [comment]
Hi @jeje232 please install the Replace Tokens extension from the marketplace and try to provision the project.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

**Comment by jeje232** [comment]
Hello Akshay,

Thanks for your answer. Finally we opt for an another way. :D
