### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by iamjayaraj17** [microsoft/AzureDevOpsDemoGenerator#903]
getting below error while creating a new project

Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

**Comment by aksh-h** [comment]
Hi @iamjayaraj17 Please install the [ARM Outputs](https://marketplace.visualstudio.com/items?itemName=keesschollaart.arm-outputs) from the marketplace and try again.
