### ISSUE TITLE
Every template is failing upon project creation, it seems to succeed 90% of the way through then fail at the end.

### ISSUE THREAD

**Issue by JasonNewellAtAllegro** [microsoft/AzureDevOpsDemoGenerator#909]
![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/72499516/dd4215c0-43b0-4635-9181-674ad14f4130)
Every template project seems to fail with errors that are incomprehensible, but different for each template.

**Comment by aksh-h** [comment]
@JasonNewellAtAllegro This is happening with installing the extension.  Please install the ARM Outputs extension from the marketplace and try again.

Though the extensions are already installed, it might take time to enable the extension. Please wait for some time after installing the extension manually.
