### ISSUE TITLE
Can the Project summary and WIKI be copied using Demo generator (i have readme file in repo with some URL details, will this be copied)

### ISSUE THREAD

**Issue by shobanadevops1** [microsoft/AzureDevOpsDemoGenerator#911]

**Comment by shobanadevops1** [comment]
Can this be achieved in an automated manner

**Comment by aksh-h** [comment]
@shobanadevops1 this can be achieved, however Demo Generator is already covering the part of it. It can import the repository into new project on behalf of you (required necessary permissions), later it can be [published as wiki](https://learn.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser#publish-a-git-repository-to-a-wiki).
