### ISSUE TITLE
Issue In Creating the project

### ISSUE THREAD

**Issue by Sriniazure** [microsoft/AzureDevOpsDemoGenerator#930]
**Below is the Diagnostic Logs:**
TF200019: The following project already exists on the Azure DevOps Server: DemoWithTerraform. You cannot create a new project with the same name as an existing project. Provide a different na
```[tasklist]
### Tasks
```

**Comment by Sriniazure** [comment]
Tried with altogether new names, still same issue persist.

**Comment by alexxayeko** [comment]
I will suggest you use a different name for your new project when creating it.
