### ISSUE TITLE
Need Access to AzureDevOpsDemoGenerator

### ISSUE THREAD

**Issue by CubeSmartCloud** [microsoft/AzureDevOpsDemoGenerator#931]
Hello,

Please provide me access to this.  Let me know if I should provide additional details.

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/134322606/adfd9190-1992-4be5-99c2-7d641231a622)

Thanks!

**Comment by aksh-h** [comment]
@CubeSmartCloud click on ```View Diagnostics``` button to get more information. 
Try provisioning a new project with different name, add a comment below if the issue persists.
