### ISSUE TITLE
project 

### ISSUE THREAD

**Issue by yunukolusuvarna** [microsoft/AzureDevOpsDemoGenerator#933]
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
Please Install [Replace tokens](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens) extension from marketplace and try again.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

**Comment by aksh-h** [comment]
#932
