### ISSUE TITLE
Error Ansible Project

### ISSUE THREAD

**Issue by mimasisji** [microsoft/AzureDevOpsDemoGenerator#936]
Error while creating release definition: Tasks with versions 'Run playbook to deploy Azure resources:0.*' are not valid for deploy job 'Agent job' in stage Azure Dev.
https://dev.azure.com/demos529304

**Comment by aksh-h** [comment]
@mimasisji Please install [Ansible](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-ansible) extension from marketplace and try to provision the project.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
