### ISSUE TITLE
ERROR in import

### ISSUE THREAD

**Issue by Espantaleon** [microsoft/AzureDevOpsDemoGenerator#941]
Copy Diagnostic Log
VS402362: No process template with type 62a4d689-9a18-49ea-a6f9-a7d6de8345dc was found.

**Comment by aksh-h** [comment]
Looks like this error is from the customized template. When you are importing the custom generated template, make sure that you have the same process Id in the source and target organization or import the template in the same organization.

Other option is, change the process template Id in the ```ProjectSettings.json``` file and import the template.
![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/38463158/6b88686a-51d5-4e37-a58e-98824f336dea)
