### ISSUE TITLE
Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

### ISSUE THREAD

**Issue by sanskriti-07** [microsoft/AzureDevOpsDemoGenerator#944]

**Comment by aksh-h** [comment]
Please install the [ARM Outputs](https://marketplace.visualstudio.com/items?itemName=keesschollaart.arm-outputs) extension from marketplace and try to provision the project again.

If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)
