### ISSUE TITLE
classic pipelines in azure devops is depricated

### ISSUE THREAD

**Issue by parijat007** [microsoft/AzureDevOpsDemoGenerator#952]
unable to import the demo project into DevOps

Error : 
Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

help?

**Comment by aksh-h** [comment]
#951

**Comment by parijat007** [comment]
Thanks this really helped.
Though I research it and was able to enable it already.
