### ISSUE TITLE
Could not get the board 

### ISSUE THREAD

**Issue by utkarsh2020** [microsoft/AzureDevOpsDemoGenerator#962]
I had created a template using extractor tool but that did not exported my Board with my columns

**Comment by aksh-h** [comment]
@utkarsh2020 thank you for reaching us. There are some limitations on the extractor/template builder tool. Exporting and importing board columns, styles, and rules are not supported. Please find the limitation document [here](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md).
