### ISSUE TITLE
Error on Generating Demo Project for ADO

### ISSUE THREAD

**Issue by iginsighttech** [microsoft/AzureDevOpsDemoGenerator#963]
I'm getting the error when generating a project using Azure Demo Generator. The project I'm creating is PartsUnlimited. Error content is below.

Sorry….We ran into an issue! and then the rest below...

Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: The classic pipelines are disabled for this project / organization.

**Comment by aksh-h** [comment]
@iginsighttech  Looks like the creation of classic build and pipeline has been disabled in your organization.
Please follow the link for more information on [enabling/disabling classic pipelines](https://devblogs.microsoft.com/devops/disable-creation-of-classic-pipelines/).
