### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Tiagoalaz** [microsoft/AzureDevOpsDemoGenerator#966]
Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: The classic pipelines are disabled for this project / organization.

**Comment by aksh-h** [comment]
@Tiagoalaz Looks like the creation of classic build and pipeline has been disabled in your organization.
Please follow the link for more information on [enabling/disabling classic pipelines](https://devblogs.microsoft.com/devops/disable-creation-of-classic-pipelines/).
