### ISSUE TITLE
AzureDevOps

### ISSUE THREAD

**Issue by Dalton-47** [microsoft/AzureDevOpsDemoGenerator#967]
Error while creating build definition: The classic pipelines are disabled for this organization. Error while creating release definition: The classic pipelines are disabled for this organization.

**Comment by aksh-h** [comment]
@Dalton-47 Looks like the creation of classic build and pipeline has been disabled in your organization.
Please follow the link for more information on [enabling/disabling classic pipelines](https://devblogs.microsoft.com/devops/disable-creation-of-classic-pipelines/).

Provision the project again once you enable the classic pipeline feature.

**Comment by Dalton-47** [comment]
Thank you
