### ISSUE TITLE
Terraform Template Deployment Failure

### ISSUE THREAD

**Issue by jopijose** [microsoft/AzureDevOpsDemoGenerator#973]
Hello Team,

Greetings for the day!

Request to please assist with below error while trying to deploy Terraform Template.
Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*' are not valid for deploy job 'Agent job' in stage Dev.

Thanks in advance for your attention.

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

Please install the replace tokens task from the [marketplace](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens).

Run the demo generator again and try to install the extension needed by the template.

Thanks
