### ISSUE TITLE
AzDevOpsDemoGenerator

### ISSUE THREAD

**Issue by theJvp** [microsoft/AzureDevOpsDemoGenerator#977]
Diagnotic message:
Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: Tasks with versions 'ARM Outputs:6.*' are not valid for deploy job 'Agent job' in stage Stage 1.

**Comment by aksh-h** [comment]
If you are running Demo Generator on a brand new organization, please enable the ```Third-party application access via OAuth``` under ``` Organization Setting >> Policies```
![image](https://user-images.githubusercontent.com/38463158/157161949-2c77eb32-5cfb-4bc0-9e29-c33244b6024d.png)

By default, classic pipeline creation has been disabled for new organizations. To enable it, go to organization settings and provision the project. 

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/38463158/b5f894e8-074d-4c12-9cff-c9955a3d8caf)

Run the demo generator again and try to install the extension needed by the template.

Thanks
