### ISSUE TITLE
ran into an issue!

### ISSUE THREAD

**Issue by Eodgeorge01** [microsoft/AzureDevOpsDemoGenerator#984]
Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: The classic pipelines are disabled for this project / organization.

**Comment by sravan0703** [comment]
> Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: The classic pipelines are disabled for this project / organization.

any solution for this??
