### ISSUE TITLE
Terraform template error

### ISSUE THREAD

**Issue by vaibhav-on-git** [microsoft/AzureDevOpsDemoGenerator#986]
Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: Tasks with versions 'Replace tokens in terraform file:5.*, Install Terraform 0.12.3:0.*, Terraform : init:2.*, Terraform : plan:2.*, Terraform : apply -auto-approve:2.*' are not valid for deploy job 'Agent job' in stage Dev.

**Comment by aksh-h** [comment]
Install the [Terraform](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks) extension from marketplace and try to provision the project.
