### ISSUE TITLE
Importing project

### ISSUE THREAD

**Issue by sravan0703** [microsoft/AzureDevOpsDemoGenerator#987]
Hi
I am not able to import the project as it is saying "Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: The classic pipelines are disabled for this project / organization" like this. Please help me

**Comment by aksh-h** [comment]
By default, classic pipeline creation has been disabled for new organizations. To enable it, go to organization settings and provision the project. 

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/38463158/b5f894e8-074d-4c12-9cff-c9955a3d8caf)
