### ISSUE TITLE
Project Creation failed due to use of Classic pipelines

### ISSUE THREAD

**Issue by rdesutter** [microsoft/AzureDevOpsDemoGenerator#991]
Hi,

When creating the [Demo project with the template "PartsUnlimited"](https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject) I ran into the error that this is trying to classic build & release pipelines, which were by default disabled when I create a new DevOps Organisation.

Error: "Error while creating release definition: The classic pipelines are disabled for this project / organization."

Fix - in the DevOps Organisation Settings,

- turn off "Disable creation of classic build pipelines"
- turn off "Disable creation of classic release pipelines"

It might be good to add in the s[tep-by-step prereq guide](https://www.azuredevopslabs.com/labs/azuredevops/prereq/) as validation step to turn these settings off - or update the project creation so it does not use classic pipelines.

Robbie

**Comment by danhjarup** [comment]
I encountered the same error today.

**Comment by aksh-h** [comment]
By default, classic pipeline creation has been disabled for new organizations. To enable it, go to organization settings and provision the project. 

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/38463158/b5f894e8-074d-4c12-9cff-c9955a3d8caf)
