### ISSUE TITLE
Got issues while creating a new DevOps project

### ISSUE THREAD

**Issue by mckma** [microsoft/AzureDevOpsDemoGenerator#994]
Error while creating build definition: The classic pipelines are disabled for this project / organization. Error while creating release definition: The classic pipelines are disabled for this project / organization.

**Comment by lgmorand** [comment]
@mckma you may give more details if you wish some feedback ;-)

- name of your org
- screenshots
- the lab your are trying to play
- etc

**Comment by aksh-h** [comment]
By default, classic pipeline creation has been disabled for new organizations. To enable it, go to organization settings and provision the project. 

![image](https://github.com/microsoft/AzureDevOpsDemoGenerator/assets/38463158/b5f894e8-074d-4c12-9cff-c9955a3d8caf)
